### ISSUE TITLE
Helm chart missing for 0.8.0

### ISSUE THREAD

**Issue by binacloud** [jenkinsci/kubernetes-operator#1008]
**Describe the bug**
According to the instructions to install the operator through Helm, on the official website (https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/installing-the-operator/), the jenkins-operator chart is located in https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/chart.

But after adding it to helm repository, we don't see any chart called jenkins-operator, only jenkins.

The only chart that exists in this repo is the Jenkins artifact.

**To Reproduce**
$ helm repo add jenkins https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/chart
$ helm repo update
$ helm install jenkins jenkins/jenkins-operator -n jenkins

`Error: INSTALLATION FAILED: chart "jenkins-operator" matching not found in jenkins index. (try 'helm repo update'): no chart name found`

**Additional information**
We tested with previous version 0.6.1 and it's available. Is there any reason that 0.8.0 removed the jenkins-operator chart?

Kubernetes version: 1.29
Jenkins Operator version: 0.8.0

Add error logs about the problem here (operator logs and Kubernetes events).

**Comment by brokenpip3** [comment]
could you try to run

```
helm search repo jenkins
```
and put here the ouput?

In our tests we indeed use the chart by installing it from the helm as you can see [here](https://github.com/jenkinsci/kubernetes-operator/blob/3f036bdea73e6c7806d4ddc3a6673f5e33e086e1/test/bats/1-deploy.bats#L31-L38)

**Comment by binacloud** [comment]
@brokenpip3 here's the result : 

`> helm search repo jenkins
NAME            CHART VERSION   APP VERSION     DESCRIPTION
bitnami/jenkins 13.1.0          2.440.3         Jenkins is an open source Continuous Integratio...
jenkins/jenkins 5.1.7           2.440.3         Jenkins - Build great things at any scale! As t...`

there's nothing else... it does seem to have the latest version of Jenkins chart though.

**Comment by brokenpip3** [comment]
you probably received an error when you did the first command since you already have a repo called `jenkins`..

from my pov everything is working correctly:
```bash
$ docker run -it --entrypoint=sh alpine/helm 
/apps # helm repo add jenkins https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/chart
"jenkins" has been added to your repositories
/apps #  helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "jenkins" chart repository
Update Complete. ⎈Happy Helming!⎈
/apps # helm search repo jenkins
NAME                    	CHART VERSION	APP VERSION	DESCRIPTION                                       
jenkins/jenkins-operator	0.8.0        	0.8.0      	Kubernetes native operator which fully manages ...
/apps # helm template jenkins jenkins/jenkins-operator -n jenkins > /dev/null
/apps # echo $?
0
```

try to add the repo as `jenkins-operator` and install it with `jenkins-operator/jenkins-operator`

**Comment by binacloud** [comment]
@brokenpip3 that was it thanks !!

another developer added a Helm repo called Jenkins with https://charts.jenkins.io, after I added https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/chart

I removed the Helm repo and re-added with the correct chart URL and it works again.

**Comment by brokenpip3** [comment]
I'm glad it worked
