### ISSUE TITLE
jnlpUrl deprecated

### ISSUE THREAD

**Issue by necipakca** [jenkinsci/kubernetes-operator#1024]
We are getting deprecation;

WARNING    hudson.slaves.SlaveComputer#doJenkinsAgentJnlp: Agent "seed-job-agent" is connecting with the "-jnlpUrl" argument, which is deprecated. Use "-url" and "-name" instead, potentially also passing in "-webSocket", "-tunnel", and/or work directory options as needed.

Jenkins Operator version: quay.io/jenkins-kubernetes-operator/operator:v0.8.0

**Comment by brokenpip3** [comment]
it's already fixed here: https://github.com/jenkinsci/kubernetes-operator/commit/061995a65ca4a6edb8e7a50fa5ea9f9446c393e1

I'm planning a bugfix release soon, in the mean time you can use: `quay.io/jenkins-kubernetes-operator/operator:e0f52b5`

**Comment by necipakca** [comment]
Thanks for super quick response. I have switched the e0f52b5 but still I am getting same Warning.

**Comment by brokenpip3** [comment]
yep you are right, not sure why is still complaining, the seed job agent command is a simple:

```
/opt/java/openjdk/bin/java -jar /usr/share/jenkins/agent.jar \
-secret <secret> \
-name seed-job-agent \
-url <svc-name> \
-workDir /home/jenkins/agent \
-webSocket 
```
will take a look

**Comment by brokenpip3** [comment]
Ok I found the issue looking on the upstream [code](https://github.com/jenkinsci/jenkins/blob/2336ac5ffac2a06d4377a7c7623d95311dc8ea46/core/src/main/java/hudson/slaves/SlaveComputer.java#L861-L888).
We need to change this method [here](https://github.com/jenkinsci/kubernetes-operator/blob/0911dfe64a122d8727a383da40dfd9ed2c082a6b/pkg/client/jenkins.go#L201), will do it in the following days

**Comment by brokenpip3** [comment]
@necipakca it should be fixed now, can you test `quay.io/jenkins-kubernetes-operator/operator:51c3bb8` and let me know? feel free to comment if the issue will persist, I will re-open the issue
