### ISSUE TITLE
Installing the Operator

### ISSUE THREAD

**Issue by nobeler** [jenkinsci/kubernetes-operator#1077]
**Relevant links**
https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/installing-the-operator/

**Description**
when install via helm or yaml, after the  last step, I get a wrong with pod jenkins-jenkins:
Multiple plugin prerequisites not met:
Plugin git:5.2.2 (via credentials:1380.va_435002fa_924) depends on configuration-as-code:1836.vccda_4a_122a_a_e, but there is an older version defined on the top level - configuration-as-code:1810.v9b_c30a_249a_4c,
Plugin kubernetes:4246.v5a_12b_1fe120e (via credentials:1380.va_435002fa_924) depends on configuration-as-code:1836.vccda_4a_122a_a_e, but there is an older version defined on the top level - configuration-as-code:1810.v9b_c30a_249a_4c,
Plugin kubernetes-credentials-provider:1.262.v2670ef7ea_0c5 (via credentials:1380.va_435002fa_924) depends on configuration-as-code:1836.vccda_4a_122a_a_e, but there is an older version defined on the top level - configuration-as-code:1810.v9b_c30a_249a_4c,
Plugin workflow-aggregator:596.v8c21c963d92d (via pipeline-input-step:495.ve9c153f6067b_->credentials:1380.va_435002fa_924) depends on configuration-as-code:1836.vccda_4a_122a_a_e, but there is an older version defined on the top level - configuration-as-code:1810.v9b_c30a_249a_4c

I can't fix this problem via edit the helm files.

I install the jenkins operator in my macbook m3  with k8s(1.31.0) which deploy by kind.

**Comment by nobeler** [comment]
same issue:  https://github.com/jenkinsci/kubernetes-operator/issues/1069

**Comment by nobeler** [comment]
I fixed  it by edit values.yml,It turns out that the block I modified earlier was incorrect.
1,edit values.yaml  to add this stage, comment out other basePlugins stage:
 basePlugins:
    - name: kubernetes
      version: 4246.v5a_12b_1fe120e
    - name: workflow-job
      version: 1400.v7fd111b_ec82f
    - name: workflow-aggregator
      version: 596.v8c21c963d92d
    - name: git
      version: 5.2.2
    - name: job-dsl
      version: "1.87"
    - name: configuration-as-code
      version: 1836.vccda_4a_122a_a_e
    - name: kubernetes-credentials-provider
      version: 1.262.v2670ef7ea_0c5

2,edit jenkins-crd.yaml to replace configuration-as-code version.

**Comment by brokenpip3** [comment]
I'm glad you managed to fix it
