### ISSUE TITLE
how to add a plain jenkins user to deployment?

### ISSUE THREAD

**Issue by styk-tv** [jenkinsci/kubernetes-operator#111]
eventually LDAP or OIDC would be better choices, but in the interim, is there a way to add to deployment script few jenkins users? what would be the best way to do it from operator?

**Comment by tomaszsek** [comment]
Hi @styk-tv

You can accomplish it by adding groovy scripts or Configuration as Code yamls.
https://github.com/jenkinsci/kubernetes-operator/blob/master/documentation/v0.2.0/jenkins-v1alpha2-scheme.md#github.com/jenkinsci/kubernetes-operator/pkg/apis/jenkins/v1alpha2.GroovyScripts
https://github.com/jenkinsci/kubernetes-operator/blob/master/documentation/v0.2.0/jenkins-v1alpha2-scheme.md#github.com/jenkinsci/kubernetes-operator/pkg/apis/jenkins/v1alpha2.ConfigurationAsCode

Cheers

**Comment by jakalkhalili** [comment]
Hi @styk-tv 
Please close issue if your problem was solved.
