### ISSUE TITLE
Feature Request: Add support for specifying the ServiceType for Jenkins Service

### ISSUE THREAD

**Issue by blucas** [jenkinsci/kubernetes-operator#12]
It would be nice to be able to configure the `ServiceType` Jenkins.  Currently it is [hardcoded to `NodePort` or `ClusterIP`](https://github.com/jenkinsci/kubernetes-operator/blob/master/pkg/controller/jenkins/configuration/base/resources/service.go#L40-L46) depending on whether or not it is running in Minikube.

For example in GCP, one could [set the `ServiceType` to `LoadBalancer`](https://cloud.google.com/solutions/prep-kubernetes-engine-for-prod#receiving_traffic_from_the_internet_to_your_cluster) to expose Jenkins externally.

**Comment by tomaszsek** [comment]
Added in https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.0.7
