### ISSUE TITLE
user-config configmap

### ISSUE THREAD

**Issue by bechampion** [jenkinsci/kubernetes-operator#122]
hey there , the doc states
```Jenkins can be customized using groovy scripts or configuration as code plugin. All custom configuration is stored in the jenkins-operator-user-configuration-<cr_name> ConfigMap which is automatically created by Jenkins Operator.```
But in my case it doesn't seem to have been created at all by the operator , am i missing something?

Thanks !

**Comment by bechampion** [comment]
It seems based on the scheme doc that:
![image](https://user-images.githubusercontent.com/4983875/66112192-4b39b500-e5c2-11e9-8810-a768b4e36b20.png) 
which as default comes as :
```  configurationAsCode:    
    configurations: null                                                                                
    secret:    
```

**Comment by tomaszsek** [comment]
Hi @bechampion

Quoted phraze comes from 0.1.0 version but you are using 0.2.0. In the latest one you have to create configmaps by yourself and reference them in CR.

Cheers

**Comment by bechampion** [comment]
make sense , do you know if this needs to be a configmap linking plain groovy , or can it be casc ?

Thank you

**Comment by tomaszsek** [comment]
Please look at docs https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/v0.2.0/customization/. You can put groovy scripts and casc yamls in a single configmap.

**Comment by bechampion** [comment]
sorted thank you!
