### ISSUE TITLE
Fix misspellings in docs

### ISSUE THREAD

**Issue by jakalkhalili** [jenkinsci/kubernetes-operator#134]
Fix misspellings and grammar in the documentation here:
https://github.com/jenkinsci/kubernetes-operator/tree/master/website

**Comment by jonbrohauge** [comment]
@tomaszsek Want me to look at spelling for v0.2.0 as well? If so, I can fit it in start of next week.

**Comment by tomaszsek** [comment]
@jonbrohauge Please go ahead.
