### ISSUE TITLE
potential corruption of backup file

### ISSUE THREAD

**Issue by pniederlag** [jenkinsci/kubernetes-operator#143]
We have seen the backup holding a corrupt .tar.gz as most recent backup. From there we had troubles getting our instance up and running again as it was tripping restoring from that corrupt backup file.

Reason of the corrupt backup file is probably some rude interactions (like delete, scale, ..) with jenkins-related resources in a situation where it eventually turned out the hosting node was running out of disk space. So, cause of corrupt backup file is definitly on our side. 

Nonetheless, it would be nicer if the backup was created in a temporary space and only after the backup ist finished is moved to the proper backup location.

thx for your efforts, it makes managing our jenkins a really joyful experience

**Comment by tomaszsek** [comment]
> thx for your efforts, it makes managing our jenkins a really joyful experience

Thanks for that!

I will be happy if you could fix this issue by yourself. Please look at script
https://github.com/jenkinsci/kubernetes-operator/blob/master/backup/pvc/bin/backup.sh#L12 which is responsible for PVC backup. To run e2e tests please go to the `backup/pvc` and run `make docker-e2e`.

**Comment by tomaszsek** [comment]
Fixed in `virtuslab/jenkins-operator-backup-pvc:v0.0.7`.
