### ISSUE TITLE
Allow to configure # of seed job executors

### ISSUE THREAD

**Issue by pawelprazak** [jenkinsci/kubernetes-operator#158]
Right now the default is 1:
![image](https://user-images.githubusercontent.com/48874/67096828-37dd3b00-f1b9-11e9-8806-b6176a8c82eb.png)

With only 12 jobs it already takes quite long, I'd propose to make it configurable and raise the default to 3.

**Comment by aditya-soni** [comment]
Is anyone working on this ? If not, can I try to @pawelprazak ?

**Comment by pawelprazak** [comment]
yes, it is in progress and requires more changes than previously anticipated, now part of #196

**Comment by pawelprazak** [comment]
sorry for mislabeling the issue
