### ISSUE TITLE
Unable to get the Jenkins Operator running on an AWS cluster

### ISSUE THREAD

**Issue by ldimaggi** [jenkinsci/kubernetes-operator#160]
After installing the Operator by following the instructions provided here - on an AWS/OCP cluster:
* https://github.com/jenkinsci/kubernetes-operator/blob/master/documentation/installation.md
* https://github.com/jenkinsci/kubernetes-operator/blob/master/documentation/v0.2.0/getting-started.md

I am seeing this error when creating/applying the CR, the operator fails to start - this error is logged:

7m30s       Warning   FailedScheduling         pod/jenkins-jenkin-with-op               skip schedule deleting pod: username-jenkins/jenkins-jenkin-with-op
7m29s       Warning   FailedScheduling         pod/jenkins-jenkin-with-op               0/6 nodes are available: 3 Insufficient cpu, 3 node(s) had taints that the pod didn't tolerate.

Either increasing the resources in the AWS cluster nodes (to M4.large, xlarge, xlarge2 - 
https://aws.amazon.com/ec2/instance-types) - or decreasing the resources required as defined in the CRD definition results in this error:

119s        Warning   FailedCreatePodSandBox   pod/jenkins-jenkin-with-op               Failed create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_jenkins-jenkin-with-op_username-jenkins_b967a173-f1aa-11e9-be52-0ea6faa6c602_0(b51e5cb6c5d2da14a2458c70c80d22e84c03f5b38b9e6b53b0ccee62399c7582): Multus: Err adding pod to network "openshift-sdn": cannot set "openshift-sdn" ifname to "eth0": no netns: failed to Statfs "/proc/11035/ns/net": no such file or directory

**Comment by bechampion** [comment]
this looks interesting
``` 3 Insufficient cpu, 3 node(s) had taints that the pod didn't tolerate.```
What taint or tolerations are those ? mybe a noschedule?
Thanks!

**Comment by jakalkhalili** [comment]
Hi @ldimaggi 
It's probably a problem with CNI not with the operator.  Are you sure that the CNI is properly set on your cluster?
