### ISSUE TITLE
Test stage of builds, fails..

### ISSUE THREAD

**Issue by atrillanes1972** [jenkinsci/kubernetes-operator#17]
Getting errors, when running the 'Build jenkins operator' job:

+ make test
+ test
can't load package: package _/home/jenkins/workspace/build-jenkins-operator/src/github.com/jenkinsci/kubernetes-operator/cmd/manager: cannot find package "_/home/jenkins/workspace/build-jenkins-operator/src/github.com/jenkinsci/kubernetes-operator/cmd/manager" in any of:
	/usr/lib/go/src/_/home/jenkins/workspace/build-jenkins-operator/src/github.com/jenkinsci/kubernetes-operator/cmd/manager (from $GOROOT)
	/go/src/_/home/jenkins/workspace/build-jenkins-operator/src/github.com/jenkinsci/kubernetes-operator/cmd/manager (from $GOPATH)
can't load package: package _/home/jenkins/workspace/build-jenkins-operator/src/github.com/jenkinsci/kubernetes-operator/internal/errors: cannot find package "_/home/jenkins/workspace/build-jenkins-operator/src/github.com/jenkinsci/kubernetes-operator/internal/errors" in any of:
	/usr/lib/go/src/_/home/jenkins/workspace/build-jenkins-operator/src/github.com/jenkinsci/kubernetes-operator/internal/errors (from $GOROOT)
	/go/src/_/home/jenkins/workspace/build-jenkins-operator/src/github.com/jenkinsci/kubernetes-operator/internal/errors (from $GOPATH)
can't load package: package _/home/jenkins/workspace/build-jenkins-operator/src/github.com/jenkinsci/kubernetes-operator/internal/time: cannot find package "_/home/jenkins/workspace/build-jenkins-operator/src/github.com/jenkinsci/kubernetes-operator/internal/time" in any of:
	/usr/lib/go/src/_/home/jenkins/workspace/build-jenkins-operator/src/github.com/jenkinsci/kubernetes-operator/internal/time (from $GOROOT)
	/go/src/_/home/jenkins/workspace/build-jenkins-operator/src/github.com/jenkinsci/kubernetes-operator/internal/time (from $GOPATH)

Any ideas I need to check?

**Comment by tomaszsek** [comment]
@atrillanes1972 Thanks for spotting this bug.

**Comment by tomaszsek** [comment]
@atrillanes1972 Run `Seed Job from jenkins-operator` job should fix the build.
