### ISSUE TITLE
Documentation for runnning the Jenkins Operator on Openshift

### ISSUE THREAD

**Issue by waveywaves** [jenkinsci/kubernetes-operator#172]
Documentation for running the Jenkins Operator on Openshift.
- As the Jenkins Image used by Openshift has some extra requirements that come with the openshift-sync-plugin and openshift-client-plugin, it makes more sense to have documentation dedicated for us to be able to deploy on Openshift. 
- This includes documentation on creating the jenkins_edit role along with other resources.

**Comment by pawelprazak** [comment]
If you already know what are the requirements, please write them here and we'll make sure we add a section for Openshift :)

Also do you have any pointers do the openshift docs that list requirements and/or differences to e.g. EKS or GKE?

Unfortunately no one in the team has experience or access to an openshift cluster, so we'd have to set up one specifically to test openshift, and as a logical consequence every single k8s flavour. As fun as it sounds I'm afraid we don't have the bandwidth for it.

**Comment by waveywaves** [comment]
@pawelprazak Do assign this to me in that case.

**Comment by tomaszsek** [comment]
We need a new section here: https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/

Old version: https://github.com/waveywaves/kubernetes-jenkins-operator/blob/aebd747075242993f1e42ff9830643891f3adaf1/website/content/en/docs/Getting%20Started/latest/Jenkins%20Operator%20on%20Openshift.md

OpenShift Docker image: https://github.com/jenkinsci/kubernetes-operator/blob/master/test/e2e/mode_openshift.go#L19

OpenShift Docker image with Oauth: https://github.com/jenkinsci/kubernetes-operator/blob/master/test/e2e/mode_openshift_oauth.go#L24
