### ISSUE TITLE
Discussion : Container Level Validation

### ISSUE THREAD

**Issue by waveywaves** [jenkinsci/kubernetes-operator#185]
I noticed that a lot of validation was done on a container level which isn't the best way in an operator. As, admission controllers have the power to add containers / side-cars which augment the operator for specific purposes. In a scenario where a user deploys a service mesh in the cluster, and containers are added, the master pod validation will fail in the Jenkins Operator and keep restarting the pod.

**Comment by pawelprazak** [comment]
One solution would be to exclude jenkine namespace from the service mesh since it does not help here.

**Comment by waveywaves** [comment]
@pawelprazak In case of scenario when a user would like to use Jenkins with Service Mesh, to manage proxies and such, injecting sidecar containers becomes a norm. At such time the validation can break the operator.

**Comment by tomaszsek** [comment]
There are two solutions:
1. Copy the whole sidecar container definition to the Jenkins CR.(@waveywaves Cloud you provide example yaml file?)
2. Add mechanisms in operator which will skip validation for containers with name that will match particular regular expression.

**Comment by pawelprazak** [comment]
closing in favour of #197, #194, #199, #201
