### ISSUE TITLE
Disable resources.limits and resources.requests default values if not set

### ISSUE THREAD

**Issue by akram** [jenkinsci/kubernetes-operator#194]
Some users may want to keep values for resources limits and resources requests to unset in order to benefit for more container density in their kubernetes infrastructure.
This is allowed by kubernetes by not setting any value for resources.requests nor resources.limits

https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-besteffort

Currently, the Jenkins operator sets default values for these and operates reconciliation of these values.

It is preferable to keep these values unsynchronized.

**Comment by pawelprazak** [comment]
Yes, we'd like to remove the defaults in favour of CR example and a warning:
- [ ] remove resource limit and request default - no longer eforce defaults
- [ ] add warning (in logs and k8s events) for mem limit < 512MB and cpu limit < 1, as not recommended config (mitigate default low container quota)

**Comment by tomaszsek** [comment]
Added in https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.4.0
