### ISSUE TITLE
Post Admission Controller validation

### ISSUE THREAD

**Issue by pawelprazak** [jenkinsci/kubernetes-operator#197]
To mitigate issues discussed in #185 and other admission controller related issues we propose to obtain a modified version of Pod manifest.

- [ ] add mechanism that applies and immediately reads the Pod manifest to make sure we get the same version as the k8s API, after all admission controllers are done with it

Note: there is a dry-run functionality (since 1.13 AFAIR) but it's probably not necessary and its use would limit the oldest k8s version supported.

**Comment by pawelprazak** [comment]
I think we might need this more than we thought, every admission controller will cause an issue with the current implementation: service meshes, CNIs, security features, all of it.

**Comment by tomaszsek** [comment]
Added in https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.4.0
