### ISSUE TITLE
Generalize Jenkins container command validation

### ISSUE THREAD

**Issue by pawelprazak** [jenkinsci/kubernetes-operator#199]
To allow for various versions of jenkins container, we need to change validation of the master container command to only check for prefix:
```
  - command:
    - bash
    - -c
    - /var/jenkins/scripts/init.sh && ...
```
and make sure that signals are propagated(to kill the process correctly).

**Comment by tomaszsek** [comment]
Added in https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.4.0
