### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by igorhou** [jenkinsci/kubernetes-operator#20]
Hello,

jenkins-opperation keep crashing and Jenkins pod never created.

**kubectl get pods -w**
NAME                                 READY          STATUS    RESTARTS                              AGE
heapster-heapster-556f4f7648-d4m6h   2/2     Running   9                                22h
jenkins-operator-7dff456666-g4n8v         1/1     Running.  2                                86s
jenkins-operator-7dff456666-g4n8v         0/1     Error   2                                     111s
jenkins-operator-7dff456666-g4n8v         0/1     CrashLoopBackOff   2             2m4s
jenkins-operator-7dff456666-g4n8v         1/1     Running.  3                               2m20s
jenkins-operator-7dff456666-g4n8v         0/1     Error   3                                    2m49s
jenkins-operator-7dff456666-g4n8v         0/1     CrashLoopBackOff.  3             3m1s

**System info**
Distributor ID: Debian
Description:    Debian GNU/Linux 9.9 (stretch)
Release:        9.9
Codename:       stretch

**Docker Info**
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:36:00 2019
 OS/Arch:           linux/amd64
 Experimental:      false
Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**Kubenertes Info**
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by tomaszsek** [comment]
@igorhou Could you provide `jenkins-operator` pod logs and events `kubectl get events`?

**Comment by igorhou** [comment]
**kubectl logs jenkins-operator-7dff456666-g4n8v**
2019-05-31T18:53:04.983Z        INFO    controller-jenkins      manager/main.go:29      Version: v0.0.10
2019-05-31T18:53:04.983Z        INFO    controller-jenkins      manager/main.go:30      Git commit: 640767a
2019-05-31T18:53:04.983Z        INFO    controller-jenkins      manager/main.go:31      Go Version: go1.10.4
2019-05-31T18:53:04.983Z        INFO    controller-jenkins      manager/main.go:32      Go OS/Arch: linux/amd64
2019-05-31T18:53:04.983Z        INFO    controller-jenkins      manager/main.go:33      operator-sdk Version: v0.2.0
2019-05-31T18:53:04.983Z        INFO    controller-jenkins      manager/main.go:49      watch namespace: default
2019-05-31T18:53:04.983Z        INFO    leader  leader/leader.go:55     Trying to become the leader.
2019-05-31T18:53:34.985Z        ERROR   controller-jenkins      manager/main.go:108     failed to become leader: Get https://10.96.0.1:443/api?timeout=32s: dial tcp 10.96.0.1:443: i/o timeout

 **kubectl get events**
LAST SEEN   TYPE      REASON              OBJECT                                   MESSAGE
47m         Normal    Pulled              pod/heapster-heapster-556f4f7648-d4m6h   Container image "k8s.gcr.io/heapster:v1.5.2" already present on machine
7m10s       Warning   Unhealthy           pod/heapster-heapster-556f4f7648-d4m6h   Liveness probe failed: Get http://10.240.1.7:8082/healthz: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
12m         Warning   BackOff             pod/heapster-heapster-556f4f7648-d4m6h   Back-off restarting failed container
6m12s       Normal    Scheduled           pod/jenkins-operator-7dff456666-g4n8v    Successfully assigned default/jenkins-operator-7dff456666-g4n8v to node1
6m10s       Normal    Pulling             pod/jenkins-operator-7dff456666-g4n8v    Pulling image "virtuslab/jenkins-operator:v0.0.10"
6m7s        Normal    Pulled              pod/jenkins-operator-7dff456666-g4n8v    Successfully pulled image "virtuslab/jenkins-operator:v0.0.10"
2m41s       Normal    Created             pod/jenkins-operator-7dff456666-g4n8v    Created container jenkins-operator
2m41s       Normal    Started             pod/jenkins-operator-7dff456666-g4n8v    Started container jenkins-operator
2m41s       Normal    Pulled              pod/jenkins-operator-7dff456666-g4n8v    Container image "virtuslab/jenkins-operator:v0.0.10" already present on machine
62s         Warning   BackOff             pod/jenkins-operator-7dff456666-g4n8v    Back-off restarting failed container
6m13s       Normal    SuccessfulCreate    replicaset/jenkins-operator-7dff456666   Created pod: jenkins-operator-7dff456666-g4n8v
6m13s       Normal    ScalingReplicaSet   deployment/jenkins-operator              Scaled up replica set jenkins-operator-7dff456666 to 1

**Comment by tomaszsek** [comment]
@igorhou It looks like your Kubernetes cluster is unhealthy. The operator can't make calls to Kubernetes API:
```
2019-05-31T18:53:34.985Z ERROR controller-jenkins manager/main.go:108 failed to become leader: Get https://10.96.0.1:443/api?timeout=32s: dial tcp 10.96.0.1:443: i/o timeout
```
Please check CNI pods status first.

**Comment by pawelprazak** [comment]
FYI this issue will soon be closed due to inactivity
