### ISSUE TITLE
Fix issues with plugin installation in custom container images

### ISSUE THREAD

**Issue by pawelprazak** [jenkinsci/kubernetes-operator#201]
E.g. OpenShift has a different script for installing plugins, we need a mechanism to mitigate that.

A workaround would be to detect OpenShift "magic env vars", but maybe a better solution would present itself, e.g. an annotation as proposed before.

**Comment by tomaszsek** [comment]
Fixed in https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.4.0
