### ISSUE TITLE
Allow for the local dev mode to be used with various providers

### ISSUE THREAD

**Issue by pawelprazak** [jenkinsci/kubernetes-operator#203]
Currently we only support `minikube` when running operator locally against a local dev cluster but there are other options e.g. `minishift` or `crc`.

**Comment by tomaszsek** [comment]
Create two parameters:
- hostname
- port

| hostname  | port | Jenkins URL| Usecase |
| ------------- | ------------- |--|--|
| empty  | empty | http://jenkins-service-name.jenkins-namespace:jenkins-service-port | operator running inside cluster |
| jenkins.example | 80 | http://jenkins.example:80 | Jenkins exposed through Load Balancer  |
| localhost | 8080 | http://localhost:8080 | `kubectl port-forward jenkins-operator 8080` |
| $(command which will return the hostname/IP of the k8s cluster node) | `NodePort` | http://value-from-hostname-parmeter:jenkins-service-node-port | for local development purpose: minikube `minikube ip`, minishift `minishift ip`, crc `crc ip` |

**Comment by pawelprazak** [comment]
does #207 address this issue sufficiently?

**Comment by tomaszsek** [comment]
No, to do:
- documentation
- profile for crc and openshift
