### ISSUE TITLE
Move the Backup and Restore functionality to a new CR.

### ISSUE THREAD

**Issue by waveywaves** [jenkinsci/kubernetes-operator#205]
Currently in the Jenkins Operator, the Backup and restore functionality is provided in the same Jenkins CR and is also something of a lifecycle related functionality.
Having a CRs for Backup and Restore which would trigger these jobs or do them intermittently based on the user settings allows for users to not be overwhelmed by a lot of information in the Same CR and also for the operator to easily manage these operations.

If you see https://cloud.google.com/blog/products/containers-kubernetes/best-practices-for-building-kubernetes-operators-and-stateful-apps it is clearly given in point 4 (4. Compartmentalize features via multiple controllers) that "Note that each controller should correspond to a specific CRD so that the domain of each controller's responsibility is clear."

Currently that does not seem to be the case in the Operator. And it would make more sense to have CRDs/CRs based on controllers which control them and do a specific job. Otherwise instead of being distributed, the operator would tend to take up heavy tasks in a monolithic fashion.

cc @tomaszsek

**Comment by pawelprazak** [comment]
It was considered briefly, basically the main disadvantage was two loops modifying the same pod.
We can discuss it further on one of the community meetings.
