### ISSUE TITLE
Docker Build inside Jenkins Build Agent

### ISSUE THREAD

**Issue by tveal** [jenkinsci/kubernetes-operator#21]
I'm probably missing something obvious... I'm trying to build a docker image in a build agent, but keep getting the following error:
```bash
+ docker build -t my-jenkins:latest -f jenkins-docker/Dockerfile .
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```
Everything I've read online so far point to starting Jenkins with `-v /var/run/docker.sock:/var/run/docker.sock`, but I'm not sure how that works with the operator/k8s implementation. I've tried various things in the jenkins instance CR, such as:
```yaml
spec:
  master:
    volumes:
    - name: nfs
      persistentVolumeClaim:
        claimName: nfs
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
```
If I'm going down the right trail, how should I set Jenkins to start with the proper docker.sock config? If not, how should I build docker images inside Jenkins?

For reference, here's my current pipeline config:
```groovy
#!/usr/bin/env groovy

def label = "docker-jenkins-${UUID.randomUUID().toString()}"
def home = "/home/jenkins"
def workspace = "${home}/workspace/build-docker-jenkins"
def workdir = "${workspace}/src/localhost/docker-jenkins/"

def ecrRepoName = "my-jenkins"
def tag = "$ecrRepoName:latest"

podTemplate(label: label,
        containers: [
                containerTemplate(name: 'jnlp', image: 'jenkins/jnlp-slave:alpine'),
                containerTemplate(name: 'docker', image: 'docker:dind', command: 'cat', ttyEnabled: true, privileged: true),
        ]) {

    node(label) {
        dir(workdir) {
            stage('Checkout') {
                timeout(time: 3, unit: 'MINUTES') {
                    checkout scm
                }
            }

            stage('Docker Build') {
                container('docker') {
                    echo "Building docker image..."
                    sh "docker build -t $tag -f jenkins-docker/Dockerfile ."
                }
            }
        }
    }
}
```

**Comment by tomaszsek** [comment]
@tveal This should work:
```groovy
#!/usr/bin/env groovy

def label = "docker-jenkins-${UUID.randomUUID().toString()}"
def home = "/home/jenkins"
def workspace = "${home}/workspace/build-docker-jenkins"
def workdir = "${workspace}/src/localhost/docker-jenkins/"

def ecrRepoName = "my-jenkins"
def tag = "$ecrRepoName:latest"

podTemplate(label: label,
        containers: [
                containerTemplate(name: 'jnlp', image: 'jenkins/jnlp-slave:alpine'),
                containerTemplate(name: 'docker', image: 'docker', command: 'cat', ttyEnabled: true),
            ],
            volumes: [
                    hostPathVolume(hostPath: '/var/run/docker.sock', mountPath: '/var/run/docker.sock'),
            ],
        ]) {
    node(label) {
        dir(workdir) {
            stage('Checkout') {
                timeout(time: 3, unit: 'MINUTES') {
                    checkout scm
                }
            }

            stage('Docker Build') {
                container('docker') {
                    echo "Building docker image..."
                    sh "docker build -t $tag -f jenkins-docker/Dockerfile ."
                }
            }
        }
    }
}
```

**Comment by tveal** [comment]
> @tveal This should work:
> 
> ```groovy
> #!/usr/bin/env groovy
> 
> def label = "docker-jenkins-${UUID.randomUUID().toString()}"
> def home = "/home/jenkins"
> def workspace = "${home}/workspace/build-docker-jenkins"
> def workdir = "${workspace}/src/localhost/docker-jenkins/"
> 
> def ecrRepoName = "my-jenkins"
> def tag = "$ecrRepoName:latest"
> 
> podTemplate(label: label,
>         containers: [
>                 containerTemplate(name: 'jnlp', image: 'jenkins/jnlp-slave:alpine'),
>                 containerTemplate(name: 'docker', image: 'docker', command: 'cat', ttyEnabled: true),
>             ],
>             volumes: [
>                 hostPathVolume(hostPath: '/var/run/docker.sock', mountPath: '/var/run/docker.sock'),
>             ],
>         ]) {
>     node(label) {
>         dir(workdir) {
>             stage('Checkout') {
>                 timeout(time: 3, unit: 'MINUTES') {
>                     checkout scm
>                 }
>             }
> 
>             stage('Docker Build') {
>                 container('docker') {
>                     echo "Building docker image..."
>                     sh "docker build -t $tag -f jenkins-docker/Dockerfile ."
>                 }
>             }
>         }
>     }
> }
> ```
> 
> More info [kubernetes-plugin](https://github.com/jenkinsci/kubernetes-plugin)

@tomaszsek awesome! Just had to remove the extra bracket in `]) {` and now I'm building docker images from Jenkins in K8s. Thanks!

**Comment by forsberg** [comment]
Be aware of the security implications of this approach - you are exposing the docker socket of the Kubernetes node on which your build container is running, which means you can modify other docker containers running on the same host. This may be OK if your kubernetes cluster is used exclusively for Jenkins, but not if you're in a shared cluster.

Good article on the different approaches available: https://medium.com/hootsuite-engineering/building-docker-images-inside-kubernetes-42c6af855f25

**Comment by albertorm95** [comment]
One question, how do you retain the caching for Docker in a volatile container as `dind`

**Comment by JuergenSimon** [comment]
This does not appear to be working for me. I'm new to Jenkins, so please bear with me. It gets as far as the checkout step but hangs with the image build step. What could it be?  

My `Jenkinsfile` looks like this now:

```
node {
    def app
    def label = "docker-jenkins-${UUID.randomUUID().toString()}"
    def home = "/home/jenkins"
    def workspace = "${home}/workspace/build-docker-jenkins"
    def workdir = "${workspace}/src/localhost/docker-jenkins/"

    def organisation = "iontichy";
    def appName = "hello-service"
    def tag = "$organisation/$appName"

    podTemplate(label: label,
        containers: [
            containerTemplate(name: 'docker', image: 'docker', command: 'cat', ttyEnabled: true)
        ],
        volumes: [
            hostPathVolume(hostPath: '/var/run/docker.sock', mountPath: '/var/run/docker.sock'),
        ])
    {
        node(label) {
            dir(workdir) {
                stage('Clone repository') {
                    timeout(time: 3, unit: 'MINUTES') {
                        checkout scm
                    }
                }
                stage('Build image') {
                    container('docker') {
                        echo "Building docker image..."
                        sh "docker build -t $tag ."
                        app = docker.build("")
                    }
                }
                stage('Test image') {
                    app.inside {
                        sh 'echo "Tests passed"'
                    }
                }
            }
        }
    }
}
```

I tried using the Docker plugin but only got the error:  "Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"

**Comment by tomaszsek** [comment]
Hi @JuergenSimon

Where exactly it hangs `sh "docker build -t $tag ."` or `app = docker.build("")`?

Cheers
