### ISSUE TITLE
Build jenkins-operator job failed

### ISSUE THREAD

**Issue by harik8** [jenkinsci/kubernetes-operator#217]
```
Commit message: "Update olm-catalog deployment manifests"
[Pipeline] }
[Pipeline] // timeout
[Pipeline] container
[Pipeline] {
[Pipeline] sh
process apparently never started in /home/jenkins/workspace/build-jenkins-operator/src/github.com/jenkinsci/kubernetes-operator@tmp/durable-2d8be5bf
(running Jenkins temporarily with -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.LAUNCH_DIAGNOSTICS=true might make the problem clearer)
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline
ERROR: script returned exit code -2
Finished: FAILURE
```

**Comment by pawelprazak** [comment]
Please provide more information so we could help better:
- what version of the operator are you using
- what is the content of the logs from the operator
- what is the content of the logs from the jenkins master

TBH, at first glance it looks more like `kubernetes-plugin` issue.

**Comment by pawelprazak** [comment]
were you able to fix the problem?

**Comment by scotty-g** [comment]
I'm seeing the same issue. I enabled LAUNCH_DIAGNOSTICS and got additional info:

```
sh: cd: line 1: can't cd to /home/jenkins/workspace/build-jenkins-operator/src/github.com/jenkinsci/kubernetes-operator: No such file or directory
sh: can't create /home/jenkins/workspace/build-jenkins-operator/src/github.com/jenkinsci/kubernetes-operator@tmp/durable-8348a553/jenkins-log.txt: nonexistent directory
sh: can't create /home/jenkins/workspace/build-jenkins-operator/src/github.com/jenkinsci/kubernetes-operator@tmp/durable-8348a553/jenkins-result.txt.tmp: nonexistent directory
mv: can't rename '/home/jenkins/workspace/build-jenkins-operator/src/github.com/jenkinsci/kubernetes-operator@tmp/durable-8348a553/jenkins-result.txt.tmp': No such file or directory
process apparently never started in /home/jenkins/workspace/build-jenkins-operator/src/github.com/jenkinsci/kubernetes-operator@tmp/durable-8348a553
```

Bit strange. I went to the script console and the directory DOES exist and contains the repository.
```
println "ls /home/jenkins/workspace/build-jenkins-operator/src/github.com/jenkinsci/kubernetes-operator".execute().text
```

There's nothing interesting in either the operator log, instance log, or Jenkins log.

Minikube: v1.6.2
Kubernetes: v1.16.4
MacOS: 10.13.6
Jenkins Operator: v0.3.1

This was working on Friday 1/10. I fired up a brand new instance this evening and started seeing the issue.

**Comment by tomaszsek** [comment]
Hi @scotty-g,

Without the whole pipeline code we can't help you.

Cheers

**Comment by scotty-g** [comment]
It's just running the example pipeline [build-jenkins-operator](https://github.com/jenkinsci/kubernetes-operator/blob/master/cicd/pipelines/build.jenkins) when walking through the [getting started](https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/) documentation.

**Comment by scotty-g** [comment]
> This was working on Friday 1/10.

I misspoke. It wasn't the build-jenkins-operator example job I got working, it was the example [maven pipeline](https://github.com/jenkinsci/kubernetes-plugin/blob/da02f75fbf975a7751af4a768ac571241d9fcc46/examples/maven.groovy) in the kubernetes-plugin. That job works as initial validation for me, so I have no need to get build-jenkins-operator working. But I can help provide feedback if anyone is having trouble duplicating the issue.
