### ISSUE TITLE
seed-job-agent is never created for v0.2.2 of the operator.

### ISSUE THREAD

**Issue by rcosnita** [jenkinsci/kubernetes-operator#218]
I have just deployed the new version of the jenkins operator. Everything works well except the fact the seed-job-agent is never created by the operator.

This causes the seed jobs to remain in pending state forever. I think the bug is here https://github.com/jenkinsci/kubernetes-operator/blob/6d32ee71e4166b30d859447b828d85e2b0450ecc/pkg/controller/jenkins/configuration/user/seedjobs/seedjobs.go#L162 but I didn't investigated more.

Steps to reproduce:

1. Deploy the jenkins operator and a custom jenkins resource (jenkins.io/v1alpha2)
2. Make sure the jenkins custom resource contains at least one seed entry.

Expected result:

1. seed-job-agent is created.
2. seed-job is executed.

Actual result:

1. seed-job-agent is never created -> offline state
2. Defined seed job remains pending forever.

**Comment by pawelprazak** [comment]
From the limited info here, I can guess that there needs to be some adjustment to the operator's config, in the `jenkins` custom resource manifest.

Have you tried restarting operator pod?
Are there any logs from the operator you could provide? (preferably in debug mode)

**Comment by pawelprazak** [comment]
Also please let us know if the operator restart helped, because that means we need to update the migration docs.

**Comment by rcosnita** [comment]
Thank you Pawel for the quick answer. Here are some more details about this:

1. Restart of the operator did not help.
2. Here is a gist with the configuration we are currently using for installing the operator + crd: https://gist.github.com/rcosnita/dee6946c0e00560403d251338e70f2ed

I will follow up with the log entries later tonight, but I haven't seen any failure / error message in there.

**Comment by pawelprazak** [comment]
At first glance the manifests look ok. Any luck with the logs that would help?

**Comment by jakalkhalili** [comment]
Hi @rcosnita 
Could you try to redeploy Jenkins manifest (`jenkins.io/v1alpha2`) and could you give us logs from `kubectl get po`. 

This line: 
```
 if len(jenkins.Spec.SeedJobs) > 0 { 
```
reads the Jenkins manifest and counts the entries in the `spec.seedJobs` and if no seed jobs are defined then it doesn't deploy seed job agent.

So please make sure the actual manifest on the cluster (`kubectl edit jenkins veridium`) matches your manifest file.

Cheers

**Comment by tomaszsek** [comment]
@rcosnita Do you still have the problem?

**Comment by rcosnita** [comment]
Well, the seed jobs are correctly defined but the seed is not automatically created :(. I didn't have time to extract the logs in debug mode.

As an workaround, we _manually_(using some scripting in terraform) launch the seed job in our K8S cluster and join it to the jenkins master.

**Comment by tomaszsek** [comment]
@rcosnita Sorry to hear that. I have one more idea could you provide the output of the commands `kubectl -n <jenkins-namesapce> get events` and `kubectl -n <jenkins-namesapce> get deployments`?

**Comment by rcosnita** [comment]
Brilliant @tomaszsek 👍 

LAST SEEN   TYPE      REASON         KIND         MESSAGE
54m         Warning   FailedCreate   ReplicaSet   Error creating: pods "seed-job-agent-veridium-54cb989ccc-lwd4p" is forbidden: failed quota: dev-quotas: must specify cpu,memory
37m         Warning   FailedCreate   ReplicaSet   Error creating: pods "seed-job-agent-veridium-54cb989ccc-nl57f" is forbidden: failed quota: dev-quotas: must specify cpu,memory
21m         Warning   FailedCreate   ReplicaSet   Error creating: pods "seed-job-agent-veridium-54cb989ccc-nqt2v" is forbidden: failed quota: dev-quotas: must specify cpu,memory
4m28s       Warning   FailedCreate   ReplicaSet   Error creating: pods "seed-job-agent-veridium-54cb989ccc-8spvm" is forbidden: failed quota: dev-quotas: must specify cpu,memory
54m         Warning   FailedCreate   ReplicaSet   Error creating: pods "seed-job-agent-veridium-889c8db94-z9m6b" is forbidden: failed quota: dev-quotas: must specify cpu,memory
37m         Warning   FailedCreate   ReplicaSet   Error creating: pods "seed-job-agent-veridium-889c8db94-2zwqk" is forbidden: failed quota: dev-quotas: must specify cpu,memory
21m         Warning   FailedCreate   ReplicaSet   Error creating: pods "seed-job-agent-veridium-889c8db94-24vhb" is forbidden: failed quota: dev-quotas: must specify cpu,memory
4m28s       Warning   FailedCreate   ReplicaSet   Error creating: pods "seed-job-agent-veridium-889c8db94-xmbrm" is forbidden: failed quota: dev-quotas: must specify cpu,memory

Indeed, the cluster accept only containers which specify the cpu and memory. Thank you so much for clearing this out. Do you think we should add this information in the readme and also mention the troubleshooting process?

Anyway, I can make a PR for the doc if you want, just let me know. From my point of view you can close this PR because there is no issue with the code.

Again, thank you so much.

**Comment by rcosnita** [comment]
Actually, a new question is relevant here :): how can we specify the resources for the seed-job-agent container given it does not appear in the definition of the CRD?

**Comment by pawelprazak** [comment]
Please look at #228
