### ISSUE TITLE
Support setting kube-context only when necessary instead of default minikube

### ISSUE THREAD

**Issue by waveywaves** [jenkinsci/kubernetes-operator#219]
### Current Usage
`Makefile` scripts are picking out minikube or any other kubernetes config for running the operator. 

### Proposed Enhancement
It would be logical to define which instance of kubernetes needs to be used by setting the kube context. The `$KUBECONFIG` file which is in its default location, usually at `~/.kube/config` contains the `current-context` being used and references to other contexts which have been used before. For more info do go through https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/ 

### Pros
- Thinner and easy to manage makefile
- Single Build process for all

## Summary
This is causing default kubecontext to be minikube which makes users set the kubecontext everytime they would like to use their own kubernetes context

cc @jakalkhalili @tomaszsek

**Comment by tomaszsek** [comment]
It is already done. You can set kubectl context there https://github.com/jenkinsci/kubernetes-operator/blob/master/config.env#L13.

**Comment by waveywaves** [comment]
@tomaszsek The context shouldn't be hardcoded like that I think, that way even though I would like to run it on my cluster it will go searching for minikube, and switching the context. That would be considered as a bug.

**Comment by pawelprazak** [comment]
Implicit kubectl context can be dangerous. You can accidentally target one of you production clusters.

IMO explicit context is the way to go, e.g. `make all CTX=minikube` with minikube as the default to minimize the damage and optimize for the most common developer use case.

**Comment by waveywaves** [comment]
@pawelprazak It is the norm in operators as far as I have seen to have it be run in the local contex for developement. Considering that this has become an opinionated view understandably, `make run` would only be used in a development context if I am not wrong. And the context in use would also reflect the user's permisisons in the ase of the cluster in production. Developers usually don't have permission to carry out production level tasks such as final deployment of the application as far as I know.
