### ISSUE TITLE
Improve developer guide section in docs

### ISSUE THREAD

**Issue by jakalkhalili** [jenkinsci/kubernetes-operator#231]
Since we had a new way to run E2E tests on non-linux operating systems for eg. macOS (see https://github.com/jenkinsci/kubernetes-operator/commit/667d263f7d8720ba2f043d790c1f2c9642b66af8) we must edit the `Developer Guide` website page `https://jenkinsci.github.io/kubernetes-operator/docs/developer-guide/` due to change in the building mechanism.

**Comment by waveywaves** [comment]
@jakalkhalili Is thi wrt the recent Dockerfile changes ?

**Comment by tomaszsek** [comment]
@waveywaves Yes it related to the Docker build improvement.
