### ISSUE TITLE
spec.master.volumes doesn't work

### ISSUE THREAD

**Issue by pbecotte** [jenkinsci/kubernetes-operator#240]
Needed to mount ca certificates into the master. Wound up reading the source code to figure out why it wasn't working-

https://github.com/jenkinsci/kubernetes-operator/blob/5a8f82c0f0b0423cf2a406ffda777f63a300cbe1/pkg/controller/jenkins/configuration/base/validate.go#L130

I have no idea why this configuration check is here... looking at the actual operator code, it seems like it would work if it wasn't rejected at the validation stage. In a related note, this seems like the kind of thing that should be mentioned in the docs as not working?

**Comment by tomaszsek** [comment]
Fixed in https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.3.1
