### ISSUE TITLE
Jenkins operator in different namespace

### ISSUE THREAD

**Issue by bechampion** [jenkinsci/kubernetes-operator#250]
Hey guys.

I have the Jenkins operator pod and deployment on namespace `default` , but i want to create a jenkins Kind resource in a different namespace.
When i do `kubectl get jenkins -n different` i can see the instance , but seems like the reconciliation process never actually creates a `pod` for that jenkins instance.
I've checked the logs in the operator and there's nothing there , any clues , can this work?

Thank you

**Comment by tomaszsek** [comment]
Hi @bechampion,

Please look at this https://github.com/jenkinsci/kubernetes-operator/blob/master/deploy/operator.yaml#L25.

Cheers

**Comment by bechampion** [comment]
Hi @tomaszsek amazing,  can you have a list here?

**Comment by tomaszsek** [comment]
It can be empty and in this situation all namespaces in k8s will be watching but I don't recommend this approach. I recommend one operator for one jenkins.

**Comment by bechampion** [comment]
Hi , is there any reason that you recommend that ?  
Thank you

**Comment by tomaszsek** [comment]
The operator produces lot of logs and it will more clear for users and it consumes small amount of resources.

**Comment by tomaszsek** [comment]
Moreover operator executes backup command before Jenkins pod deletion and it's blacks the reconciliation loop.

@bechampion Can I close the issue?

**Comment by goraxe** [comment]
@tomaszsek I have a similar use case, we want to handle all of our jenkins masters in a central cluster using differenent namespaces for different teams.  I was expecting one operator to handle many (maybe hundreds) of jenkins masters.  Namespaces would be used for quota/permissions, we could get away with one watch namespace as long as we can launch/manage in different namespaces.  In terms of log volume, we don't care customer teams won't see them.  Are there other design constraints I should know about?  We might be able to throw a little bit of dev time this way if there are limitations to be solved.

**Comment by tomaszsek** [comment]
Hi @goraxe,

Jenkins operator creates only one reconciliation loop worker to avoid concurrency problems. I don't know how operator will work with more than concurrent worker. You can set it as described here https://github.com/operator-framework/operator-sdk/issues/1938.

Logs from operator are important for the debugging purposes. I you will go with one instance it will be not acceptable from user point of view.

In multitenant environment I recommend to give full control of Jenkins to the team including operator.

Cheers

**Comment by haf-tech** [comment]
so the recommendation is, to have in any namespace a
- jenkins_operator
- and an jenkins instance
if one need in the namespace Jenkins?

**Comment by tomaszsek** [comment]
> is it right, that the recommendation is, to have in any namespace a
> 
> * jenkins_operator
> * and an jenkins instance
>   if one need in the namespace Jenkins?

yes
