### ISSUE TITLE
JenkinsJobTrigger type

### ISSUE THREAD

**Issue by styk-tv** [jenkinsci/kubernetes-operator#253]
Hi @tomaszsek

Is there any appetite to start triggering Jenkins jobs using Kubernetes Job type mechanism? 
https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/

Maybe get to a point where there is a jenkins-operator type for a job run. You know, not the one that defines the job nor the script, but one that actually triggers the execution providing/overriding input params/secrets.

**Comment by pawelprazak** [comment]
Jenkins + kubernetes-plugins is effectively the same as k8s job.
Kubernetes Job just runs a pod once, it's not very sophisticated. 

What we plan is to make it possible to use k8s in a more Jenkins-native way: https://github.com/jenkinsci/kubernetes-operator/issues/196

**Comment by styk-tv** [comment]
@pawelprazak well what is clearly missing is ability to trigger a job by providing sort of a JenkinsJob type where you reference existing job/pipeline and feed it with parameters and execute from command line. And #196 doesn't seem to address it from that angle. Don't you think?

**Comment by pawelprazak** [comment]
I'm sorry, I don't fully understand the example, could you elaborate on
your use case?

pt., 24 sty 2020, 15:30 użytkownik Peter Styk <notifications@github.com>
napisał:

**Comment by styk-tv** [comment]
As a Kubernetes user I want to be able to trigger more complicated Jenkins jobs using Kubernetes API (or kubectl cli)

I want to be able to reference specific job and specify job/pipeline parameters in a JenkinsJob type and post them to Kubernetes-Operator CRD to be interpreted as a trigger to start an existing Jenkins job.

**Comment by tomaszsek** [comment]
@styk-tv Could you describe your use case? Why you want use Kubernetes API to trigger Jenkins job/pipeline?

**Comment by styk-tv** [comment]
@tomaszek you are on a quest to create a jenkins-kubernetes-operator, such operator is incomplete unless a fundamental capability exists that allows the user to use kubernetes itself to launch the job.

and I don't say it lightly, i spent last 8 years with jenkins and last 5 years with kubernetes. i have built systems that launch jenkins jobs both from cli and rest, there is always a need to run all those nicely created and full of plugin jobs.

by allowing JenkinsJob type into the mix, you are taking Jenkins into a realm of truly kubernetized experience by allowing other users to use kubernetes-native method (cli+api) and its own rbac-controlled space 

I'm a l ittle surprised I have to explain this, however as true guardians of this operator I understand your focus on agents, plugins, scalability etc, but you should also level down with the user of this system, whether i'm writing some terraform script or bootstrapping another, at the end, I need to run a job. and not with some half-baked hack, but ideally using best tool for all the jobs.....   kubectl

**Comment by pawelprazak** [comment]
@styk-tv thank you for taking the time to explain you use case, I appreciate that.

I understand your point, the question I have is is it something that the operator should provide, or is it a job for a plugin (I think openshift has one) or high level abstraction like knative

**Comment by jstrachan** [comment]
to avoid confusion maybe call this CRD `JenkinsJobTrigger` as its really about triggering via a CRD and using the Operator rather than creating Jenkins `Job` resources inside a Jenkins server

**Comment by styk-tv** [comment]
@pawelprazak i'm not sure how to relate to that, all I think its missing is ability to start an existing job and provide job params.

...and now that I think of it @jstrachan might be right, maybe there is a confusion here, and maybe `JenkinsJobTrigger` would be a better name.

Without ability to start a job using kubectl, although very much in love, feels somehow incomplete.

**Comment by tomaszsek** [comment]
:+1: for the new name `JenkinsJobTrigger`.
