### ISSUE TITLE
Documentation on using jenkins operator in a kubernetes cluster with windows containers along with linux containers

### ISSUE THREAD

**Issue by salluvada** [jenkinsci/kubernetes-operator#254]
This is more a request to update documentation as I couldn't find references to using jenkins operator in a setting where the operator can spin up seed jobs in a kubernetes cluster that has both windows and linux VMs in it. Build pipelines that need windows machine should spin up containers on the windows vms where as Build pipelines that can run on linux should spin up containers on linux. Is this currently achievable?

Also as the windows vms and linux vms would be running on separate node pools, can the operator scale the appropriate node pool as the load increases on the jenkins instance to build several pipelines in parallel. Any support or guidance that can be provided for this would be greatly appreciated.

**Comment by tomaszsek** [comment]
Hi @salluvada,

To run Kubernetes pod on specific node you have to use node selector https://kubernetes.io/docs/concepts/configuration/assign-pod-node/. The jenkins kubernetes plugin gives you chance to configure it like here https://github.com/jenkinsci/kubernetes-plugin/blob/master/examples/windows.groovy.

To provision additional nodes in pools you have to use https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler.

Cheers

**Comment by salluvada** [comment]
thank you @tomaszsek. The information you provided was quite helpful. I am was able to successfully test an autoscale scenario with just a single node linux node pool. Going to test with a multi node pool cluster using windows and linux nodes.
