### ISSUE TITLE
Test Request : Jenkins Multiple Namespace e2e Test

### ISSUE THREAD

**Issue by waveywaves** [jenkinsci/kubernetes-operator#256]
e2e Test for running multiple Jenkins instances multiple namespaces and same namespaces
This will allow us to test High Availability and cluster scoped control of the Jenkins Operator.

**Comment by tomaszsek** [comment]
The Jenkins operator is namespace scoped operator(https://github.com/operator-framework/operator-sdk/blob/master/doc/operator-scope.md#namespace-scoped-operator-usage). The cluster scope is not supported.

The only test we can write is test which deploys operator in single namespace and operator multiple Jenkins instances in the same namespace. Do you want to configure how many Jenkins instances should be created in the test?

**Comment by waveywaves** [comment]
In production environments, it is possible that clusterscope would be preferred as Jenkins is seen as a resource hungry application on Kubernetes. Allowing it to be cluster scoped would allow for promotion of images from one namespace to the other where production envs are set to move container images from eg: build to test namespace and then test to deploy namespace, which will have the ingress present for final releases. That was the context in which I was thinking about this. 

If cluster scope is not supported, it would be a good option for allowing it to be cluster scoped, @tomaszsek what do you think ? How do you think we should go about this ?

**Comment by waveywaves** [comment]
Based on https://github.com/operator-framework/operator-sdk/blob/master/doc/operator-scope.md#cluster-scoped-operator-usage The operator can still be used in cluster-scoped mode right ?

**Comment by tomaszsek** [comment]
Cluster scope requires admin access in Kubernetes cluster. Most of our users uses multi tenant Kubernetes clusters and don't have admin access. Now you have full control of the operator and the Jenkins instances created by it. Cluster wide is not good approach.
