### ISSUE TITLE
Try to install Jenkins Operator 0.2.2 in Openshift 4.3, but have a problem with fsgroup

### ISSUE THREAD

**Issue by johnlongo** [jenkinsci/kubernetes-operator#259]
I first had to change the run-as-user from 1000 to 1000690000.

Now I'm getting a issue with the fsgroup value of 1000, any Ideas what I can try.

Reconcile loop failed 10 times with the same error, giving up: pods "jenkins-jenkins-instance-1" is forbidden: unable to validate against any security context constraint: [fsGroup: Invalid value: []int64{1000}: 1000 is not an allowed group]	{"cr": "jenkins-instance-1"}

**Comment by waveywaves** [comment]
@johnlongo Have you tried with the latest release of the Operator, the reconcilation issue on the securityContext has been fixed.

**Comment by johnlongo** [comment]
I'll give v0.3.2 a try and let you know how it goes, thank you for the feedback

**Comment by johnlongo** [comment]
Tried Opertor v.3.2, when I tried to create the instance see jenkins_instance.yaml.txt, getting the following error

2020-01-29T06:13:24.684Z	WARN	controller-jenkins	jenkins/jenkins_controller.go:152	Reconcile loop failed 10 times with the same error, giving up: pods "jenkins-instance-1" is forbidden: unable to validate against any security context constraint: [fsGroup: Invalid value: []int64{1000}: 1000 is not an allowed group spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 1000: must be in the ranges: [1000710000, 1000719999]]	{"cr": "instance-1"}

[jenkins_instance.yaml.txt](https://github.com/jenkinsci/kubernetes-operator/files/4126467/jenkins_instance.yaml.txt)

**Comment by tomaszsek** [comment]
Hi @johnlongo,

Currently we are working to support OpenShift in Jenkins operator. There is no release which can be used but it will be released soon(v0.4.0).

Cheers

**Comment by johnlongo** [comment]
If you need me to test it out, be happy to do it

**Comment by cody-pope** [comment]
@tomaszsek Any update on the OpenShift support for this?  It'd be awesome to be able to use this operator.

**Comment by tomaszsek** [comment]
We are waiting for #303 to release `0.4.0`.

**Comment by johnlongo** [comment]
I have openshift 4.3.8 running in a VMware 6.7 cluster with 3 controlers and 6 compute nodes. I offered to help with there testing but never got a response so I haven't looked at that again.


<img width="1044" alt="2020-03-26_12-24-13" src="https://user-images.githubusercontent.com/23619505/77670775-05e8b580-6f5d-11ea-89c0-d975d5cfda01.png">

**Comment by tomaszsek** [comment]
Fixed in https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.4.0
