### ISSUE TITLE
All INFO logging of user configuration changes 

### ISSUE THREAD

**Issue by pawelprazak** [jenkinsci/kubernetes-operator#26]
Currently the operator logs does not show when the user config change was detected (CR,Secret or ConfigMap).

This is confusing for the user when unsuccessful config change attempts show up in logs
(e.g. cr plugin config fail) and then after correction there is no indication of the change in the internal state of the operator or the jenkins (at least from the logs).

It would be very helpful if we could get INFO log on a detected change of a CR, Secret or ConfigMap

**Comment by tomaszsek** [comment]
Added in https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.0.12
