### ISSUE TITLE
Jenkins customisation link is dead

### ISSUE THREAD

**Issue by kboom** [jenkinsci/kubernetes-operator#260]
https://jenkinsci.github.io/kubernetes-operator/docs/security/v0.1.1/getting-started.md#jenkins-customisation link is dead (404)

**Comment by jakalkhalili** [comment]
Hi @kboom,
It seems to be working:
https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/v0.1.x/customization/

**Comment by tomaszsek** [comment]
Hi @kboom 

Where did you find the broken link?

Cheers

**Comment by kboom** [comment]
Here:

https://jenkinsci.github.io/kubernetes-operator/docs/security/

**Comment by SylwiaBrant** [comment]
Working for v5.x.x. Can finally be closed.
