### ISSUE TITLE
Ability to add labels on master pod

### ISSUE THREAD

**Issue by myhau** [jenkinsci/kubernetes-operator#262]
Example use case: pod identities in Azure. 

In order to access Azure resources (for example KeyVault through Azure Flex Vault) without having to use service principal you have to create `AzureIdentityBinding` and specify `aadpodidbinding` **label** on pod.

https://github.com/Azure/kubernetes-keyvault-flexvol#option-2-pod-identity

**Comment by tomaszsek** [comment]
Added in https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.3.3

**Comment by myhau** [comment]
Wow, that was quick 🔥 ! Thank you !
