### ISSUE TITLE
Cannot specify `jenkins-home` volumeMount for `jenkins-master` container

### ISSUE THREAD

**Issue by wendtek** [jenkinsci/kubernetes-operator#265]
### Issue
In the CR spec, adding a `volumeMount` with `name: jenkins-home` to the container named `jenkins-master` will result in a warning similar to the following:
```
WARN	controller-jenkins	jenkins/jenkins_controller.go:153	Reconcile loop failed 10 times with the same error, giving up: Pod "jenkins-cc-jenkins" is invalid: spec.containers[0].volumeMounts[6].mountPath: Invalid value: "/var/jenkins/jenkins": must be unique	{"cr": "cc-jenkins"}
```
I personally was confused by this as my experience working with multiple containers in a pod led me to put the `volumeMount` in both, making this counter-intuitive to me and possibly other Kubernetes users.

### Suggestion
I suggest either checking for and overriding if that `volumeMount` is supplied in the spec, or adding to the documentation that it is created by default. The two places I think it would be relevant in the documention are:
* [schema docs](https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/schema/#github.com/jenkinsci/kubernetes-operator/pkg/apis/jenkins/v1alpha2.Container)
* [backup and restore docs](https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/configure-backup-and-restore/). The documentation here does show an example without the volumeMount for the master container, but does not indicate why

**Comment by Nuru** [comment]
I would like to be able to specify `jenkins-home` as a PersitentVolume so I can include it in my global backup and restore scripts, especially since the operator backup/restore seems not to be working well: #104 #210 #267 #273

**Comment by tomaszsek** [comment]
@Nuru sorry, but we can't do that. When we will allow this Jenkins will be mutable and this is not acceptable form the architecture point of view. We have to improve the backup and restore mechanism.

**Comment by Nuru** [comment]
> @Nuru sorry, but we can't do that. When we will allow this Jenkins will be mutable and this is not acceptable form the architecture point of view. We have to improve the backup and restore mechanism.

@tomaszsek right now if I make a change to the Jenkins resource, nothing is restored and the backups start over from 1. That is pretty harsh. 

I would prefer that the full JENKINS_HOME is restored and the configuration as code is applied on top of it. Until then, I would prefer not to lose JENKINS_HOME in the first place.

**Comment by tomaszsek** [comment]
@Nuru I think the issue is somewhere else please create a separate issue with the details(operator version and Jenkins CR). BTW did you look at the operator logs?

**Comment by Sig00rd** [comment]
Hello, thanks for your input. I've updated the docs in #608
