### ISSUE TITLE
Operator does not restart jenkins when plugin dependency version is changes

### ISSUE THREAD

**Issue by pawelprazak** [jenkinsci/kubernetes-operator#27]
Steps to reproduce:
- start a Jenkins with a plugin configuration that has dependencies
- change version of a one of the plugin's dependency
- observe jenkins was not restarted and is still running old version

**Comment by tomaszsek** [comment]
Fixed in https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.0.12

**Comment by pawelprazak** [comment]
can still reproduce in v0.0.12

**Comment by tomaszsek** [comment]
Fixed in https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.1.0
