### ISSUE TITLE
Ability to set username in Jenkins CR

### ISSUE THREAD

**Issue by chrisgrove-keysight** [jenkinsci/kubernetes-operator#271]
From [Jenkins Operator Active Directory #47
](https://github.com/jenkinsci/kubernetes-operator/issues/47#) Comments

> Is it possible to modify the 'jenkins-operator' username as part of the Jenkins Pod Deployment? It is non-trivial to add jenkins-operator to our directory service.
> To clarify - I want to set the user value before the credential is created. We need to deploy several Jenkins instances. I would prefer setting the user jenkins-operator-credentials-<cr_name> as part of the deployment compared to editing the credential secret after the pod is launched.

**Comment by tomaszsek** [comment]
Hi @chrisgrove-keysight,

What about password? Do you need set the password too?

Cheers

**Comment by chrisgrove-keysight** [comment]
Greetings @tomaszsek,

For my scenario (Active Directory), we do need to set the password. 

Thank you.

**Comment by chrisgrove-keysight** [comment]
Greetings @tomaszsek,

I discovered if I create the jenkins-operator-credentials-_name_ prior to the Jenkins CR everything works great. 

Documentation would be nice but no changes are necessary.
