### ISSUE TITLE
Could we make this be overwritten by an env variable on the Jenkins Kind definition?

### ISSUE THREAD

**Issue by bechampion** [jenkinsci/kubernetes-operator#272]
https://github.com/jenkinsci/kubernetes-operator/blob/852d72901878e7119b6df35e9a537b8152d688ac/pkg/controller/jenkins/configuration/user/seedjobs/seedjobs.go#L420

**Comment by tomaszsek** [comment]
Hi @bechampion,

Why you need to configure Jenkins URL for seed job agent?

Cheers
