### ISSUE TITLE
Install of some plugins are failing

### ISSUE THREAD

**Issue by riqio** [jenkinsci/kubernetes-operator#274]
we are trying to add the following plugins as part of the deployment 
 - name: aws-credentials
      version: 1.28
    - name: pipeline-aws
      version: 1.39
    - name:  jenkins-multijob-plugin
      version: 1.32
    - name:  jobConfigHistory
      version: 2.24
When the pod is deploying we are seeing the following error message 
E0217 18:32:36.484217       1 reflector.go:134] pkg/mod/k8s.io/client-go@v0.0.0-20181213151034-8d9ed539ba31/tools/cache/reflector.go:95: Failed to list *v1alpha2.Jenkins: v1alpha2.JenkinsList.Items: []v1alpha2.Jenkins: v1alpha2.Jenkins.Spec: v1alpha2.JenkinsSpec.Master: v1alpha2.JenkinsMaster.BasePlugins: []v1alpha2.Plugin: v1alpha2.Plugin.Version: ReadString: expects " or n, but found 1, error found in #10 byte of ...|version":1.32},{"nam|..., bigger context ...|.4"},{"name":"jenkins-multijob-plugin","version":1.32},{"name":"jobConfigHistory","version":2.24}],"|...

**Comment by tomaszsek** [comment]
Hi @riqio,

Please put version in double quotes:
version: "1.23"

Cheers

**Comment by riqio** [comment]
Thank @tomaszsek I am able to deploy the jenkins-operator with all the plugins i want
