### ISSUE TITLE
Script that creates a tar-ball for charts does not filter out existing tarballs.

### ISSUE THREAD

**Issue by apogrebnyak** [jenkinsci/kubernetes-operator#279]
Unpack `kubernetes-operator/chart/jenkins-operator/jenkins-operator-0.0.8.tgz` which currently stands at 67201 bytes.

You will see that inside, it has tarballs for ALL previous versions as well as a smaller tarball for `jenkins-operator-0.0.8.tgz`, which is 44801 bytes.

When you unpack that one...
You will see that inside, it has tarballs for ALL previous versions as well as a smaller tarball for `jenkins-operator-0.0.8.tgz`, which is 22397 bytes.

...

I did not try to unpack the last one, but you can see a pattern here.

**Comment by tomaszsek** [comment]
Hi @apogrebnyak,

Should be fine now.

Cheers
