### ISSUE TITLE
Feature Request : Sync CA Certificates, Keys etc. via Secrets

### ISSUE THREAD

**Issue by waveywaves** [jenkinsci/kubernetes-operator#280]
This would allow users to update the default Jenkins keystore at `/etc/pki/java/cacerts` with their own certificates which they can inject via ConfigMaps or Secrets.

**Comment by tomaszsek** [comment]
Hi @waveywaves,

In Jenkins CR you can add volume pointing to the secret or config map and that mount it at `/etc/pki/java/cacerts`.

Cheers
