### ISSUE TITLE
How to set plugin settings (.xml file)?

### ISSUE THREAD

**Issue by styk-tv** [jenkinsci/kubernetes-operator#281]
Typical plugin when added is setup through Manage Jenkins / Configure System
In there there would be a section for newly added plugin.

In most cases this manifests itself in an .xml file in the home of jenkins. For example, I've added :

```
    - name: ansicolor
      version: 0.6.3
```

This puts the file `hudson.plugins.ansicolor.AnsiColorBuildWrapper.xml` in `/var/jenkins/home. In my case I want to make sure that the default scheme selected is `xterm` which i checked ends up as

```
<hudson.plugins.ansicolor.AnsiColorBuildWrapper_-DescriptorImpl plugin="ansicolor@0.6.3">
  <globalColorMapName>xterm</globalColorMapName>
</hudson.plugins.ansicolor.AnsiColorBuildWrapper_-DescriptorImpl>
```

By default the globalColorMapName is empty, it has to be set.

Question to you guys, what is the recommended way for this or any plugin to do this.

1. Replace a whole file as ConfigMap with correct settings? 
2. Do this programmatically.

At this point I think it would be easier to do this as configmap for easy access in the future and pattern. I'm looking at the documentation of https://github.com/jenkinsci/configuration-as-code-plugin but I can't seem to do this properly as per https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/customization/ Would you mind explaining how to add settings as per above? Many thanks...

**Comment by tomaszsek** [comment]
Hi @styk-tv,

Definitely you should configure it programmatically via CasC or groovy script. In the CasC there is demo folder but it doesn't include all examples.

To configure it through CasC https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/README.md#initial-configuration:
- install plugin you want to configure
- run Jenkins and click `Manage Jenkins`
- `Click the Documentation link at the bottom of the Configuration as Code page.`
- `If you want to configure a specific plugin, search the page for the name of the plugin. The page will show you which root element belongs to the configuration. Most installed plugins belong under the unclassified root element.`
- you will find properties you can configure via CasC

Not all properties can be configured via CasC, sometimes you have to use groovy scripts:
- search for plugin in GitHub https://github.com/jenkinsci/ansicolor-plugin
- dig into code and figure out how to set required properties

Cheers
