### ISSUE TITLE
Jenkins backup.sh script exclude jobs/*/config.xml

### ISSUE THREAD

**Issue by prabhukasisekar** [jenkinsci/kubernetes-operator#282]
Hello,
We see that in jenkins backup.sh script there is code snippet to exclude jobs/*/config.xml files.
Why is config.xml files are excluded since they are core job configuration files which we needed.
We changed the script removing the exclude part in backup.sh locally executed backup, restore and restarted jenkins to see the jobs restored. (This is what we want)
1)**Can you please update the backup.sh script to include jobs/*/config.xml files?**
2) is it possible to login as root to container and update the script?

Is jenkins restart required to see the jobs restored? (we did not see the jobs restored without restart of jenkins, just want to confirm this behaviour).

Thank you,
Prabhu Kasisekar

**Comment by tomaszsek** [comment]
Hi @prabhukasisekar,

This was done on purpose. Jenkins created by the operator is immutable so any changes made by hand in the UI will disappear after the restart. You have to add you job definition via the plugin `job-dsl`. More info you can find here https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/configuration/.

Cheers
