### ISSUE TITLE
Jenkins Instances not deleted after deletion of Operator Pod

### ISSUE THREAD

**Issue by waveywaves** [jenkinsci/kubernetes-operator#283]
The Jenkins Instances created by the Operator are not deleted upon deletion of the Operator Pod.
This is not the case with Pods only, this is wrt all the resources created by the Operator.

Considering the Operator is the owner of these resources, upon deletion of the owner the the underlying resources should also get deleted.

**Comment by tomaszsek** [comment]
Hi @waveywaves,

Operator operates on Jenkins instances and it is not owner of them. All created resources including jenkins pod have owner set as Jenkins CR. After delete Jenkins CR all related k8s resources will be deleted as well.

Cheers

**Comment by waveywaves** [comment]
Oh yeah, thanks for the clarity :thinking: :smile:
