### ISSUE TITLE
configuration-as-code-support is listed as required plugin, but it has been deprecated.

### ISSUE THREAD

**Issue by apogrebnyak** [jenkinsci/kubernetes-operator#291]
When specifying `basePlugins` list, if I do not provide `configuration-as-code-support` it complains that required plugin is missing.

This plugin has been marked as deprecated -> https://plugins.jenkins.io/configuration-as-code-support/

**Comment by trieszklr** [comment]
probably it is marked deprecated as it was proposed and accepted to be part of std component of jenkins?
https://github.com/jenkinsci/jep/tree/master/jep/201

**Comment by tomaszsek** [comment]
Required tasks:
- remove ti from base plugins https://github.com/jenkinsci/kubernetes-operator/blob/master/pkg/controller/jenkins/plugins/base_plugins.go#L22
- run operator locally and make sure that Jenkins is up and the plugin `configuration-as-code-support` is not installed
- run e2e tests 

Developer guide is located [here](https://jenkinsci.github.io/kubernetes-operator/docs/developer-guide/)

**Comment by tomaszsek** [comment]
Fixed in https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.4.0
