### ISSUE TITLE
Ability to add all the repo username and password as part of the deployement

### ISSUE THREAD

**Issue by riqio** [jenkinsci/kubernetes-operator#295]
Does the jenkins operator has the ability to add repo username and password as part of the deployment. 

I want to be able to add my Github,Bitbucket and AWS creditionals(access and secret key) when I deploy the jenkins operator

Thanks
Venkata

**Comment by tomaszsek** [comment]
Hi @riqio,

You have to add your secrets on your own and the link them in Jenkins CR.

Seed jobs - https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/configuration/#configure-ssh-authentication
CasC & groovy script - https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/customization/#using-secrets-from-a-groovy-script

Cheers
