### ISSUE TITLE
Custom auth overridden on jenkins restart

### ISSUE THREAD

**Issue by justyns** [jenkinsci/kubernetes-operator#3]
It looks like this script gets run every time Jenkins starts up:

https://github.com/jenkinsci/kubernetes-operator/blob/v0.0.4/pkg/controller/jenkins/configuration/base/resources/init_configuration_configmap.go#L16-L30

We're currently configuring a 3rd party auth plugin in the user-config groovy scripts.   This works fine until someone either restarts Jenkins from the UI or another config script does a safe restart.  This causes the above script to run again and then the new auth plugin has to be reconfigured.

Can you provide some guidance on how this should be resolved?  The options I can think of right now are:

1. We can probably override the `init-configuration` configmap and remove that part of the init script.  I don't know if this configmap ever gets re-created by the operator though, or if it's meant to be overridden.
2. Should this be a feature request to have an option in the CR for `customAuth: true` or something similar that the script can check and skip those config items?

**Comment by tomaszsek** [comment]
@justyns Thanks for spotting it!

1. This configmap is owned by operator and will be overwritten.
2. We can fix it without adding custom field to CR.

I will look at this tomorrow.

**Comment by tomaszsek** [comment]
Fixed in https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.0.5
