### ISSUE TITLE
Jenkins master pod name is misleading

### ISSUE THREAD

**Issue by pawelprazak** [jenkinsci/kubernetes-operator#30]
jenkins-operator-<cr-name> is a bit misleading name for a jenkins master, it looks like there is no master running

![image](https://user-images.githubusercontent.com/48874/59276799-4477e280-8c5f-11e9-859d-061d94e31d6d.png)

I propose dropping the infix `-operator-` and make it simply: `jenkins-<cr-name> `

**Comment by tomaszsek** [comment]
Changed in https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.1.0
