### ISSUE TITLE
Add raw webhook Integration to Jenkins Operator

### ISSUE THREAD

**Issue by salluvada** [jenkinsci/kubernetes-operator#302]
When Jenkins Operator runs into issues outside of its control in ensuring that the instance is running as per configuration, particularly in cases when its reconciliation loop breaks and it gives up, the operator should be able to create an incident in pager duty. When the issue is ultimately resolved, the operator should be able to resolve that incident in pager duty.

E.g. Jenkins is configured to use LDAP/AD integration and the operator credentials expired.

**Comment by tomaszsek** [comment]
Hi @salluvada,

Did you try the notifications feature https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/notifications/. I think it can cover your use case.

Cheers

**Comment by salluvada** [comment]
Yes I looked at the notifications feature. It is missing Pager Duty. While slack, teams notifications are good for pre-production scenarios of using jenkins operator in enterprise, for a production usage scenario, we do need integrations with incident management tools like Pager Duty, Opsgenie  etc.

**Comment by waveywaves** [comment]
@salluvada I think this is good for integrating with things such as slack actually and can abstract the configuration

**Comment by salluvada** [comment]
We should be good if we can give a raw web hook integration with json payload as it will be possible to integrate jenkins operator with a varitey of tools that can listen to them (Pager Duty included), and not just slack and teams.

**Comment by Sig00rd** [comment]
Closing this as there are currently no plans to work on features around notifications, though that might change in the future.
