### ISSUE TITLE
Add functionality to import jobs into jenkins using exported xmls

### ISSUE THREAD

**Issue by salluvada** [jenkinsci/kubernetes-operator#308]
While the right way to setup jobs is using Job DSL and load them up using seed jobs. It would be easier for teams who are trying to migrate to the operator model, if the operator can import the jobs in xml format at startup. This would help with a faster migration path into using the operator and eventually the teams can convert the jobs into Job DSL and load them through the seed job.

**Comment by tomaszsek** [comment]
As we discussed on the Jenkins Operator community call:
- it will introduce the bad practice because users should use the Jenkins Job DSL plugin
- is hard to debug invalid XML jobs
