### ISSUE TITLE
Azure storage backup provider

### ISSUE THREAD

**Issue by tomaszsek** [jenkinsci/kubernetes-operator#311]
Add backup provider which will make a backup on [Azure storage](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blobs-introduction)

- [instruction how to make a custom backup provider](https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/custom-backup-and-restore/)
- example PVC backup provider is located [here](https://github.com/jenkinsci/kubernetes-operator/tree/master/backup/pvc)
- [example how to use Azure CLI to upload file to Azure storage container](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-samples-blobs-cli)
- add `getLatestBacup.sh` scripts which will return the latest backup number located in Azure storage
- code with Dockerfile Makefile and e2e tests should be located [here](https://github.com/jenkinsci/kubernetes-operator/tree/master/backup/azure-storage)

**Comment by salluvada** [comment]
@tomaszsek  I will take this up. Please assign it to me.

**Comment by tomaszsek** [comment]
@salluvada Do you have access to Azure account?

**Comment by salluvada** [comment]
Yes. I do.

**Comment by tomaszsek** [comment]
Cool, here you go.

**Comment by andrijaperovic** [comment]
Any update on this? After using the v0.4.0 backup and restore instructions, I appear to only get the following log messages in the backup sidecar: 
`Trimming to only 3 recent backups in preparation for new backup`
The persistent volume is a managed volume of type AzureDisk.

The operator log has the following error messages: 
`' stderr 'tar (child): /backup/2.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
': command terminated with exit code 2	{"cr": "cxaiml-jenkins"}
2020-07-02T01:05:30.751Z	INFO	controller-jenkins	backuprestore/backuprestore.go:139	Restoring backup '2'	{"cr": "cxaiml-jenkins"}
2020-07-02T01:05:31.283Z	WARN	controller-jenkins	jenkins/jenkins_controller.go:152	Reconcile loop failed 10 times with the same error, giving up: pod exec error operation on stream: stdout 'Running restore backup
' stderr 'tar (child): /backup/2.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
': command terminated with exit code 2	{"cr": "cxaiml-jenkins"}`

Any help would be appreciated. Unless I need the custom backup provider implementation as you mentioned @tomaszsek
