### ISSUE TITLE
Use Kubernetes KIND instead of minikube in e2e tests

### ISSUE THREAD

**Issue by waveywaves** [jenkinsci/kubernetes-operator#315]
https://github.com/kubernetes-sigs/kind

This allows Kubernetes to run in Containers instead and is supported under Kubernetes SIG. It is more elegant than minikube configuration travisci and also gives a better idea of a Production level Kubernetes Cluster.

This is used in e2e for helm and is well tested https://github.com/helm/acceptance-testing. Would be a good enhancement in the e2e tests.

**Comment by tomaszsek** [comment]
Hi @waveywaves,

For it is nice to have. The only advantage is that kind support multi-node.

Cheers

**Comment by salluvada** [comment]
we will eventually get there when we are able to define in the CR, the node labels for operator/master pods and node labels for the pods that run builds to be able to specify that the builds should not run on the same nodes as operator/master.

**Comment by Sig00rd** [comment]
Thank you for your input. It doesn't seem very beneficial to migrate to kind for e2es now and there are no plans to work on this for the time being, but revisiting it in the future might be a good idea.
