### ISSUE TITLE
Configure PodTemplates with a custom CR.

### ISSUE THREAD

**Issue by mxandeco** [jenkinsci/kubernetes-operator#317]
PodTemplates are the core piece of the kubernetes plugin, it's very usual for companies to create a set of pre defined templates instead of defining them in the pipelines, it's possible to have them configured in the `caas` configmap, but as you add more templates the configuration is just huge and very hard to maintain.

Would be a life saver if we could configure each pod-template using a standalone `JenkinsPodTemplate` resource.

The operator would have to "listen" to these resources and somehow have them added to the kubernetes plugin.

We have tried to split our pod templates in multiple configmaps, that would work almost the same way, the problem with that is that one config will override the other and we only have the last template applied, we believe a custom resource would work the best for this, or does somebody have any suggestion on dealing with this?

**Comment by tomaszsek** [comment]
Hi @mxandeco,

This is how CasC plugin works with every new YAML file it overrides the previous one.
You can switch to groovy scripts where you have full control of how to apply the configuration.

Cheers

**Comment by mxandeco** [comment]
Hey @tomaszsek , yes we tried do use groovy scripts for some of the config, the pod templates are a bit complex to be configured that way we found, we thought some for of "native support" in the operator would be a good feature, i don't know.

Thanks for the work you guys have being doing there btw. =)

**Comment by akram** [comment]
Hi @mxandeco ,
did you have a look at the openshift-sync plugin ? it is built on top of the kubernetes plugin and provides automatic synchronisation of configmap annontated with role=jenkins-slave and add them as PodTemplate to kubernetes plugin without any restart.

this part should work with any kubernetes.

documentation is here:
https://docs.openshift.com/container-platform/3.6/using_images/other_images/jenkins.html#using-the-jenkins-kubernetes-plug-in-to-run-jobs

and the plugin is available in update center.

**Comment by Sig00rd** [comment]
Hello @mxandeco. Thank you for your input. What you described is doable with CaSC & GroovyScripts, though not always easy. There are currently no plans to add a standalone resource for Jenkins PodTemplates as described here as that seems redundant.
