### ISSUE TITLE
Scheme is missing in docs

### ISSUE THREAD

**Issue by anxolerd** [jenkinsci/kubernetes-operator#320]
After https://github.com/jenkinsci/kubernetes-operator/commit/7963de1f5d964e5ddc86e9d2b5fcfb3d2beb0e54 docs are lacking CR schemas.

![image](https://user-images.githubusercontent.com/6533582/78383867-d4698d00-75e1-11ea-9e70-cbea58e99909.png)

https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/schema/

I suppose, here is what happened: 

https://discourse.gohugo.io/t/raw-html-getting-omitted-in-0-60-0/22032

**Comment by tomaszsek** [comment]
Fixed :)

**Comment by anxolerd** [comment]
Thank you so much!
