### ISSUE TITLE
[Feature request] Allow to set priorityClassName for master pod

### ISSUE THREAD

**Issue by anxolerd** [jenkinsci/kubernetes-operator#321]
There is a possibility to assign a priorityClass to pod and by this make pod either

- not be preempted by others
- preempt other pods, when there are not enough resources for it

See [Pod Priority and Preemption documentation](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/) for more details.

It would be nice to have a possibility to set priorityClassName for JenkinsMaster, but I do not see one right now.

**Comment by anxolerd** [comment]
P.S. I can try implement the feature, but I cannot set up the project environment. Can you please help me to get started with it. Also, is the [Developer Guide](https://jenkinsci.github.io/kubernetes-operator/docs/developer-guide/) up to date? I encounter multiple different issues when following it (i.e. packages conflict on go-dependencies, different operator-sdk versions in go.mod and prerequisites, etc).

**Comment by tomaszsek** [comment]
Hi @anxolerd,

It will be great if you could contribute. Please join our slack https://github.com/jenkinsci/kubernetes-operator#community--contribution. We will help you to set up your environment.

Cheers

**Comment by tomaszsek** [comment]
Added in https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.4.0
