### ISSUE TITLE
[Helm] chart/templates/configuration.yaml not properly rendered when both CasC and Groovy content defined

### ISSUE THREAD

**Issue by snooyen** [jenkinsci/kubernetes-operator#327]
When both CasC and Groovy content are defined, chart/templates/configuration.yaml only applies the Groovy ConfigMap.

There either needs to be a `---` separator between the resource definitions or `configuration.yaml` needs to be separated into two files.

**Comment by tomaszsek** [comment]
Fixed in `0.1.1` Helm Chart version
