### ISSUE TITLE
Chart repo index.yaml has bad URL for chart version 0.1.0

### ISSUE THREAD

**Issue by Nuru** [jenkinsci/kubernetes-operator#329]
The current `chart/index.yaml` has a bad URL for `jenkins-operator-0.1.0.tgz`
https://github.com/jenkinsci/kubernetes-operator/blob/dc8bafd03a326596ca5df4232b0120de73ad3a4b/chart/index.yaml#L22

This breaks installs using chart version 0.1.0. Please fix. I believe it should be
```
  - https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/chart/jenkins-operator/jenkins-operator-0.1.0.tgz
```

**Comment by tomaszsek** [comment]
fixed :+1:
