### ISSUE TITLE
Documents how to develop with a remote k8s cluster

### ISSUE THREAD

**Issue by akram** [jenkinsci/kubernetes-operator#33]
Hi team,

I made some addons to documentation in order to be able to test and develop within a remote or locally configured cluster other than minikube.

Before submitting the PR, I wanted to get your opinion about it.

**Comment by tomaszsek** [comment]
Hi @akram,

Thanks but I saw only one PR with Makefile change. Maybe you forgot about something.

Regards

**Comment by akram** [comment]
Hi @tomaszsek 
Here it is: https://github.com/jenkinsci/kubernetes-operator/pull/34

I cherry picked some commits from my working branch.+

**Comment by tomaszsek** [comment]
I've improved little bit it in https://github.com/jenkinsci/kubernetes-operator/commit/0b03b85cf071f14a744184a2f49729685b5171a3.

**Comment by akram** [comment]
👍 Thanks !
