### ISSUE TITLE
Cannot access the Slack chat

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/kubernetes-operator#336]
Hello, I would like to join the projects Slack channel. I have tried to fill out the invite form several times since December (documented in https://github.com/jenkinsci/kubernetes-operator#community), but I have not received an invitation to the Slack channel.

**Comment by tomaszsek** [comment]
Hi @oleg-nenashev,

I've just checked and the form works for me. Did you get an email `Paweł Prażak has invited you to join a Slack workspace`?

Cheers

**Comment by oleg-nenashev** [comment]
Nope, email does not arrive. Will try my company email instead

**Comment by tomaszsek** [comment]
![image](https://user-images.githubusercontent.com/31410181/79751710-57ddea80-8313-11ea-945a-9c9090385980.png)

**Comment by oleg-nenashev** [comment]
> You asked us to send you a password reset link for virtuslab.slack.com. It turns out the email address...  doesn't have an account for that workspace yet

It looks like something is weird in the Slack database
