### ISSUE TITLE
[helm/templates/jenkins.yaml] {{ with.jenkins.notifications }} on wrong line.

### ISSUE THREAD

**Issue by snooyen** [jenkinsci/kubernetes-operator#344]
Line 51 should be moved to Line 57.  This is causing issues when overriding service and slaveservice settings via Helm chart values.

https://github.com/jenkinsci/kubernetes-operator/blob/e4b168dbe33f0d93be3a2b1389488ed8a6f3b96a/chart/jenkins-operator/templates/jenkins.yaml#L51

**Comment by tomaszsek** [comment]
Fixed in `0.1.3` Helm Chart
