### ISSUE TITLE
Few developer guide docs shortcomings

### ISSUE THREAD

**Issue by mkarebski** [jenkinsci/kubernetes-operator#348]
I noticed, that docs have few shortcomings. Of course, it is an individual problem, but I decided to put it here so we can talk about it. Here is the list I would prefer to have as a contributor: 
- in developers guide in the section `Build and run with a Minikube` as a developer I would like to see a result of run commands,
- in developers guide in the section as a developer I would appreciate section about debugging (`OPERATOR_EXTRA_ARGS`). I know that there is one in the diagnostics section, but for new contributor would be beneficial to have this info upfront,
- some kind of info in section Tips'n'Tricks in developers guide about `minikube stop` and `minikube delete` in case of errors, which are the result of errors within Minikube or obsolete virtual machines.
- self-learning site with links to maybe YouTube videos or courses about operators,
- switch information about secrets and installing plugins in `Customisation` in getting started. As new-comer I though that somehow Jenkins handles by itself plugins :).

**Comment by Sig00rd** [comment]
Closing this since almost all of the changes mentioned were already merged (and thanks for submitting PR for that!) and I've mentioned minikube stop & delete in #608.
Thanks for your contribution!
