### ISSUE TITLE
Seedjobs example of how to use with Github PR's ? 

### ISSUE THREAD

**Issue by ekarlso** [jenkinsci/kubernetes-operator#36]
Do we have an example of this?

**Comment by ekarlso** [comment]
What I mean is I want to achieve the effect of being able to build PR's and master branches off of triggers in github.

**Comment by tomaszsek** [comment]
Hi @ekarlso

**Recommended approach:** [tutorial(]https://webhookrelay.com/blog/2019/04/17/automated-github-pull-request-builds-on-jenkins/) Don't expose whole Jenkins to the internet and configure webhook proxy to trigger builds by GitHub.

Not recommended approach: Expose Jenkins to the internet through [Kubernetes LoadBalancer](https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/) or [Ingress controller](https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/). [tutorial](https://devopscube.com/jenkins-build-trigger-github-pull-request/)

Cheers

**Comment by pawelprazak** [comment]
You could also use 2 ingress controllers that support path based routing,
two Istio Ingress Gateways can also be used, one public to the webhook only
and one private for everything else.

**Comment by tomaszsek** [comment]
@ekarlso Did you get enough information? Can I close it?

**Comment by mxandeco** [comment]
Would be nice to have the option to configure the seed job to build periodically or to register the webhook automatically, from the CRD. maybe should open a new issue for this?

**Comment by tomaszsek** [comment]
@mxandeco Please create new issue.

**Comment by mxandeco** [comment]
> @mxandeco Please create new issue.

👍 have created a new issue related to exposing seed job config in spec.seedJobs. #69 

Thanks

**Comment by ekarlso** [comment]
Also, would it be better maybe to make this a seperate CRD maybe ? if you have 1 jenkins with multiple teams ?

**Comment by tomaszsek** [comment]
@ekarlso One Jenkins for many teams is not good idea. I recommend one Jenkins(CRD) per one team. We have plenty of teams and everyone have separate Jenkins.
