### ISSUE TITLE
kubernetes-operator does not have sufficient RBAC permissions

### ISSUE THREAD

**Issue by Nuru** [jenkinsci/kubernetes-operator#362]
# Expected Behavior
kubernetes-operator is given all needed RBAC permissions

# Actual Behavior
When updating Jenkins with new ServiceAccount annotations, the update fails with error:
```
serviceaccounts "jenkins-operator-jenkins" is forbidden: User "system:serviceaccount:jenkins:jenkins-operator" cannot update resource "serviceaccounts" in API group "" in the namespace "jenkins"
```

# Steps to Reproduce the Problem

1. Deploy Jenkins 2.222.3 with kubernetes-operator v0.4.0 using helm chart 0.2.0 onto Kuberentes 1.15.11
2. Change the annotations under
```yaml
spec: 
  serviceAccount:
          annotations:
```
in the Jenkins Resource
3. View the logs of the kubernetes-operator

**Comment by tomaszsek** [comment]
Fixed in `0.2.2` Helm chart
