### ISSUE TITLE
All-in-one YAML lacks Role permissions

### ISSUE THREAD

**Issue by tux-o-matic** [jenkinsci/kubernetes-operator#377]
# Expected Behavior
Deploying with the [All-in-one YAML](https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/deploy/all-in-one-v1alpha2.yaml) should have sufficient permissions similar to the separate [Role YAML](https://github.com/jenkinsci/kubernetes-operator/blob/master/deploy/role.yaml) 
# Actual Behavior
Permissions are not sufficient for a fully functional instance.

# Steps to Reproduce the Problem
Follow the install guide [from YAML section](https://jenkinsci.github.io/kubernetes-operator/docs/installation/)

**Comment by tomaszsek** [comment]
Fixed in 6edd2e5
