### ISSUE TITLE
Stop distributing configuration-as-code-support plugin

### ISSUE THREAD

**Issue by jetersen** [jenkinsci/kubernetes-operator#385]
Please stop distributing configuration-as-code-support plugin.
Since version 1.18 it has been a tomb stone plugin, it basically contains noting but a resource file, [read the release notes](https://github.com/jenkinsci/configuration-as-code-plugin/releases/tag/configuration-as-code-1.18).

Also 1.19 for JCasC seems like a terrible version to install as base. 😓

Please upgrade JCasC version to something higher than 1.19 there are many improvements made to JCasC and hopefully you want the kubernetes operator to provide the best starting experience.

**Comment by jetersen** [comment]
I see https://github.com/jenkinsci/kubernetes-operator/commit/ea059eab76966ac65ca163feba312401aa71ad51 partly fixed the issue.

But the website still refers to `configuration-as-code-support`
https://github.com/jenkinsci/kubernetes-operator/search?q=configuration-as-code-support&unscoped_q=configuration-as-code-support

**Comment by tomaszsek** [comment]
Fixed in 0d58add55f89d06c42f48f54dbb6c62abd5c95a8

**Comment by jetersen** [comment]
Much appreciated @tomaszsek
