### ISSUE TITLE
jenkins-operator cannot authenticate to Jenkins API when using Github OAuth plugin with MFA enabled

### ISSUE THREAD

**Issue by wendtek** [jenkinsci/kubernetes-operator#392]
# Expected Behavior
When I replace the `data.user` and `data.password` fields in the `jenkins-operator-<cr_name>` secret with a GitHub username and Personal Access Token (with `org:read` scope) and configure the GitHub OAuth plugin with the same user as an admin, jenkins-operator should be able to authenticate to the Jenkins API after the OAuth configuration is applied.

# Actual Behavior
After the secret is changed, jenkins-operator rebuilds the Jenkins master using the stored username and token to authenticate to Jenkins, then once it configures the GitHub Oauth plugin via a ConfigMap in `spec.configurationAsCode`, it can no longer authenticate and the reconcile loop begins to fail:

```
Reconcile loop failed: couldn't poll data from Jenkins API, invalid status code returned: 403
```

# Steps to Reproduce the Problem

1. Configure GitHub OAuth via ConfigMap and apply manifest.
2. Edit `jenkins-operator-credentials-<cr_name>` secret with GitHub user and token set as admin in step 1.
3. Wait for master to rebuild and watch the operator logs.

# Additional Info

- Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

- Jenkins Operator version:

```
v0.4.0
```

I do have MFA enabled on the user, however, GitHub Personal Access Tokens should circumvent the need for using MFA. I can still authenticate against the API using the same user and Personal Access Token myself with curl. An example being getting a json object back using:

```
curl -X GET "https://$JENKINS_URL/job/$JOB_NAME/api/json" --user "$GITHUB_USER:$GITHUB_TOKEN"
```

In the above, `GITHUB_USER` is set to the same as the credentials secrets `data.username` and `GITHUB_TOKEN` is set to the same as `data.password`. When I look at the secret again after the master rebuilds, I can see that the operator has added a `data.token` field that I suspect was generated by Jenkins prior to configuring the OAuth plugin. I suspect it is attempting to authenticate with that token rather than the set `data.user` and `data.password`.

**Comment by gizabutler** [comment]
Hi @wendtek. I have noticed similar behavior. When I edit the data.token field in the operator cedentials secret with my github personal access token it can reauthenticate to the Jenkins API... Unfortunately if the instance is restarted a new token gets generated. Is there a way to prevent this API token from being generated entirely?

**Comment by wendtek** [comment]
HI @gizabutler, I do not know of a way, which is why I brought the issue here. I imagine finding a way to stop the token from generating could be a workaround, but I found that every time I edited the secret containing the token, the operator would rebuild the master instance anyway, causing it to just generate a new token.

**Comment by scott-kausler** [comment]
I found a way to stop the token from generating. The trick is to set the tokenCreationTime in the future:
`kubectl create secret generic -n ${JENKINS_NAMESPACE} jenkins-operator-credentials-${RELEASE_NAME} 
  --from-literal=tokenCreationTime=2031-02-27T14:56:56.524250355Z 
  --from-literal=user=ACCESSTOKEN 
  --from-literal=token=${GITHUB_TOKEN} 
  --from-literal=password=${GITHUB_TOKEN} `

**Comment by Sig00rd** [comment]
I'm closing this since we don't have the capacity to work on this for some time as new API takes priority over this. Thanks for input everyone!
