### ISSUE TITLE
Any documentation around migrating to the new jenkins version 0.4.0

### ISSUE THREAD

**Issue by riqtest01** [jenkinsci/kubernetes-operator#399]
Currently we are running jenkins version 0.3. Would be interested in migrating to the new jenkins 0.4.0 
do you plan on providing any documentation 

Thanks
Venkat

**Comment by tomaszsek** [comment]
Hi @riqtest01,

We only provide a migration guide when it's needed. Migration from `0.3.0` to `0.4.0` is very easy just to update operator image tag.

Cheers
