### ISSUE TITLE
Issues updating plugins and jenkins-operator-user-configuration

### ISSUE THREAD

**Issue by s1apped** [jenkinsci/kubernetes-operator#40]
Hi,

When I try to update kubernetes or configuration-as-code plugins I get below. Looks like expect certain versions?
![plugins2](https://user-images.githubusercontent.com/32245059/60416402-09bdf600-9bde-11e9-830a-b73e530e2521.png)

I also noticed that version needs to be in quotes otherwise it causes some issues
![plugins1](https://user-images.githubusercontent.com/32245059/60416522-53a6dc00-9bde-11e9-8319-4e7ece9c8820.png)

Another issues I have with jenkins-operator-user-configuration. When I use default everything is fine but when I add another script or modify existing I get below

![adminAddress](https://user-images.githubusercontent.com/32245059/60416656-ac767480-9bde-11e9-9a08-caae976e1c7f.png)

Please advise.
Cheers

**Comment by tomaszsek** [comment]
Hi @s1apped,

> When I try to update kubernetes or configuration-as-code plugins I get below. Looks like expect certain versions?

Kubernetes and CasC plugin is located in `spec.master.basePlugins` please change versions there only.

> I also noticed that version needs to be in quotes otherwise it causes some issues

This is how yaml parsing works in go, I can do nothing with it. If version is `version: 2.0` go recognises `2.0` as a decimal value but the type is string. The only solution is to put double quotes `version: "2.0"`.

> Another issues I have with jenkins-operator-user-configuration. When I use default everything is fine but when I add another script or modify existing I get below

That's mean your CasC config is incorrect. Could you post it there?

Cheers

**Comment by s1apped** [comment]
Hi @tomaszsek,

> apiVersion: v1
> data:
>   1-configure-theme.groovy: |2
>     import jenkins.*
>     import jenkins.model.*
>     import hudson.*
>     import hudson.model.*
>     import org.jenkinsci.plugins.simpletheme.ThemeElement
>     import org.jenkinsci.plugins.simpletheme.CssTextThemeElement
>     import org.jenkinsci.plugins.simpletheme.CssUrlThemeElement
> 
>     Jenkins jenkins = Jenkins.getInstance()
> 
>     def decorator = Jenkins.instance.getDescriptorByType(org.codefirst.SimpleThemeDecorator.class)
> 
>     List<ThemeElement> configElements = new ArrayList<>();
>     configElements.add(new CssTextThemeElement("DEFAULT"));
>     configElements.add(new CssUrlThemeElement("https://cdn.rawgit.com/afonsof/jenkins-material-theme/gh-pages/dist/material-light-green.css"));
>     decorator.setElements(configElements);
>     decorator.save();
> 
>     jenkins.save()
>   1-configure-sonarqube.groovy: |2
>     import hudson.model.*
>     import jenkins.model.*
>     import hudson.tools.*
>     import hudson.security.*
>     import hudson.plugins.*
>     import jenkins.security.s2m.AdminWhitelistRule
>     import hudson.security.csrf.DefaultCrumbIssuer
>     import com.microsoft.jenkins.azuread.*
>     import org.jenkinsci.plugins.plaincredentials.impl.*
>     import hudson.util.Secret
>     import hudson.plugins.sonar.SonarGlobalConfiguration
>     import hudson.plugins.sonar.*
>     import hudson.plugins.sonar.model.TriggersConfig
>     import com.cloudbees.plugins.credentials.CredentialsScope
>     import com.cloudbees.plugins.credentials.domains.Domain
>     import com.cloudbees.plugins.credentials.SystemCredentialsProvider
> 
>     Jenkins jenkins = Jenkins.getInstance()
> 
>     def credentials = new StringCredentialsImpl(CredentialsScope.GLOBAL, "sonar", "sonar", Secret.fromString("4563tgfy54yregfdgfdg346534tregf"))
>     def credentialsStore = jenkins.getExtensionList(SystemCredentialsProvider.class)[0];
>     credentialsStore.store.addCredentials(Domain.global(), credentials);
> 
>     def serverName = "SonarQube"
>     def serverUrl = "https://test/sonarqube"
>     def mojoVersion = ""
>     def additionalProperties = ""
>     def additionalAnalysisProperties = ""
>     def triggers = new TriggersConfig()
> 
>     def sonarInstallation = new SonarInstallation(
>             serverName,
>             serverUrl,
>             credentials.getId(),
>             null,
>             mojoVersion,
>             additionalProperties,
>             additionalAnalysisProperties,
>             triggers
>     )
> 
>     def sonarGlobalConfiguration = jenkins.getDescriptorByType(SonarGlobalConfiguration.class)
>     def sonarInstallations = sonarGlobalConfiguration.getInstallations()
>     def isSonarInstalled = false
>     sonarInstallations.each {
>         installation = (SonarInstallation) it
>         if (sonarInstallation.getName() == installation.getName()) {
>             isSonarInstalled = true
>             println("Found existing installation: " + installation.getName())
>         }
>     }
>     if (!isSonarInstalled) {
>         sonarInstallations += sonarInstallation
>         sonarGlobalConfiguration.setInstallations((SonarInstallation[]) sonarInstallations)
>         sonarGlobalConfiguration.save()
>     }
> 
>     println("Configuring SonarQube Scanner...")
> 
>     def runnerVersion = "3.3.0.1492"
>     def instanceDescriptor = jenkins.getDescriptor("hudson.plugins.sonar.SonarRunnerInstallation")
>     def runnerInstaller = new SonarRunnerInstaller(runnerVersion)
>     def installSourceProperty = new InstallSourceProperty([runnerInstaller])
> 
>     def runnerInstallation = new SonarRunnerInstallation("Sonar", "", [installSourceProperty])
> 
>     def runnerInstallations = instanceDescriptor.getInstallations()
>     def isRunnerInstalled = false
>     runnerInstallations.each {
>         installation = (SonarRunnerInstallation) it
>         if (runnerInstallation.getName() == installation.getName()) {
>             isRunnerInstalled = true
>             println("Found existing installation: " + installation.getName())
>         }
>     }
>     if (!isRunnerInstalled) {
>         runnerInstallations += runnerInstallation
>         instanceDescriptor.setInstallations((SonarRunnerInstallation[]) runnerInstallations)
>         instanceDescriptor.save()
>     }
>     jenkins.save()
>   1-system-message.yaml: |2
>     jenkins:
>       systemMessage: "Configuration as Code integration works!!!"
>       adminAddress: "${SECRET_JENKINS_ADMIN_ADDRESS}"
> kind: ConfigMap
> metadata:
>   name: jenkins-operator-user-configuration-test
>   namespace: jenkins

When I login to jenkins sonar is setup but 
![image](https://user-images.githubusercontent.com/32245059/60434887-79e17180-9c08-11e9-9ea6-949509ae8b16.png)

**Comment by tomaszsek** [comment]
https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/demos/kubernetes-secrets/README.md I think Jenkins API has changed:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-casc
data:
  jenkins.yaml: |
    jenkins:
      location:
        url: http://jenkins/
        adminAddress: "${SECRET_JENKINS_ADMIN_ADDRESS}"
```

**Comment by s1apped** [comment]
@tomaszsek 

Looks like below made a trick:

```
  1-system-message.yaml: |2
    jenkins:
      systemMessage: "Configuration as Code integration works!!!"
    unclassified:
      location:
        adminAddress: "${SECRET_JENKINS_ADMIN_ADDRESS}"
```
but when I try to add basePlugins

```
spec:
  master:
   basePlugins:
   - name: configuration-as-code
     version: "1.21"
   - name: kubernetes
     version: "1.16.2"
   plugins:
   - name: simple-theme-plugin
```
`Warning  CRValidationFailure       4m39s (x2 over 4m39s)  jenkins-operator  Base CR validation failed
`

**Comment by tomaszsek** [comment]
The operator installs these base plugins https://github.com/jenkinsci/kubernetes-operator/blob/master/pkg/controller/jenkins/plugins/base_plugins.go. You have to specify all o them in `spec.master.basePlugins`.

**Comment by s1apped** [comment]
@tomaszsek 

Thanks! Everything works.

Cheers
