### ISSUE TITLE
Vertical Pod Autoscaler

### ISSUE THREAD

**Issue by snooyen** [jenkinsci/kubernetes-operator#402]
Is it possible to use VPA with the jenkins.jenkins.io resource?

Out of the box, VPA is presenting the following error:
```
Cannot read targetRef. Reason: Unhandled targetRef jenkins.io/v1alpha2 / Jenkins / jenkins, last error the server could not find the requested resource (get jenkins jenkins)
```

**Comment by akram** [comment]
Hi @snooyen ,
with the current version of the Operator, we are intesively monitoring the Pod and reconcilling many of its values which may prevent VPA to work.

Can you check with the last version on master branch by enabling the Deployment based of Jenkins if VPA is working better?

**Comment by snooyen** [comment]
Thanks @akram, I wasn't aware that you're migrating to using a Deployment controller for the Jenkins instances.  Can you provide more info on how to enable this?

**Comment by akram** [comment]
@snooyen yes sure, you need to annotate your Jenkins CR with the following annotation to make the operator use `deployment` instead of pods.

```
jenkins.io/use-deployment: "true"
```

This feature is still in current development and we know that some mechanisms are still not handled properly, so your feedback on VPA would be interesting also.

**Comment by snooyen** [comment]
@akram Just got back around to looking at this. I'm guessing this feature is not apart of the 0.4.0 release?

**Comment by tomaszsek** [comment]
Hi @snooyen,

VPA is not supported and it's not in our roadmap. With the Jenkins, architecture is very hard to add support for the VPA.

Cheers
