### ISSUE TITLE
Using active-directory requires user 'jenkins-operator'

### ISSUE THREAD

**Issue by shadamik** [jenkinsci/kubernetes-operator#407]
# Expected Behavior
I can configure the username used for operator jenkins api calls.

# Actual Behavior
The user used for accessing the jenkins api is hard coded.

# Steps to Reproduce the Problem

1. install active-directory plugin
2. activate activeDirectory security realm
3. operator can not access jenkins api anymore

# Additional Info

  ```
 WARNING j.s.BasicHeaderApiTokenAuthenticator#authenticate: API token matched for user jenkins-operator but the impersonation failed
org.acegisecurity.userdetails.UsernameNotFoundException: Authentication was successful but cannot locate the user information for jenkins-operator 
```

**Comment by apogrebnyak** [comment]
No, you can use any user defined in your AD.

Just make sure you create a kuberentes secret `jenkins-operator-credentials-<CR-NAME>`.
In it specify `user` as your AD user and `password` as its password.

Beware, that jenkins-operator uses this secret to store other important information.  There is a ticket to split that extra info https://github.com/jenkinsci/kubernetes-operator/issues/313

**Comment by shadamik** [comment]
Thanks, found it in the code. Sorry I overlooked that.
