### ISSUE TITLE
Master pod restarts generates new slave api token 

### ISSUE THREAD

**Issue by samirmajen** [jenkinsci/kubernetes-operator#410]
# Expected Behavior

Permanent slaves should be able to reconnect to the jenkins master after the master pod restarts

# Actual Behavior

Master pod restarts and generates a new slave api token which causes the slave to fail to connect as its token differs

# Steps to Reproduce the Problem

1. Create a slave and connect to Jenkins
2. Restart the jenkins master pod
3. Slave will not reconnect

# Additional Info

- Kubernetes version:

  1.15

  ```
  (paste your output here)
  ```

- Jenkins Operator version:

```
  0.4.0
  ```

**Comment by SylwiaBrant** [comment]
Unfortunatelly that's the nature of Jenkins. I'm closing it. If you have the need, you can reopen it.
