### ISSUE TITLE
Metrics service deployed with wrong selector

### ISSUE THREAD

**Issue by Nuru** [jenkinsci/kubernetes-operator#411]
# Expected Behavior

The operator deploys a Service that exposes a metrics endpoint that Prometheus can scrape.

# Actual Behavior

The operator deploys a jenkins-operator-metrics Service that exposes ports named http-metrics and cr-metrics, but uses a Selector that does not match the operator pod, so no Endpoints are discovered/exposed.

# Steps to Reproduce the Problem

1. Deploy the operator version 0.4.0 into the `jenkins` namespace using jenkinsci/kubernetes-operator Helm chart version 0.2.0
2. Observe there are no jenkins-operator-metrics endpoints
```
$ kubectl -n jenkins get endpoints jenkins-operator-metrics
NAME                       ENDPOINTS   AGE
jenkins-operator-metrics   <none>      3m
```

# Additional Info

- Kubernetes version:

```text
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:08:59Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Jenkins Operator version: v0.4.0

**Comment by SylwiaBrant** [comment]
We'll be migrating into new Operator SDK and we'll fix it then.

**Comment by Sig00rd** [comment]
Closing as currently the Operator doesn't deploy the metrics Service with Helm chart installation
