### ISSUE TITLE
Make operator-username and password configurable in Jenkins CR

### ISSUE THREAD

**Issue by skashyap7** [jenkinsci/kubernetes-operator#412]
# Expected Behavior
Request for enhancement: Jenkins CR should allow operator username and password as configuration

# Actual Behavior
Currently, the firm policy does not allow creating LDAP uses with name jenkins-operator. A workaround suggested in #133 works only for the first time startup. If the pod crashes and restarts, operator credential secrets are re-created and any further re-configuration by CaSC fails.

# Steps to Reproduce the Problem

1. Create a secret for operator credential as suggested in #133 
2. Create a Jenkins CR
3. Kill the pod
4. Pod restarts
5. The operator is unable to poll Jenkins "Reconcile loop failed: couldn't poll data from Jenkins API, invalid status code returned: 500"

Happy to contribute if it is a small change!

# Additional Info

- Kubernetes version: 
 
 ```
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
  

- Jenkins Operator version:

```
  0.0.4
  ```

**Comment by pniederlag** [comment]
https://github.com/jenkinsci/kubernetes-operator/blob/43dffbd5d36a6f0f020ebefb0e23e8e610b4e55c/pkg/configuration/base/resources/operator_credentials_secret.go seems relevant?

**Comment by apogrebnyak** [comment]
Is it a dup of https://github.com/jenkinsci/kubernetes-operator/issues/407?

**Comment by tomaszsek** [comment]
Hi @skashyap7,

What exactly did you save in the secret?

Cheers

**Comment by wendtek** [comment]
This would also provide a workaround for https://github.com/jenkinsci/kubernetes-operator/issues/392

**Comment by skashyap7** [comment]
> Hi @skashyap7,
> 
> What exactly did you save in the secret?
> 
> Cheers

I set the operator username and password in the secret. The issue is I configure LDAP plugin as part of my CaSC setting. Once this configuration is made, the operator is unable to query Jenkins post a restart.

**Comment by pniederlag** [comment]
The username and password are currently not configurable per configuration or the CRD. However after quite a little bit of troubles it seems we now managed to get our jenkins up and running with a remote authentication source(Crowd2/atlassian). Here is what we did:

- make sure the setup of remote-auth-adapter is correct
- make sure the setup of remote-auth-adapter is part of the CaCS setup
- edit the kubernetes secret 'jenkins-operator-credentials-<yourcr>' to contain a proper username/password that can authenticate on the remote-auth-adapter
- make sure the chosen user has admin rights

**Comment by brokenpip3** [comment]
Hi there! any plan to support this? we have the same problem with the saml plugin, thanks!
