### ISSUE TITLE
Deploy Jenkins

### ISSUE THREAD

**Issue by samarthsaxena** [jenkinsci/kubernetes-operator#414]
# Expected Behavior
Example for cr_name string. What is meant by it?
# Actual Behavior
Command with placeholders as cr_name
kubectl get secret jenkins-operator-credentials-<cr_name> -o 'jsonpath={.data.user}' | base64 -d
kubectl get secret jenkins-operator-credentials-<cr_name> -o 'jsonpath={.data.password}' | base64 -d
# Steps to Reproduce the Problem

1.In the Jenkins deployment section
2.commands have a placeholder cr_name 
3. no example for what exactly is meant by it.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

  ```
  (paste your output here)
  ```

- Jenkins Operator version:

```
  (paste your output here)
  ```

**Comment by waveywaves** [comment]
The cr_name, means Custom Resource Name i.e. the value that you set for "name" under metadata in your yaml where you defne your Jenkins Resource.

**Comment by tomaszsek** [comment]
Hi @samarthsaxena,

`cr_name` is just a Jenkins instance name.

Cheers
