### ISSUE TITLE
Getting WARN when installing new plugin

### ISSUE THREAD

**Issue by placydo** [jenkinsci/kubernetes-operator#42]
After I've added new plugin and checked logs from operator I did get warn message:
WARN: Incompatible plugin '{pipeline-utility-steps 2.3.0}' version, actual ''	{"cr": "infrastructure"}

Issue is that plugin was compatible and installed successfully thus above message is not accurate.

**Comment by jakalkhalili** [comment]
We fixed this bug in version 0.1.0

**Comment by placydo** [comment]
Wow thanks! Closing issue
