### ISSUE TITLE
Helm install doesn't use prepared PVC

### ISSUE THREAD

**Issue by peske** [jenkinsci/kubernetes-operator#422]
# Expected Behavior

`helm install` should use existing PVC for backup container, if configured in this way.

# Actual Behavior

`helm install` tries to create `jenkins-backup` PVC, no matter it's configured to use the existing PVC.

# Steps to Reproduce the Problem

1. Ensure that you have `jenkins` namespace, and an existing PVC in it. Something like:
```
# kubectl get pvc --namespace jenkins
NAME             STATUS    VOLUME       CAPACITY   ACCESS MODES   STORAGECLASS    AGE
jenkins-pvc      Bound     jenkins-pv   8Gi        RWO            local-storage   11m
```
2. Ensure that your values file (i.e. `jenkins-operator-values.yaml`) instructs `helm` to use the existing PVC, by having there something like:
```
  volumes:
    - name: backup # PVC volume where backups will be stored
      persistentVolumeClaim:
        claimName: jenkins-pvc
```
Note that `claimName` is `jenkins-pvc`, which is the name of the existing PVC.

3. Ensure that the newly created Jenkins instance targets the same namespace where the existing PVC resides, by having the following in the values file:
```
  namespace: jenkins
```

4. Install the operator by using `helm`, by executing something like:
```
helm upgrade -i jenkins-operator-release jenkins/jenkins-operator --values jenkins-operator-values.yaml --namespace jenkins
```

5. List all the PVCs from `jenkins` namespace by executing:
```
# kubectl get pvc --namespace jenkins
NAME             STATUS    VOLUME       CAPACITY   ACCESS MODES   STORAGECLASS    AGE
jenkins-backup   Pending                                                          9m29s
jenkins-pvc      Bound     jenkins-pv   8Gi        RWO            local-storage   11m
```
As you can see, `helm install` attempted to create a new PVC (`jenkins-backup`) although we've specified that the existing one should be used (`jenkins-pvc`).

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Jenkins Operator version:

```
NAME                    	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART                 	APP VERSION
jenkins-operator-release	jenkins  	1       	2020-06-18 02:20:52.630516391 +0000 UTC	deployed	jenkins-operator-0.3.2	0.4.0 
```

 - Helm version:

```
version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

**Comment by peske** [comment]
Update: if I don't create the PVC in advance, `helm install` will create it and bind it to an exisitng PV, so I get:
```
# kubectl get pvc --namespace jenkins
NAME             STATUS   VOLUME       CAPACITY   ACCESS MODES   STORAGECLASS    AGE
jenkins-backup   Bound    jenkins-pv   8Gi        RWO            local-storage   5m10s
```

But there are again some questions:
1. Why the PVC is named `jenkins-backup` although I've specified `jenkins-pvc` in the values file? Not a too big deal, but still annoying.
2. Why `helm install` creates the PVC successfully, yet it doesn't create Jenkins instance at all?

No Jenkins instance created anyway, so it doesn't solve the original issue: https://github.com/jenkinsci/kubernetes-operator/issues/418

**Comment by tomaszsek** [comment]
Hi @peske,

1. The PVC name is hardcoded https://github.com/jenkinsci/kubernetes-operator/blob/master/chart/jenkins-operator/templates/backup.yaml#L5 but should contain Jenkins name as well (@jakalkhalili please fix that).
2. Please follow the instructions https://github.com/jenkinsci/kubernetes-operator/issues/418#issuecomment-646647310 and continue the discussion in #418.

Cheers

**Comment by SylwiaBrant** [comment]
Is it still an issue?
