### ISSUE TITLE
Default Route on OpenShift should be functional

### ISSUE THREAD

**Issue by mnuttall** [jenkinsci/kubernetes-operator#429]
# Expected Behavior

A Jenkins instance on OpenShift should be accessible when created using the default settings. The associated documentation should be correct, and reflect the behaviour of the operator. 

# Actual Behavior

The instructions at https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/openshift/ have several Route-related problems. The section 'OpenShift OAuth integration' states, 

> The creation of a Route is required for the integraiton [sic] of Jenkins with OpenShift oauth authentication.

As of version 0.4.1-rc1, a Route is created automatically when a `jenkins` instance is created. The documentation should reflect this. The document also states, 

> Note: the route name (jenkins-route) must match the pointed route on the serviceaccount annotation.

This is correct: but the default route that is created will be called `jenkins-[namespace]` e.g., `jenkins-default` if created in the namespace `default`. The sample `Jenkins` yaml in the OpenShift docs includes the stanza, 

```yaml
serviceAccount:
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.jenkins: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"jenkins-route"}}'
```

This will only work by default if created in the namespace `route`, which is unlikely and unintended. 

The automatic creation of a Route is good, but requiring the end user to correctly annotate the right service account, through the `Jenkins` CR, while having to correctly predict the name of the Route that will be automatically created, is not a good experience. As an end user, all I want is that a Route be created automatically, and a service account created and correctly annotated. 

Again, as an end user I want to be able to copy/paste the sample yaml from https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/openshift/ , `kubectl apply` it and have it work. As it stands, I have to edit `spec.serviceAccount.annotations` to reflect the namespace into which I'm creating the instance. This makes for more complex instructions, and complicates the task of automating Jenkins instance creation. 

# Steps to Reproduce the Problem

1. Install the Jenkins operator
2. Create an instance as per the yaml at https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/openshift/
3. Notice that a route has been created automatically, but the wrong value annotated on to the associated service account. 

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
k version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:08:14Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2", GitCommit:"4320e48", GitTreeState:"clean", BuildDate:"2020-01-21T19:50:59Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

- Jenkins Operator version:

```
0.4.1-rc1
  ```

Many thanks to @akram for being so helpful on Slack. His pointer to https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/openshift/ was vital - but that page should have been easier to find from the Operator landing page in the OpenShift admin console.

**Comment by mnuttall** [comment]
The name of the route comes from [pkg/configuration/base/route.go](https://github.com/jenkinsci/kubernetes-operator/blob/43dffbd5d36a6f0f020ebefb0e23e8e610b4e55c/pkg/configuration/base/route.go#L18):

```go
func (r *ReconcileJenkinsBaseConfiguration) createRoute(meta metav1.ObjectMeta, serviceName string, config *v1alpha2.Jenkins) error {
	route := routev1.Route{}
	name := fmt.Sprintf("%s-%s", config.ObjectMeta.Name, config.ObjectMeta.Namespace)
```

No external configuration is available to effect the name chosen for the route. Is this naming convention is to be treated as an API, it should be documented. This would allows end users such as ourselves to write automation that depends on this naming convention. Otherwise, a means to override the generated Route name should be provided.

**Comment by Sig00rd** [comment]
Closing this as the current Operator release is not compatible with OpenShift. Thank you very much for your input.
