### ISSUE TITLE
jenkins --prefix= question

### ISSUE THREAD

**Issue by s1apped** [jenkinsci/kubernetes-operator#43]
Hi,

Is it possible to use --prefix= with operator? Usually below needs to be added in Deployment configuration.

```
     env:
     - name: JENKINS_OPTS
       value: --prefix=/jenkins
```
Instance is up and running with with prefix i.e http://localhost:8080/jenkins/login but Operator fails to configure it.
![image](https://user-images.githubusercontent.com/32245059/60671922-7eaa5d80-9e74-11e9-9c0b-613e05565cd5.png)

Thanks.

**Comment by tomaszsek** [comment]
Hi @s1apped,

We can add support for it.

Cheers

**Comment by SkySonR** [comment]
Hi @tomaszsek 
+1
will be useful

**Comment by tomaszsek** [comment]
Added in https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.2.0
