### ISSUE TITLE
Only the Jenkins Operator Pod comes up in OpenShift

### ISSUE THREAD

**Issue by TheAppService** [jenkinsci/kubernetes-operator#433]
# Expected Behavior
After creating an instance of Jenkins via the Jenkins operator I would assume a working deployment is coming up.
# Actual Behavior
Only the Jenkins operator pod comes up and outputs this message endlessly:
```
1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v1.Route: routes.route.openshift.io is forbidden: User "system:serviceaccount:jenkins2:jenkins-operator" cannot list resource "routes" in API group "route.openshift.io" in the namespace "jenkins2"
```

# Additional Info

- OpenShift Version: 4.3

- Jenkins Operator version:

```
Jenkins Operator
0.4.1-rc1
  ```

I guess even if this is only a small permission problem (I did not succeed to solve either), others would be grateful for a fix for this ;)

**Comment by jkhelil** [comment]
Hi @TheAppService,
this should fix it https://github.com/operator-framework/community-operators/pull/1945
it needs to be merged before you have it in operator hub

**Comment by TheAppService** [comment]
Ah great, thank you for the information!

**Comment by TheAppService** [comment]
Good morning from Germany,

thanks for your efforts to fix this, unfortunateley after trying out the new version, an error from the same "structure" appears when the operator pod tries to install .... I have not yet tested it with an available PV, but I guess regarding the error this would not make much difference, would it?
`pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *unstructured.Unstructured: persistentvolumes is forbidden: User "system:serviceaccount:test:jenkins-operator" cannot list resource "persistentvolumes" in API group "" at the cluster scope`

Best regards

Daniel

**Comment by Sig00rd** [comment]
Closing this as the current Operator release is not compatible with OpenShift.
