### ISSUE TITLE
Jenkins operator sets the target port for jenkins-operator-http-<cr> service to 80 instead of 8080

### ISSUE THREAD

**Issue by sarabesh** [jenkinsci/kubernetes-operator#439]
# Expected Behavior
the jenkins-operator-http-cr service should always default TargetPort to 8080.
# Actual Behavior
the jenkins-operator-http-cr service sets TargetPort to port we specify in Jenkins.spec.service.port, which should only be set for jenkins-operator-http-cr service.spec.Port and not jenkins-operator-http-cr service.spec.TargetPort
# Steps to Reproduce the Problem

1. used the following spec in jenkins crd
service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    type: LoadBalancer
    port: 90

2. describing the created svc

Name:                     jenkins-operator-http-pod
Namespace:                jenkins-operator
Labels:                   app=jenkins-operator
                          jenkins-cr=pod
Annotations:              service.beta.kubernetes.io/aws-load-balancer-internal: true
Selector:                 app=jenkins-operator,jenkins-cr=pod
Type:                     LoadBalancer
IP:                       xxxx.xxxx.xxxx.xxxx
LoadBalancer Ingress:     xxxx.xxxx.xxxx.com
Port:                     <unset>  90/TCP
TargetPort:               90/TCP
NodePort:                 <unset>  31147/TCP
Endpoints:                <none>
Session Affinity:         None

**Comment by r00t4ccess** [comment]
I have this exact same issue running in AWS, I need to edit my loadBalancer service after deploying jenkins to have it point to port 8080 for targetPort. I looked through the CRD and it appears that it only supports the port parameter and not targetPort.

**Comment by SylwiaBrant** [comment]
Hello, we're planning a new release soon which will fix this.

**Comment by tomaszsek** [comment]
Fixed in https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.5.0
