### ISSUE TITLE
Need better documentation

### ISSUE THREAD

**Issue by romil-punetha** [jenkinsci/kubernetes-operator#44]
Im trying to install google-login plugin. However, i don't understand where the settings should be provided after installing the plugin. When jenkins restarts, the plugin is there, but the settings are gone.

**Comment by tomaszsek** [comment]
Hi @romil-punetha,

You have to configure your plugin by groovy script or Configuration as Code plugin, https://github.com/jenkinsci/kubernetes-operator/blob/master/docs/getting-started.md#jenkins-customisation. Every single manually change will be wipe out after Jenkins restart.

Cheers

**Comment by romil-punetha** [comment]
@tomaszsek Can you give an example how i can add pod templates so that I may use them in the pipeline? I dont want to define an entire template again and again in the Jenkinsfile. Rather, defile it in k8s plugin pod template and use it as `agent my-app-template`.

**Comment by romil-punetha** [comment]
Also, is there a better way to perform user configurations? eg. I can see the user config map, where if i add *.groovy as an entry, it works. However, I would like to have separate configmaps that contain the groovy scripts as its better managed then.

**Comment by pawelprazak** [comment]
you mean like this?
https://github.com/jenkinsci/kubernetes-plugin/blob/master/README.md
or this?
https://github.com/jenkinsci/kubernetes-plugin/blob/master/README.md


sob., 6 lip 2019, 08:11 użytkownik Romil Punetha <notifications@github.com>
napisał:

**Comment by tomaszsek** [comment]
@romil-punetha Configurations will be improved in v0.2.0 version https://github.com/jenkinsci/kubernetes-operator/issues/28#issuecomment-500359852.

**Comment by tomaszsek** [comment]
Improved in https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.2.0
