### ISSUE TITLE
SeedJobs - Support gitHubApp credential type

### ISSUE THREAD

**Issue by snooyen** [jenkinsci/kubernetes-operator#446]
# Expected Behavior
Authentication for seedJobs should support `credentialType: gitHubApp`.

This is required for authentication to repositories at an organizational level via GitHubApps/ GitHub Branch Source plugin as outlined in https://github.com/jenkinsci/github-branch-source-plugin/blob/master/docs/github-app.adoc

# Actual Behavior
```
2020-08-12T20:54:34.253Z	WARN	controller-jenkins	jenkins/jenkins_controller.go:308	Validation of user configuration failed, please correct Jenkins CR	{"cr": "jenkins"}
2020-08-12T20:54:34.253Z	WARN	controller-jenkins	jenkins/jenkins_controller.go:310	seedJob `my-seed-job` unknown credential type	{"cr": "jenkins"}
```
# Steps to Reproduce the Problem

Deploy Jenkins CR with
```
seedJobs: |
    - id: my-seed-job
      credentialType: gitHubApp
      credentialID: my-github-app-credential
      targets: "cicd/jobs/my-seed-job.jenkins"
      description: "Organization Folder for MyOrg Repositories"
      repositoryBranch: ':^(origin/master\$|origin/dev\$).*'
      repositoryUrl: git@github.com:MyOrg/my-repo.git
      githubPushTrigger: true
```

# Additional Info

- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-07-04T15:01:15Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-fd1ea7", GitCommit:"fd1ea7c64d0e3ccbf04b124431c659f65330562a", GitTreeState:"clean", BuildDate:"2020-05-28T19:06:00Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Jenkins Operator version: `0.4.0`

 
- Relevant Code:

https://github.com/jenkinsci/kubernetes-operator/blob/6f65d1c89249b36666b438a8a760197be80d1857/pkg/apis/jenkins/v1alpha2/jenkins_types.go#L533

https://github.com/jenkinsci/kubernetes-operator/blob/43dffbd5d36a6f0f020ebefb0e23e8e610b4e55c/pkg/configuration/user/seedjobs/validate.go#L43

**Comment by sknight80** [comment]
Hi, Do we have any ETA on this ticket?

**Comment by SylwiaBrant** [comment]
Hello @snooyen, @sknight80, I am sorry to say that this is not in our roadmap, as we have many more pressing issues. Maybe in the further future.

**Comment by sknight80** [comment]
@SylwiaBrant thanks for the update!
