### ISSUE TITLE
Add ability to pass imagePullSecrets parameter

### ISSUE THREAD

**Issue by SkySonR** [jenkinsci/kubernetes-operator#45]
Hi! 
I would like to use my own image from private registry with preinstalled plugins and tools. 
Looks like it's not possible or undocumented. Please fix and provide ability to pull images from private registries using imagePullSecrets statement. Thanks.

**Comment by tomaszsek** [comment]
Added in https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.2.0
