### ISSUE TITLE
Shared volume for jenkins_home

### ISSUE THREAD

**Issue by gregdurham** [jenkinsci/kubernetes-operator#450]
Hello, 
Looking at the source code and doing some testing, I see that it appears that we cannot mount the JENKINS_HOME dir on a shared EFS volume so that the data can persist a restart. Is this intentional? If not, would you be open to a feature request to remove the default emptydir and allow this to be overridden via the CRD? 

Thanks!

**Comment by robertsandoval** [comment]
I have the same question. How can we have JENKINS_HOME mounted to a volume other than one that is emptyDir()

**Comment by SylwiaBrant** [comment]
Hello @gregdurham, this behaviour is intended. Jenkins should be immutable and only operator can ensure it, so JENKINS_HOME has to remain unchanged. You have to use operator's built-in backup and restore mechanism.

**Comment by jam01** [comment]
@SylwiaBrant is it possible to re-consider this?

I agree Jenkins configurations should be as immutable as possible. However, job history is still very important to maintain and backup/restore cannot address that sufficiently. For example, in continuous delivery scenario we could have tens if not hundreds of jobs run in a single day, so even if the backups were made daily we run the risk of losing that information to a simple container restart in the middle of the day. Some client setups even use the job build numbers as part of their artifact versioning scheme, so losing that history may result in considerable headaches.

I understand the operator simply can't just guarantee that nothing will ever go wrong. But allowing jenkins-home to use a PVC seems like a worthwhile attempt to bridge the gap between backup/restores. At the same time it allows other backup/restore mechanisms like volume snapshots from the cloud provider, etc.

Let us know if that may be acceptable, we'd be happy to submit a PR for this :) Or let us know if there are alternatives we may not have considered. 

PS thanks for sharing your work.

**Comment by Sig00rd** [comment]
Thank you for your input. Jenkins' immutability is, however, an important part of current, GitOps oriented architectural design of the Operator, and there are currently no plans to change that.
