### ISSUE TITLE
Support unique k8s secrets for different CASCs

### ISSUE THREAD

**Issue by joeljeske** [jenkinsci/kubernetes-operator#459]
It would be nice to be able to specify a unique secret for each CASC yaml item. Currently, you can specify exactly 1 secret ref that is used for all of the CASC yaml or exactly 1 secret to be used for all of the CASC groovy. It would be helpful to be able to specify a secret ref for each config item. 

Use cases: 

- When deploying the jenkins operator via gitops-style where secrets are encrypted and versioned in scm, it is helpful to be be able to encrypt and add *new* secrets for *new* config items. Currently, I have to manually decrypt my secrets and add a new secret item entry. I would like to be able to allow anyone to add new arbitrary secrets and reference them in new configuration items. This is particularly useful when keeping all jenkins credentials version in git and new credentials may be added frequently.  (my primary use case)
- It helps distinguish which secrets are used for which configuration

**Comment by SylwiaBrant** [comment]
Hello @joeljeske, thanks for your idea. It's definitely doable with Groovy scripts, we'll check how about CaSC yamls. We'll work on it.

**Comment by leifmadsen** [comment]
I think I'm running in to this as well. If you specify a secret for a CasC configuration then it wipes out the generated secret for Kubernetes integration.

**Comment by Sig00rd** [comment]
In the new API the secret is configurable for CaSC and unique per CaSC but there is still only 1 CaSC per Jenkins allowed as it poses multiple technical challenges to support more. Having multiple CaSC could have unforeseeable consequences because the order in which they get applied is non-deterministic.
