### ISSUE TITLE
Supported?

### ISSUE THREAD

**Issue by opsroller** [jenkinsci/kubernetes-operator#460]
Is this stinky tool being supported anymore? Because by the look of the Issues board it's not, and there are more than enough bugs in here to need the Orkin Man.

So, is there a future for this Operator, or is it going the way of the Dino?

**Comment by snooyen** [comment]
It's quite unfortunate that support from the maintainers has dropped off since April.

**Comment by oleg-nenashev** [comment]
@opsroller @snooyen Please see the Jenkins Kubernetes operator open governance proposal here: https://groups.google.com/g/jenkinsci-dev/c/OA5nb_SAgh0/m/APy-RTypAAAJ . In the Jenkins community we are interested in recovering the project and restarting active development and maintenance in the project. Multiple contributors are involved in this effort, including @waveywaves @akram @slide and me. You are welcome to join the effort.

Meanwhile, please be kind @opsroller. Some comments also stink and do not help to resolve the situation.

**Comment by waveywaves** [comment]
@opsroller @snooyen I understand your frustration. An update to the governance of this operator is still underway.

Please checkout the fork at https://github.com/redhat-developer/jenkins-operator where @akram @jkhelil and I are actively developing on the operator. 

@oleg-nenashev thanks for checking this out.

**Comment by snooyen** [comment]
@oleg-nenashev @waveywaves 

Glad to hear there is discussion going on in the background!  The project itself is a great one with lots of potential.  I'm sure there can be good community contribution with better maintenance of the issues board.

**Comment by surj-bains** [comment]
@oleg-nenashev  @waveywaves  @akram  @slide  I share the same frustrations as @opsroller , I appreciate that people's lives can take them away from channeling effort into something that is perceived as being free, however I think just some communication and responses to outstanding issues ( I have a few ) and PR's would help people either volunteer to help or determine which Jenkins implementation in kubernetes to choose.

**Comment by oleg-nenashev** [comment]
FTR https://groups.google.com/g/jenkinsci-dev/c/oAWCXDbgcG4 - Hosting request for a new Kubernetes Operator from Red Hat

**Comment by antoniaklja** [comment]
Hi everyone, thank you @oleg-nenashev for giving an explanation. I really appreciate you actively support the community 👍 

Let me elaborate a little bit more on the current situation and the future. As a [VirtusLab](http://virtuslab.com/), we were super busy for some time, and most of the work was on @tomaszsek shoulders anyway, which is barely possible for one person to maintain such a complex project and focus on a day to day responsibilities at VirtusLab.

So, now, we hired one full-time person to contribute and actively take part in community engagement. Apart from that, we have one more position to fulfil in this area. 

Together with @oleg-nenashev and Jenkins board, we want to establish an open governance model for this project and make sure everything is actively maintained and heading in the right direction. 

In the next couple of days, I'm going to issue a few pull requests in areas of contribution model, architecture proposals and general guidelines how we can collaborate together.

@opsroller @snooyen @surj-bains @waveywaves is there anything more we could focus on apart from dedicating more engineering effort from VirtusLab's end? Do you see some obvious community engagement issues we can address now?

**Comment by bainss** [comment]
Hi @antoniaklja , That's great news! I'm sure the community will benefit massively from the additional engagement. I think the transparency you are giving will overcome the disconnect that is currently present.

**Comment by antoniaklja** [comment]
Glad to hear that @bainss :) Moreover in the next two weeks, we should get back with the initial version of high-level project roadmap towards more modularization and fine-grained k8s Custom Resources (which we already discussing internally).

Which I'm happy to present live, back to the community and discuss over the office hours or dedicated call if needed.

**Comment by dene14** [comment]
@antoniaklja any update on the roadmap?

**Comment by antoniaklja** [comment]
@dene14 yes, I've sent a [note](https://groups.google.com/d/msgid/jenkinsci-dev/974e2999-273c-4247-9c6d-f052811d505en%40googlegroups.com?utm_medium=email&utm_source=footer) to @jenkinsci/board the following documents:

- [Jenkins Operator Roadmap and Vision](https://docs.google.com/document/d/1Rbv27DLHz-UyIZ5q_4ER7VpO1GVzrrsyN3royrQPymM/edit?usp=sharing)
- [Governance Model proposal](https://docs.google.com/document/d/163bJco3_F7ZzdqnIAVLtNx8ZbmJHRMEvm4jq23I4kcw/edit?usp=sharing) - still early version, expect next update by end of 2020
- [Contribution Model](https://docs.google.com/document/d/1Kq088u8TJOOG5JtnXV7EADiuX0cH1VwbSy4sFzkZ0so/edit?usp=sharing) - will issue a new pull request with this soon
 
Of course, we are open for any feedback regarding the roadmap, in the meantime, the team is already working on it. 
I assume we'll be discussing these early next year, then making everything visible on the website/github/docs.

**Comment by Sig00rd** [comment]
Closing this since the questions have been answered.
