### ISSUE TITLE
k8s cluster domain not properly detected

### ISSUE THREAD

**Issue by iwwwwwwi** [jenkinsci/kubernetes-operator#461]
# Expected Behavior
When a k8s cluster gets deployed using a custom cluster domain (other than cluster.local) all configurations referencing cluster domain use a proper domain name.

# Actual Behavior
Urls referencing resources in the cluster use `cluster.local` instead of the actual domain used on the cluster. This issue exhibits for example in Kubernetes URL parameter in k8s cloud configuration. This prevents the seed job agent to properly register back with jenkins master since it's not reachable from the agent due to wrong domain.

# Steps to Reproduce the Problem

1. Create k8s cluster where cluster domain is other than cluster.local
2. Deploy jenkins using kubernetes operator with seed job defined in jenkins yaml.
3. Log into Jenkins and go to Manage Jenkins -> Manage Nodes and Clouds ->  Configure Clouds -> Kubernetes Cloud Details.
Kubernetes URL, as well as Jenkins URL and Jenkins Tunnel parameters would have a wrong domain configured (cluster.local vs actual domain).

# Additional Info

- Kubernetes version: 

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

- Jenkins Operator version:

```
v0.4.0
```

It appears that the fuction here https://github.com/jenkinsci/kubernetes-operator/blob/v0.4.0/pkg/controller/jenkins/configuration/base/resources/service.go#L90 is returning false even when the operator is running in the cluster.
When swapped lines #96 and #98 around Jenkins URL and Jenkins Tunnel got configured properly although Kubernetes URL was still wrongly using domain.local.

**Comment by tomaszsek** [comment]
Fixed in https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.5.0
