### ISSUE TITLE
support for migration from on prem or other jenkins installations such as vm/helm chart/docker

### ISSUE THREAD

**Issue by sarabesh** [jenkinsci/kubernetes-operator#468]
# Expected Behavior
It would be very helpful to have a proper migration mechanism or function to migrate data such as job history from previous jenkins installations. Sure the casc can be exported from the plugin, but it is difficult to migrate the job history.

# Actual Behavior
Currently, the only work around I was able to use was to create a backup zip file in backup volume similar to how it will be created by jenkins operator for it's backup with high number to avoid it getting overriden, and use that backup in restore.

And also if possible easier way to specify backup number for restore,.and maybe failover to use previous backup,.when current one fails

**Comment by SylwiaBrant** [comment]
Hello @sarabesh,
for now there's no process that would support it. Such process as it is requires manual creation of a backup without job definitions, writing job definitions into job-dsl-plugin format as groovy script and somehow saving jenkins configuration as cascs or groovy.

**Comment by Sig00rd** [comment]
Thank you for your input. Adding generic mechanisms for migrating legacy Jenkins to one managed by Operator would be a very complex task, and it's not currently on the roadmap.
