### ISSUE TITLE
Custom CA Certificate inside seed-job-agent-master

### ISSUE THREAD

**Issue by Fixmetal** [jenkinsci/kubernetes-operator#470]
Hello, thanks for the awesome project.
This is more of a request rather than an issue really.

I've build a new image on top of jenkins-inbound-agent image including our custom CA certificate in OS and Java Key store, but I am struggling to find any example on how to override the image of the `seed-job-agent-master` pod. Is there a way to achieve this?
Thanks in advance

# Additional Info
- Kubernetes version:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Jenkins Operator version:

```
v4.0
```

**Comment by Fixmetal** [comment]
For anyone out there googling: I just noticed (thanks to the Slack channel) that this part is still hard coded (row 
[seedjobs.go](https://github.com/jenkinsci/kubernetes-operator/blob/v0.4.0/pkg/controller/jenkins/configuration/user/seedjobs/seedjobs.go#L412).

It kinda surprises me that such a thing is hardcoded as constant.

I guess a very nice feature would be to let it be overridable.

Is there anybody willing to do an enhancement PR?

**Comment by SylwiaBrant** [comment]
Hello, as part of our [Roadmap](https://github.com/jenkinsci/kubernetes-operator/blob/master/ROADMAP.md) we're working on features that will enable using custom seed job image. Please look forward to it :)

**Comment by Fixmetal** [comment]
Hello, I've seen that 0.6.0 has been released but couldn't see a fix to this. Can you please confirm? @SylwiaBrant

**Comment by Fixmetal** [comment]
Sorry for asking, but is there any update on this?

**Comment by brokenpip3** [comment]
Closing since this is possible atm by using the crd `spec.seedJobAgentImage`
1) [code](https://github.com/jenkinsci/kubernetes-operator/blob/d91a729ccf895a9e10155ccc262e1f1d826ad4af/pkg/configuration/user/seedjobs/seedjobs.go#L421-L424)
2) [chart value](https://github.com/jenkinsci/kubernetes-operator/blob/d91a729ccf895a9e10155ccc262e1f1d826ad4af/chart/jenkins-operator/values.yaml#L130)
