### ISSUE TITLE
Operator Website has a wrong copyright

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/kubernetes-operator#473]
See the footer of https://jenkinsci.github.io/kubernetes-operator/ . Although the website sources and content are open-source , but the footer says that "All rights reserved". It is not correct since the website contents are licensed under the Apache License 2.0 as the rest of the site

![image](https://user-images.githubusercontent.com/3000480/99267574-66966c80-2824-11eb-8726-88cdd2ff57d7.png)

# Expected Behavior

* The footer references Virtus lab somehow, but not with "All"
* There is a Jenkins attribution as documented in https://www.jenkins.io/project/trademark/#trademark-attribution 

# Actual Behavior

* "Virtus Lab - All rights reserved"

# Steps to Reproduce the Problem

1. Go to https://jenkinsci.github.io/kubernetes-operator/

**Comment by pdolega** [comment]
Thanks, we'll fix it shortly.
