### ISSUE TITLE
How can I save the Jenkins job after regression is finished to a new directory with that day date and time and job title 

### ISSUE THREAD

**Issue by vsutrave** [jenkinsci/kubernetes-operator#478]
# Expected Behavior: How can I save the Jenkins job after regression is finished to a new directory with that day date and time and job title 

# Actual Behavior

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Jenkins Operator version:

```
  (paste your output here)
  ```

**Comment by SylwiaBrant** [comment]
Hello @vsutrave, what plugins are you using? You can install plugins, like these: 
https://plugins.jenkins.io/regression-report-plugin/ 
https://plugins.jenkins.io/test-results-analyzer/
https://plugins.jenkins.io/bootstraped-multi-test-results-report/
Does this satisfy your needs?

**Comment by vsutrave** [comment]
So I have those plugins I see them in my “installed” lists but can you please provide me a procedure how to save the logs or complete job that was running in the regression in Jenkins to a different directory, because the data gets lost when new regression runs for the job

For example:
Attachment 1: 1jenkins jobs running front page

Shows the jobs running in the regression and I for example I have highlighted one job in this case, once you click on that you get following attachment2

Attachment 2:  2 build history job #563

Above job has finished successfully as you can see I have highlighted  with build no -->#563 and it save it in following location

/opt/local/regr/workspace/Flint_Regression_FIB/fpga-flint/fib/sim/utb


But when next build starts and finishes above location data of previous build gets erased. So I want it go get saved in different directory with its build name job name and date and time



Can you please provide me a procedure on how to do that ?


Yours faithfully,
Venkatasubbarao sutrave

**Comment by SylwiaBrant** [comment]
@vsutrave please provide the screenshots you were talking about so we can better understand your problem

**Comment by vsutrave** [comment]
Please, loo at the attachment for the screen shorts.


Yours faithfully,
Venkatasubbarao sutrave

**Comment by Sig00rd** [comment]
Logs are stored on Jenkins controller (master) container at $JENKINS_HOME/jobs/<job-name>/builds/<build-name>/log
So you can script the job to save the logs as you see fit, to volume mounted to Jenkins pod, or send it to mail or AWS S3 or something. 
For more info you can file an issue under Jenkins project
