### ISSUE TITLE
persist Jenkins operator data (created jobs, configurations...)

### ISSUE THREAD

**Issue by abdessamadcdg** [jenkinsci/kubernetes-operator#493]
# Expected Behavior
**hello, we want to persist our jobs, configurations, data after restarting pods.**
# Actual Behavior
**we lost data (jobs created, configurations, settings...) after restarting pods**
this is the configuration used:

> 

   priorityClassName:
    disableCSRFProtection: false
    containers:
      - name:  jenkins-master
        image: jenkins/jenkins:lts
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 12
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 80
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 1500m
            memory: 3Gi
          requests:
            cpu: 1
            memory: 500Mi
      - name: backup
        image: virtuslab/jenkins-operator-backup-pvc:v0.0.8
        imagePullPolicy: IfNotPresent
        env:
        - name: BACKUP_DIR
          value: /backup
        - name: JENKINS_HOME
          value: /jenkins-home
        - name: BACKUP_COUNT
          value: "3"
        volumeMounts:
        - mountPath: /jenkins-home
          name: jenkins-home
        - mountPath: /backup
          name: backup
    volumes:
    - name: backup
      persistentVolumeClaim:
        claimName: jenkins-backup
    - name: jenkins-home
      persistentVolumeClaim:
        claimName: jenkins-home
    securityContext:
      fsGroup: 1000
      runAsUser: 1000
  seedJobs:
    - description: Jenkins Operator repository
      id: jenkins-operator
      repositoryBranch: master
      repositoryUrl: https://github.com/jenkinsci/kubernetes-operator.git
      targets: cicd/jobs/*.jenkins

> 

# Additional infos
 Jenkins Operator version: 

```
  v0.4.0
  ```
Kubernetes verion: 
```
  v1.17.3
  ```

**Comment by SylwiaBrant** [comment]
Hello, backup and restore have been greatly adjusted since the versions you used, especially through release of v0.5.0 of the jenkins-operator and v0.1.0 of the backup image. I'll update docs to avoid such situations in the future. Please update the image version in your Custom Resource and use operator version v0.5.0 and tell me if everything works as expected.

**Comment by abdessamadcdg** [comment]
thank you for your reply, it works because we made all our jobs as code and the operator reload them directly.
