### ISSUE TITLE
Migrate Jenkins instance from Pod to Deployment

### ISSUE THREAD

**Issue by antoniaklja** [jenkinsci/kubernetes-operator#497]
We should use Deployment instead of Pod. This change will unlock more abilities and gives us more control over the Jenkins.

**Comment by Chris-Carmichael** [comment]
I'm running into a problem with the active-directory plugin not honoring the site.  Jenkins can't connect to every domain controller on the network, which causes auth problems.  A simple addition to `/etc/hosts` would solve the problem, but I'm not able to do it with the current pattern.  A deployment would solve that for me also.

**Comment by brokenpip3** [comment]
close as duplicate of https://github.com/jenkinsci/kubernetes-operator/issues/195
