### ISSUE TITLE
Improve documentation on setting Jenkins system variables

### ISSUE THREAD

**Issue by jeff-knurek** [jenkinsci/kubernetes-operator#502]
**Describe the bug**

It's possible to update Jenkins master env vars to add JAVA_OPTS, however if you don't included some defaults, Jenkins master won't actually start.

**To Reproduce**

It might be possible that you want to have Jenkins master start with some system variables, for example:
`-XX:MaxPermSize=1024m -Dmaven.test.failure.ignore=false`

These can be applied like:
```
spec:
  master:
    containers:
      - name: jenkins-master
        env:
          - name: JAVA_OPTS
            value: "-XX:MaxPermSize=1024m -Dmaven.test.failure.ignore=false"
```
But you'd end up with Jenkins not starting due to errors like:
```
Jenkins Master container env 'JAVA_OPTS' doesn't have required flag '-Djenkins.install.runSetupWizard=false'
```

So the documentation (possible before/after https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/configuration/#http-proxy-for-downloading-plugins ) should indicate using this pattern:

```
spec:
  master:
    containers:
      - name: jenkins-master
        env:
          - name: JAVA_OPTS
            value: "-Djenkins.install.runSetupWizard=false -Djava.awt.headless=true -XX:MaxPermSize=1024m -Dmaven.test.failure.ignore=false"
```

**Additional information**

Even better would be if the operator itself included these required defaults :shrug: 

Add error logs about the problem here (operator logs and Kubernetes events).
```
WARN    controller-jenkins  jenkins/jenkins_controller.go:253   Validation of base configuration failed, please correct Jenkins CR. {"cr": "jenkins"}
WARN    controller-jenkins  jenkins/jenkins_controller.go:255   Jenkins Master container env 'JAVA_OPTS' doesn't have required flag '-Djava.awt.headless=true'  {"cr": "jenkins"}
WARN    controller-jenkins  jenkins/jenkins_controller.go:255   Jenkins Master container env 'JAVA_OPTS' doesn't have required flag '-Djenkins.install.runSetupWizard=false'    {"cr": "jenkins"}
```

**Comment by SylwiaBrant** [comment]
Hello, Jenkins Operator is setting the defaults if nothing was specified. If user declares JAVA_OPTS in the CR the defaults are overridden instead of merged together as that would be quite complicated since it would require many edge cases. But we created the validation you've observed. I'll update the docs and clearly state that if someone wants to use custom options they also need to specify the defaults. Thank you for your input :)
