### ISSUE TITLE
Helm Chart 0.4.1 Missing JenkinsImage CRDs

### ISSUE THREAD

**Issue by snooyen** [jenkinsci/kubernetes-operator#503]
**Describe the bug**
After installing jenkinsci/kubernetes-operator 0.5.0 via Helm Chart v0.4.1, the jenkins-operator pod enters crashloop backoff because JenkinsImage CRD is missing.

**To Reproduce**
Install jenkinsci/kubernetes-operator 0.5.0 via Helm Chart v0.4.1

**Additional information**

Kubernetes version: 1.18.9
Jenkins Operator version: 0.5.0

Add error logs about the problem here (operator logs and Kubernetes events).

> 2021-01-26T21:13:27.395Z	ERROR	controller-runtime.source	source/source.go:88	if kind is a CRD, it should be installed before calling Start	{"kind": "JenkinsImage.jenkins.io", "error": "no matches for kind \"JenkinsImage\" in version \"jenkins.io/v1alpha2\""}
2021-01-26T21:13:27.396Z	ERROR	controller-jenkins.cmd	manager/main.go:274	failed to start cmd: no matches for kind "JenkinsImage" in version "jenkins.io/v1alpha2"

**Comment by Dudesons** [comment]
There is a workaround ? because I'm stuck to upgrade this chart

**Comment by snooyen** [comment]
@Dudesons I worked around it by executing 

`kubectl apply -f https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/deploy/crds/jenkins_v1alpha2_jenkinsimage_crd.yaml`

**Comment by SylwiaBrant** [comment]
Hello, I've updated the docs about the issue and released fixed Helm Chart v0.4.2. I'll be closing this issue. Thank you for your contribution :)
