### ISSUE TITLE
Viewing K8s Agent events errors due to missing permissions

### ISSUE THREAD

**Issue by rmb938** [jenkinsci/kubernetes-operator#507]
**Describe the bug**

When viewing a kubernetes agent events in the UI the jenkins logs error with the following:

```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://kubernetes.default.svc.cluster.local/api/v1/namespaces/jenkins/events?fieldSelector=involvedObject.name%3Djenkins-slave-h5c82%2CinvolvedObject.uid%3D8de10866-a100-4d23-b951-325fed7c30a8%2CinvolvedObject.namespace%3Djenkins. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. events is forbidden: User "system:serviceaccount:jenkins:jenkins-operator-hcc-dp" cannot list resource "events" in API group "" in the namespace "jenkins".
```

**To Reproduce**

Configure the kubernetes cloud agent, run a job using the agent and look in the agent events.

Kubernetes version: 1.17.8
Jenkins Operator version: v0.5.0

Add error logs about the problem here (operator logs and Kubernetes events).

**Comment by KorusMateusz** [comment]
Fixed in https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.6.0
