### ISSUE TITLE
Usage of getLatestAction unclear/wrong

### ISSUE THREAD

**Issue by pniederlag** [jenkinsci/kubernetes-operator#512]
**Describe the bug**

In v0.5.0 the backup/restore was updated to (optionally?) make use of some 'getLatestAction' configuration and script

- Documentation says this should be set on 'spec.backup.getLatestAction' https://github.com/jenkinsci/kubernetes-operator/blob/master/website/content/en/docs/Getting%20Started/latest/configure-backup-and-restore.md
- we see a log message that says 'spec.restore.getLatestAction' is missing, coming from here https://github.com/jenkinsci/kubernetes-operator/blob/a78b9ea77be7e88994d0a9e7af6248e22625bd73/pkg/configuration/backuprestore/backuprestore.go#L167
- we see the spec/type to be set on spec.restore https://github.com/jenkinsci/kubernetes-operator/blob/master/pkg/apis/jenkins/v1alpha2/jenkins_types.go#L606

So, what's wrong here?

Maybe it's just documentation?

Also, it seems like there is a corresponding value in the helm chart. But is it used anywhere? Doesn't look like it to me
https://github.com/jenkinsci/kubernetes-operator/blob/a78b9ea77be7e88994d0a9e7af6248e22625bd73/chart/jenkins-operator/values.yaml#L204

**To Reproduce**

upgrade to v0.5.0 and update configuration to latest best practice

**Comment by pniederlag** [comment]
@SylwiaBrant thx for tackling this, pls check this PR also, it has an additonal { if } condition, but misses the documentation change. 
https://github.com/jenkinsci/kubernetes-operator/pull/506

**Comment by SylwiaBrant** [comment]
Yes, thank you. We'll probably merge the PR you linked, since the decision is to let it stay optional. But I need to resolve another issue prior to that :) I'm sorry for the mess.
