### ISSUE TITLE
v1 CRDS

### ISSUE THREAD

**Issue by rmb938** [jenkinsci/kubernetes-operator#513]
**Describe the solution you'd like**

Create a `apiextensions.k8s.io/v1` version of the CRDS

**Describe alternatives you've considered**

Currently the `apiextensions.k8s.io/v1beta1` version can be found here https://github.com/jenkinsci/kubernetes-operator/blob/master/deploy/crds/jenkins.io_jenkins_crd.yaml not only is this the old apiVersion the schema is out of date and doesn't include `priorityClassName`

**Comment by prryb** [comment]
We are working on a new API schema version that already uses the `apiextensions.k8s.io/v1` CRD API version. `v1beta1` will be removed in Kubernetes v1.22 (https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122). We should have it released before that.

**Comment by scarby** [comment]
@prryb Is there an issue open for this currently? Not sure why this was closed, It still appears to be valid and hasn't been marked as a duplicate or mentioned anywhere else.
