### ISSUE TITLE
This repo should not be a fork of VirtusLab/jenkins-operator

### ISSUE THREAD

**Issue by bitwiseman** [jenkinsci/kubernetes-operator#516]
**Describe the bug**
There are a number of GitHub features that are only available to the root of a fork tree. Also, there are behaviors such as pull requests that default to targeting the root of a fork tree.  

Having VirtusLab gain visibility for their contributions to this project is great, but for functional reason this project should be the root of the fork tree.

**To Reproduce**
Go to https://github.com/jenkinsci/kubernetes-operator and look in the upper right corner of your browser
Steps to reproduce the behavior.

**Additional information**
Making this repo the root of the fork tree without losing fork information from all other forks requires asking GitHub support to reset the root of the fork tree.  It cannot be done from the user facing UI.

**Comment by antoniaklja** [comment]
Hi @bitwiseman, thanks for your feedback, however, the project was initially developed within [VirtusLab](https://virtuslab.com/) and eventually transferred to _jenkinsci_ GitHub organization without losing track of work. 

Currently, we're discussing Jenkins Operator becoming sub-project of Jenkins including new governance model in place.  
Will keep you informed.
