### ISSUE TITLE
Order of User-Configuration and Seed-Job not configurable by user/admin

### ISSUE THREAD

**Issue by pniederlag** [jenkinsci/kubernetes-operator#517]
**Describe the bug**

With #263 the execution order of the seed-job and user-configuration was reversed. While I perfectly understand the reason to do so there are also use-cases that depend on the user-configuration to be executed *after* the seed-job.

**To Reproduce**

We assign roles and permissions in a groovy configuration-as-code snippet. This snippet relies on the jobs to exist. With #263 this setup is now broken

**Additional information**

Jenkins Operator version: v0.5.0

As it seems there is a demand to run CaC *before* the seed-job as well as *after* the seed-job.

Is there a chance we can set two different slots for CaC? Is there any other approach where user/admin get's control over the execution point of CaC in relation to the seed job?

**Comment by marco-krammer** [comment]
I am not that experienced in Go yet, but this doesn't look too complicated. I will try to come up with a PR to make this configurable.

**Comment by SylwiaBrant** [comment]
Hello, that's a really good point. We are currently in the process of changing the architecture. We've already have an initial version of the schema and we all think that reconciling CaSC and Groovy both before and after seed jobs will be a great addition, so we will definitely implement it, but it will take some time until we're ready to release the new Operator. Is this a critical issue?

**Comment by marco-krammer** [comment]
@SylwiaBrant yes that is a critical issue for us as we have to manually run the groovy scripts after a pod restart at the moment.

**Comment by marco-krammer** [comment]
As I stated in my earlier comment I am trying to come up with a fix myself, but didn't have any success there yet :/

**Comment by antoniaklja** [comment]
Hi @marco-krammer, as @SylwiaBrant mentioned, the team is currently implementing a new API schema which will consists of desired changes. 

Currently, I'm afraid changing user configuration flow requires significant work and at the end of the day will be replaced by new implementation anyway.

I'd advise to create a custom job to execute Groovy/CasC code after Jenkins starts if this makes sense.

**Comment by marco-krammer** [comment]
@antoniaklja alright we will leave it as is then and run the configuration in a job after the seed job.
Is there a convenient way to configure triggering another job in the seed jobs post actions programmatically?

**Comment by Sig00rd** [comment]
After re-evaluating this issue I regret to inform that it won't be worked on for a while as it would be significantly more complex to address with new API schema and architectural changes it brings than initially thought.

**Comment by marco-krammer** [comment]
Alright @Sig00rd, thanks for the update. We have now implemented a workaround in the form of a job that is triggered by the seed job after startup and runs all the CasC code via a shared lib method instead.
