### ISSUE TITLE
Certificate error when attempting to register plugins.

### ISSUE THREAD

**Issue by AaronJaegerVA** [jenkinsci/kubernetes-operator#520]
**Describe the bug**

When I attempt to launch a new Jenkins using the operator, I get a certificate error when it attempts to register plugins.

```
[root@vhaispvchdck001 ets-jenkins]# kubectl logs -f pod/jenkins-ets-jenkins-001
+ '[' '' == true ']'
+ echo 'To print debug messages set environment variable '\''DEBUG_JENKINS_OPERATOR'\'' to '\''true'\'''
+ mkdir -p /var/lib/jenkins/init.groovy.d
To print debug messages set environment variable 'DEBUG_JENKINS_OPERATOR' to 'true'
+ cp -n /var/jenkins/init-configuration/createOperatorUser.groovy /var/lib/jenkins/init.groovy.d
+ mkdir -p /var/lib/jenkins/scripts
+ cp /var/jenkins/scripts/init.sh /var/jenkins/scripts/install-plugins.sh /var/lib/jenkins/scripts
+ chmod +x /var/lib/jenkins/scripts/init.sh /var/lib/jenkins/scripts/install-plugins.sh
Installing plugins required by Operator - begin
+ echo 'Installing plugins required by Operator - begin'
+ cat
+ [[ -z '' ]]
+ install-plugins.sh
WARN: install-plugins.sh is deprecated, please switch to jenkins-plugin-cli
Creating initial locks...
Analyzing war /usr/share/jenkins/jenkins.war...
Registering preinstalled plugins...
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**To Reproduce**
`kubectl create -f new-jenkins-instance.yaml`
`kubectl logs -f new-jenkins-master-pod`

**Additional information**

**Kubernetes version**: v1.19.7+rke2r1
**Jenkins Operator version**:   
```
Containers:
   jenkins-operator:
    Image:      virtuslab/jenkins-operator:v0.5.0
```

I believe we have a perimeter network device doing TLS termination and certificate chain rewriting. There have been other cases where I have had to add our internal CA certificates to a trust store to make getting out to TLS-enabled websites on the Internet. I am not sure where I would add those certificates in this case.

**Comment by Sig00rd** [comment]
Hello @AaronJaegerVA . Essentially you need to have the certificates in your Jenkins container trust store. Find out where to put them for the Jenkins image you're using, if you're using alpine based image (like it's done by default), you can refer to answer posted here
https://stackoverflow.com/questions/67231714/how-to-add-trusted-root-ca-to-docker-alpine
to build a custom Jenkins image with your certs in store.

**Comment by AaronJaegerVA** [comment]
Thank you @Sig00rd . I was able to get passed this issue by creating a custom Jenkins image and instructing the operator to use it instead of the default alpine image.
