### ISSUE TITLE
help: configure parameters for pipelines with job

### ISSUE THREAD

**Issue by divramod** [jenkinsci/kubernetes-operator#53]
Hey, thx again for the work on the operator.

I try to get the operator running together with a github app. 
this is running basically with parameters to start the builds.

My problem now is, that i need to add the parameters (with its default values) manually to the pipeline. Are the seed jobs able to do that automatically for me?
The seed job for the pipeline i am trying to do that looks like that:

Any hint on how to configure the pipelines parameters programatically?

```groovy
#!/usr/bin/env groovy

pipelineJob('devops-deploy-pr') {
    displayName('devops: deploy pr')

    logRotator {
        numToKeep(10)
        daysToKeep(30)
    }

    configure { project ->
        project / 'properties' / 'org.jenkinsci.plugins.workflow.job.properties.DurabilityHintJobProperty' {
            hint('PERFORMANCE_OPTIMIZED')
        }
    }

    definition {
        cpsScm {
            scm {
                git {
                    remote {
                        url('git@github.com:.../....git')
                        credentials('ssh-key-jenkins-github-devops')
                    }
                    branches('*/...')
                }
            }
            scriptPath('cicd/pipelines/....groovy')
        }
    }
}
```

**Comment by tomaszsek** [comment]
Hi @divramod,

You can configure it in DSL plugin https://jenkinsci.github.io/job-dsl-plugin/#path/pipelineJob-parameters, for example:
```
job('example') {
    parameters {
        booleanParam('FLAG', true)
        choiceParam('OPTION', ['option 1 (default)', 'option 2', 'option 3'])
    }
}
```

Cheers

**Comment by divramod** [comment]
this works. thx!
