### ISSUE TITLE
Restart Jenkins after restore instead of configuration reloading

### ISSUE THREAD

**Issue by MohamedAmineOuali** [jenkinsci/kubernetes-operator#531]
Hello,

Thank you for this project.

To my knowledge, the operator reloads the Jenkins configuration after a backup restore. Is there a parameter I can add to make the operator restart Jenkins sever instead of reloading the configuration?

Thank you very much.

**Comment by Sig00rd** [comment]
There's no parameter to enforce behaviour like you mentioned and I see no point in restarting Jenkins with only jobs history being restored, but if you think otherwise, feel free to file up a feature request with description of solution you'd like to see and what it would improve. Thanks!
