### ISSUE TITLE
Disable Route Creation in OpenShift

### ISSUE THREAD

**Issue by mk811** [jenkinsci/kubernetes-operator#532]
**Describe the solution you'd like**

When I deploy Jenkins Operator (App Version: 0.5) to OpenShift, it automatically creates Route. Is there any parameters to disable this behaviour? As ingress is maintained by Network team, we are using different Route in OpenShift.
This we don't like Jenkins Operator creates Route which we don't use.

**Comment by Sig00rd** [comment]
For Operator v0.5 it was not possible to disable automatic creation of the Route, and current (v0.6) release of the Operator is not compatible with OpenShift.

**Comment by pleimer** [comment]
@Sig00rd are there plans to make newer versions of this operator compatible with openshift?

**Comment by Sig00rd** [comment]
Hello @pleimer.  It's not currently planned. For users requiring OpenShift compatibility, there is [Operator Service for Jenkins](https://marketplace.redhat.com/en-us/products/operator-service-for-jenkins) available on the Red Hat Marketplace.
