### ISSUE TITLE
Add possibility to set pod affinity/anti-affinity for master pod

### ISSUE THREAD

**Issue by gmarraff** [jenkinsci/kubernetes-operator#538]
**Describe the solution you'd like**
I'd like to have the possibility to set the affinity spec in the pod hosting the master container, as described by the [kubernetes doc](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity).

**Describe alternatives you've considered**
I also tried to set the [schedulerName](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity-per-scheduling-profile) field but also that seems to be ignored.

**Additional context**
I'd like to have this feature because in the current cluster we are running several Jenkins instances, and some of them are really heavy on network resources, so it will be better to have them scheduled on different nodes: the pod anti-affinity mechanism seems to be perfect for the purpose.
Is there a way to achieve this behavior with the latest version of the operator?

Thanks for the good work!

**Comment by KorusMateusz** [comment]
Hello, we are currently working on a new API implementation. In the new API we're using a Deployment for Jenkins instance so that will allow you to pass the `affinity` field
