### ISSUE TITLE
Nightly Builds

### ISSUE THREAD

**Issue by prryb** [jenkinsci/kubernetes-operator#555]
Set up nightly builds of the operator docker image.

Add a workflow that will trigger during night-time, and, if tests pass, publish a nightly image to docker hub.

Include short commit hash in the tag name (`git rev-parse --short HEAD`). Proposed tag format: `nightly-{short_hash}`

**Comment by leifmadsen** [comment]
Would it be possible to also mirror to quay.io? The Docker Hub quota limits really affects me behind the firewall at work. I end up having to mirror the image in to the internal registry rather than just pulling it from the remote registry.

**Comment by prryb** [comment]
@leifmadsen that's a cool idea 👍 - I've created an issue to do that: https://github.com/jenkinsci/kubernetes-operator/issues/559

**Comment by leifmadsen** [comment]
Thanks!
