### ISSUE TITLE
Mirror releases to quay.io

### ISSUE THREAD

**Issue by prryb** [jenkinsci/kubernetes-operator#559]
Release the docker images to both https://hub.docker.com/ and https://quay.io/

- [ ] Set up quay.io docker repo.
- [ ] Modify `container-runtime-release` makefile goal.
- [ ] Push latest release images to the new repo.
- [ ] Update docs.

Proposed by @leifmadsen:

> Would it be possible to also mirror to quay.io? The Docker Hub quota limits really affects me behind the firewall at work. I end up having to mirror the image in to the internal registry rather than just pulling it from the remote registry.

**Comment by Sig00rd** [comment]
Closing this as there are no plans to work on this for some time with new API ahead
