### ISSUE TITLE
Installing this chart from master causes operator pod to crash

### ISSUE THREAD

**Issue by scarby** [jenkinsci/kubernetes-operator#563]
**Describe the bug**
Installing this chart from master causes operator pod to crash

In this case:
https://github.com/jenkinsci/kubernetes-operator/pull/551/files#diff-6ba34268624276e15c00b82e4c9638a3dacb2ea570711aa78a200847b8c5bedeL33

has update the command run by the operator container to:
```
/manager
```

this command does not exist within  the `virtuslab/jenkins-operator:v0.5.0` image - which is the default container for this chart:

```
Containers:
  jenkins-operator:
    Container ID:  containerd://229d2c3b844843baf57b1e8e0cf23f9bb4b74df82d867536ecc2430f9281953f
    Image:         virtuslab/jenkins-operator:v0.5.0
    Image ID:      docker.io/virtuslab/jenkins-operator@sha256:6cde31b5264abaad393e6eb833124f3f34b18deae0cb575f7cc59cd61a989ea6
    Port:          80/TCP
    Host Port:     0/TCP
    Command:
      /manager
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       StartError
      Message:      failed to create containerd task: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "/manager": stat /manager: no such file or directory: unknown
      Exit Code:    128
      Started:      Wed, 31 Dec 1969 16:00:00 -0800
      Finished:     Mon, 10 May 2021 10:54:21 -0700
```

**To Reproduce**
- checkout repo
- install chart from master without specifying a default container
- 
**Additional information**

Kubernetes version: 1.19
Jenkins Operator version: master

**Comment by prryb** [comment]
The latest released version of the helm chart (which currently is 0.4.3) should work fine.

The chart will be updated soon.
