### ISSUE TITLE
documentation changes for 0.6 release

### ISSUE THREAD

**Issue by pniederlag** [jenkinsci/kubernetes-operator#574]
big thx for shipping an updated 0.6 release. :100: 

I noticed on the release notes it says "does not support openshift". If that is really true please add a note into https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/openshift/ so openshift users won't try to start the impossible ;)

Other than that, a section for upgrading from 0.5 to 0.6 would of course also be very welcome. ;)

Thx for putting your time onto this awesome project

**Comment by prryb** [comment]
Hello and thank you 🙂 

We've updated the docs, also the release notes contain some information about the migration guide. 

Unfortunately, the migration requires re-applying the CRDs.
