### ISSUE TITLE
Install jenkins-operator offline, it prompts that updates.jenkins.io cannot be connected, how to skip it?

### ISSUE THREAD

**Issue by xiaofan-linux** [jenkinsci/kubernetes-operator#581]
>>> logs -f -n jenkins-system jenkins-jenkins --container jenkins-master
+ '[' '' == true ']'
+ echo 'To print debug messages set environment variable '\''DEBUG_JENKINS_OPERATOR'\'' to '\''true'\'''
+ mkdir -p /var/lib/jenkins/init.groovy.d
To print debug messages set environment variable 'DEBUG_JENKINS_OPERATOR' to 'true'
+ cp -n /var/jenkins/init-configuration/createOperatorUser.groovy /var/lib/jenkins/init.groovy.d
+ mkdir -p /var/lib/jenkins/scripts
+ cp /var/jenkins/scripts/init.sh /var/jenkins/scripts/install-plugins.sh /var/lib/jenkins/scripts
+ chmod +x /var/lib/jenkins/scripts/init.sh /var/lib/jenkins/scripts/install-plugins.sh
+ echo 'Installing plugins required by Operator - begin'
+ cat
Installing plugins required by Operator - begin
+ [[ -z '' ]]
+ install-plugins.sh
WARN: install-plugins.sh is deprecated, please switch to jenkins-plugin-cli
Creating initial locks...
Analyzing war /usr/share/jenkins/jenkins.war...
Registering preinstalled plugins...
curl: (6) Could not resolve host: updates.jenkins.io

Install jenkins-operator offline, it prompts that updates.jenkins.io cannot be connected, how to skip it?

**Comment by prryb** [comment]
Offline installations are currently not supported by the operator.

**Comment by willzhang** [comment]
jenkins helm chart support skip installLatestPlugins, maybe jenkins operator support this too ?
```
helm install jenkins \
--set controller.installLatestPlugins=false
```
