### ISSUE TITLE
Upgrade Kubernetes plugin to 1.30.0

### ISSUE THREAD

**Issue by thecooldrop** [jenkinsci/kubernetes-operator#587]
**Describe the bug**
During running of Jenkins Kubernetes Operator on local `kind` cluster I was not able to run my pipelines in Pods due to an issue in 1.29.7 Kubernetes plugin. Namely it seems that there was a build-error for this plugin version and any attempt to run a pipeline within a Pod results in `NoSuchMethodException`, due to lack of `fabric8` methods.

**To Reproduce**
Follow the following steps:
- Download Kind tool
- Execute command `kind cluster create`
- Install Jenkins operator into local cluster with default values provided by the chart ( Helm installation )
- Login to the instance via port-forwarding
- Create a new pipeline, and choose to run sample pipeline `Declarative (Kubernetes)`
- Run it
- Observe how large number of Pods get created and never start

![image](https://user-images.githubusercontent.com/17129522/122873540-2eaf5480-d332-11eb-8230-95f3cab5e884.png)

**Additional information**

Kubernetes version: 1.21.1
Jenkins Operator version: 0.6

**Comment by prryb** [comment]
https://github.com/jenkinsci/kubernetes-operator/pull/579

That's already merged in.

**Comment by prryb** [comment]
You can always supply upgraded plugins in `basePlugins` - the default version of `kubernetes` plugin is upgraded to 1.30.0 on `master` branch – it will go out in the next release.
