### ISSUE TITLE
Documentation: Jenkins home directory

### ISSUE THREAD

**Issue by thecooldrop** [jenkinsci/kubernetes-operator#589]
As a new user of Jenkins Kubernetes Operator I have not been aware of the "immutability principle" which underlies some of architectural choices made for the Kubernetes operator. This has lead to me to to repeatedly try to repalace Jenkins `emptyDir` volume used as home directory with some PVC-based Volume resource.

As I have noticed that at least couple of issues have been raised due to improper configuration of Jenkins home directory I feel strongly that correct configuration and principles need to be documented so that this pitfall can be avoided by future users.

Acceptance criteria:
- Documentation includes the issue
- Default values.yaml file contains a reference to documentation and at least 1 sentence describing the problem.

**Comment by Sig00rd** [comment]
Hello, thanks for your input! I've updated the docs with #608.
