### ISSUE TITLE
podTemplate - global or specific with readTrusted

### ISSUE THREAD

**Issue by styk-tv** [jenkinsci/kubernetes-operator#591]
I couldn't find anything in the documentation nor previous issues so asking here:

1. Could you please share an example on how to create a global podTemplate using jenkins-operator-user-configuration
2. Could you please share an example on how where to attach a custom pod template so it could be used with readTrusted as per here? Example overwriting some values using DSL variables would be ideal. For example with container version.

Reference:
<img width="866" alt="Screenshot 2021-06-30 at 10 40 36" src="https://user-images.githubusercontent.com/838921/123939518-1d002980-d990-11eb-9cb4-527d8a0aea40.png">
https://github.com/jenkinsci/kubernetes-plugin#example

NOTE: goal here is to avoid duplication of same podTemplate across jobs when using inline method

**Comment by SylwiaBrant** [comment]
Hello, questions about exact usage of pod template options and overriding values would be better addressed at the corresponding plugins providers' sites. According to https://www.jenkins.io/doc/pipeline/steps/workflow-multibranch/#readtrusted-read-trusted-file-from-scm you need to have the pod template in the VSC. If you have it in the same place as the pipeline file, you have direct access. You can also write code to fetch it from other repos.

**Comment by prryb** [comment]
As @SylwiaBrant said, there are some possibilities, you can use VCS to store these files with templates, use them as a git submodule, or check them out as part of the job. You probably event could attach a volume to Jenkins with these templates. The `kubernetes-plugin` community could provide more information on that matter.
