### ISSUE TITLE
Reconciliation restarts from client timeouts

### ISSUE THREAD

**Issue by dgilmanTORQATA** [jenkinsci/kubernetes-operator#594]
**Describe the bug**
There's a timeout when reconciliation goes to create a Jenkins client to ping the instance. It's hardcoded. For whatever reason after updating to v0.6.0 my Jenkins master is getting lagged every few hours, exceeding the ten second timeout, and rebooting the Jenkins master. There's no indication of high memory or CPU usage of the Jenkins master when this happens.

If there isn't a known issue here, is it at least possible to tune the [10 second hardcoded timeout](https://github.com/jenkinsci/kubernetes-operator/blob/master/pkg/client/jenkins.go#L162) on this?

**Additional information**

Kubernetes version: GKE 1.19.10-gke.1600
Jenkins Operator version: v0.6.0
Jenkins plugins: all updated to latest

Add error logs about the problem here (operator logs and Kubernetes events).
```
Reconcile loop failed: Get "http://jenkins-operator-http-main.jenkins:8080/api/json": dial tcp 10.32.12.94:8080: connect: connection refused
couldn't init Jenkins API client
github.com/jenkinsci/kubernetes-operator/pkg/client.newClient
 /workspace/pkg/client/jenkins.go:178
github.com/jenkinsci/kubernetes-operator/pkg/client.NewUserAndPasswordAuthorization
 /workspace/pkg/client/jenkins.go:138
github.com/jenkinsci/kubernetes-operator/pkg/configuration.(*Configuration).GetJenkinsClientFromSecret
 /workspace/pkg/configuration/configuration.go:254
github.com/jenkinsci/kubernetes-operator/pkg/configuration.(*Configuration).GetJenkinsClient
 /workspace/pkg/configuration/configuration.go:186
github.com/jenkinsci/kubernetes-operator/pkg/configuration/base.(*JenkinsBaseConfigurationReconciler).Reconcile
 /workspace/pkg/configuration/base/reconciler.go:101
github.com/jenkinsci/kubernetes-operator/controllers.(*JenkinsReconciler).reconcile
 /workspace/controllers/jenkins_controller.go:252
github.com/jenkinsci/kubernetes-operator/controllers.(*JenkinsReconciler).Reconcile
 /workspace/controllers/jenkins_controller.go:136
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
 /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:263
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
 /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:235
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1
 /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:198
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1
 /go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
 /go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
 /go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
 /go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext
 /go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.UntilWithContext
 /go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:99
runtime.goexit
 /usr/local/go/src/runtime/asm_amd64.s:1374 {"cr": "main"}
github.com/go-logr/zapr.(*zapLogger).Info
 /go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:126
github.com/jenkinsci/kubernetes-operator/controllers.(*JenkinsReconciler).Reconcile
 /workspace/controllers/jenkins_controller.go:175
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
 /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:263
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
```

**Comment by Sig00rd** [comment]
The timeout was introduced in order not to have Operator waiting for Jenkins API forever in cases it wasn't responding at all, but as long as it manages to connect to the API within 10 retries of reconcile loop it shouldn't be a problem. Is that the case, or are you getting ```Reconcile loop failed 10 times```?

**Comment by dgilmanTORQATA** [comment]
After doing some investigation it turns out that the Jenkins container was actually crashing so the API call would never come back working. It may be worth adding/increasing timeouts to reduce reconciliation loops and log spam while the Jenkins master container is restarting, downloading all the plugins and such as that will always take a minute or two.

**Comment by prryb** [comment]
We'll take your suggestion into consideration. 👍  Longer requeue times will make the process of configuring Jenkins longer. Increasing the HTTP client timeout won't help in this case, as logs indicate that connecting to the Jenkins API did not fail due to a timeout, but the connection was refused.
