### ISSUE TITLE
Empty backups

### ISSUE THREAD

**Issue by wawrzek** [jenkinsci/kubernetes-operator#596]
**Describe the bug**
The script creates empty backups for our configuration. 

Additionally, I cannot understand why config.xml in a job directory is not backup up. It should be, especially for something like GitHub organization project.

**To Reproduce**
Use default backup configuration.

**Additional information**

Kubernetes version: 1.20.7
Jenkins Operator version: 0.6

Add error logs about the problem here (operator logs and Kubernetes events).

**Comment by KorusMateusz** [comment]
Hello,

Because of Jenkins Operator's architecture, the configuration of Jenkins should be done using ConfigurationAsCode or GroovyScripts and jobs should be defined as SeedJobs. Because of that you only need to backup jobs' history, which is how the backup script works.

**Comment by wawrzek** [comment]
Ah, that make sense. Could you add a short paragraph explaining that to the documentation? Maybe something like that:

> Because of Jenkins Operator's architecture, the configuration of Jenkins should be done using ConfigurationAsCode or GroovyScripts and jobs should be defined as SeedJobs. It means that there is no point to back any job configuration up. Therefore, the backup script take copy of jobs history only.

That might be a good place to add it: https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/configure-backup-and-restore/

**Comment by prryb** [comment]
Docs updated!
