### ISSUE TITLE
PriorityClassname removed after deployment

### ISSUE THREAD

**Issue by mortenbirkelund** [jenkinsci/kubernetes-operator#605]
https://github.com/jenkinsci/kubernetes-operator/blob/9d5c525ace0b68efeaf402e8d6e589b0cf72c0b8/chart/jenkins-operator/templates/jenkins.yaml#L104

I use ArgoCD for managing my Kubernetes cluster. 

I have installed jenkins operator using helm (latest version)

Whenever I deploy Jenkins, argo shows that everything is synced, but shortly after, jenkins is out of sync with the code. 

It seems like the cluster is removing the priorityclassname because it is empty. 

![image](https://user-images.githubusercontent.com/8955039/127003229-4ab916e8-017e-474a-9f67-d923d289911d.png)

I am not sure, but perhaps line 103 and 104 should be removed, so that priorityclassname is only present, if it is set in the values file??

**Comment by Sig00rd** [comment]
Hello @mortenbirkelund, thank you for pointing this out. It does look like it's redundant, I've just confirmed locally that removing these lines doesn't seem to break anything, and priorityClassName is optional in the API anyway.
Would you like to issue a PR for this? Apart from removing the lines you mentioned, the chart version needs to be bumped.
