### ISSUE TITLE
Jenkins master node spec's resource limits and requests are overridden

### ISSUE THREAD

**Issue by jorgenkg** [jenkinsci/kubernetes-operator#64]
### Motivation

The default values are too aggressive on CPU and too lenient on RAM. In our use case it makes sense to remove the hard limit on RAM and CPU, and increase the memory request value. The default values are as follows:

```yaml
resources:
  limits:
    cpu: 1500m
    memory: 3Gi
  requests:
    cpu: 1000m
    memory: 500Mi
```

### Bug

[As per the examples in the documentation](https://github.com/jenkinsci/kubernetes-operator/blob/50c973dc2261de25047ad5e51fea0e3d09d1043b/deploy/crds/jenkins_v1alpha2_jenkins_cr.yaml#L31) it appears to be possible to adjust the Kubernetes resource request using the Jenkins master node spec:

```yaml
apiVersion: jenkins.io/v1alpha2
kind: Jenkins
spec:
  master:
    containers:
    - name: jenkins-master
      image: jenkins/jenkins:lts
      # Attempting to specify resource values:
      resources:
        requests:
          cpu: 500m
          memory: 2.5Gi
```

However, the Jenkins container is still created with default resource values.

The operator logs the following lines when we attempt to update the resource requirements on the container (and the Jenkins pod isn't cycled/updated):

```plain
2019-07-30T14:32:16.634Z  INFO  controller-jenkins  jenkins/handler.go:89 *v1alpha2.Jenkins/jenkins has been updated  {"cr": "jenkins"}
2019-07-30T14:32:16.634Z  INFO  controller-jenkins  jenkins/jenkins_controller.go:353 Setting default Jenkins master container resource requirements  {"cr": "jenkins"}
2019-07-30T14:32:16.717Z  INFO  controller-jenkins  jenkins/handler.go:89 *v1alpha2.Jenkins/jenkins has been updated  {"cr": "jenkins"}
```

### Versions
Operator API version: `jenkins.io/v1alpha2`
Jenkins operator version: `v0.1.1`
```plain
2019-07-30T14:27:12.023Z	INFO	controller-jenkins	manager/main.go:44	Version: v0.1.1
2019-07-30T14:27:12.023Z	INFO	controller-jenkins	manager/main.go:45	Git commit: 6fffcb6
2019-07-30T14:27:12.023Z	INFO	controller-jenkins	manager/main.go:46	Go Version: go1.12
2019-07-30T14:27:12.023Z	INFO	controller-jenkins	manager/main.go:47	Go OS/Arch: linux/amd64
2019-07-30T14:27:12.023Z	INFO	controller-jenkins	manager/main.go:48	operator-sdk Version: v0.8.1
```

**Comment by jorgenkg** [comment]
I've discovered a caveat in the code that prevents a setting up the operator without hard limits on RAM and CPU. There is an if check that verifies that both requests and limits are specified in [jenkins_controller.go#L455](https://github.com/jenkinsci/kubernetes-operator/blob/dda0a0075ea7a8ad35200401d54e46c4fd8c5032/pkg/controller/jenkins/jenkins_controller.go#L455).

Thus you have to specify all resource fields in the Jenkins master node's YAML otherwise the operator will inject a default configuration.

Is there a rationale for enforcing a "default configuration" for Kubernetes resource constraints?

**Comment by tomaszsek** [comment]
Hi @jorgenkg,

Setting limits for requests and limits is a Kubernetes good practice. Without that Kubernetes scheduler won't work properly. That's why we set limits even if user did not specyfied them.

Cheers

**Comment by Dudesons** [comment]
> Hi @jorgenkg,
> 
> Setting limits for requests and limits is a Kubernetes good practice. Without that Kubernetes scheduler won't work properly. That's why we set limits even if user did not specyfied them.
> 
> Cheers

Hi,

There is a way to let the user to choose if they want to set limit.
An example in our case we are setting:
 * memory request and limit
 * cpu request

We prefe rto let the cpu share feature work and avoid cpu throttling.

**Comment by hablislim** [comment]
@Dudesons  I was looking for the same thing and I found this thread ^^
