### ISSUE TITLE
backup does not backup gitlab-branch-source-plugin

### ISSUE THREAD

**Issue by DanArlowski** [jenkinsci/kubernetes-operator#643]
**Describe the bug**
the backup does not backup gitlab organization folder

**To Reproduce**
create an organization folder using gitlab-branch-source plugin & a seed job, run a job, wait for backup to run
and delete the jenkins pod so it'll be recreated

**Additional information**
Gitlab source branch plugin version: 1.5.8

Kubernetes version: 1.19
Jenkins Operator version:0.5.0

Add error logs about the problem here (operator logs and Kubernetes events).
(backup logs are pretty useles... only this)

```
Trimming to only 3 recent backups in preparation for new backup
Trimming to only 3 recent backups in preparation for new backup
Trimming to only 3 recent backups in preparation for new backup
Trimming to only 3 recent backups in preparation for new backup
Trimming to only 3 recent backups in preparation for new backup
Trimming to only 3 recent backups in preparation for new backup
Trimming to only 3 recent backups in preparation for new backup
Trimming to only 3 recent backups in preparation for new backup
Trimming to only 3 recent backups in preparation for new backup
Trimming to only 3 recent backups in preparation for new backup
Trimming to only 3 recent backups in preparation for new backup
Trimming to only 3 recent backups in preparation for new backup
Trimming to only 3 recent backups in preparation for new backup
Trimming to only 3 recent backups in preparation for new backup
```

**Comment by prryb** [comment]
Hey @DanArlowski, 

are you using configuring the seed job through the `Jenkins` Custom Resource (or the helm chart)?

Jenkins CR v1alpha2 schema: https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/schema/#github.com/jenkinsci/kubernetes-operator/pkg/apis/jenkins/v1alpha2.JenkinsSpec

Helm Chart `values.yaml`: https://github.com/jenkinsci/kubernetes-operator/blob/master/chart/jenkins-operator/values.yaml

The seed job configured by the operator will be run automatically when the pod is created and should create all the necessary jobs.

The goal of the backup script is to backup whatever cannot be configured via CaSC, Groovy, or other means. In practice that mostly means job history and artifacts (actual jobs are intentionally excluded).

**Comment by prryb** [comment]
See https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/configuring-seed-jobs-and-pipelines/#configure-seed-jobs for details.

**Comment by DanArlowski** [comment]
The seed job was configured by the CRD, but the problem is that the gitlab organization folder, created with gitlab source plugin does not get backed up,
I suspect due the way they save and manage their folder, logs of both jenkins and backup gave nothing of value.

**Comment by prryb** [comment]
That's what I was afraid of – that "Organization folders" in `gitlab-branch-source` store jobs differently. You can create a custom backup container image for your specific use case.

The backup container image is built from these sources: https://github.com/jenkinsci/kubernetes-operator/tree/master/backup/pvc

The actual backup script looks like this: https://github.com/jenkinsci/kubernetes-operator/blob/master/backup/pvc/bin/backup.sh

If you're using the helm chart you could overwrite the backup image by setting `jenkins.backup.image`. if not, more details are here: https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/configuring-backup-and-restore/

**Comment by Sig00rd** [comment]
Closing this as the workaround has been provided
