### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by crytome1995** [jenkinsci/kubernetes-operator#650]
**Relevant links**
https://jenkinsci.github.io/kubernetes-operator/docs/installation/

**Description**
Why are previous versions installation steps throwing 404's?

**Comment by Sig00rd** [comment]
Hello @crytome1995,
Instructions on installing the Operator were previously available at the address you mentioned and covered the latest version, but were recently moved to https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/installing-the-operator .
Where are you getting the link to the old installation page from? I've been fixing broken links that were made for the old layout, though it seems I've missed a few.

**Comment by Sig00rd** [comment]
Closing this because of lack of response from the author
