### ISSUE TITLE
Boot loop with large volumes

### ISSUE THREAD

**Issue by andrewm-aero** [jenkinsci/kubernetes-operator#652]
**Describe the bug**
When a large volume is attached, and fsGroup is set in securityContext, the chmod performed by kubelet after mounting volumes can take longer than 2 minutes for the master pod to move out of the "Pending" phase. Because the operator has a hard-coded timeout for the master pod to move out of Pending, this causes a loop where the operator terminates the pod before kubelet has a chance to finish chmod'ing the volume. If the operator is disabled after starting the pod, it starts normally.

**To Reproduce**
1. Create a persistentVolumeClaim, add a sufficient number of files to the volume
2. Add a volume and volumeMount to the Jenkins spec for the PVC
3. Set the securityContext.fsGroup in the Jenkins spec
4. Delete master pod, observe resulting boot loop
5. Scale down operator deployment to 0 after master pod has been recreated, observe master pod starting correctly

**Additional information**
https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
https://github.com/kubernetes/kubernetes/issues/95587
https://github.com/kubernetes/examples/issues/260
https://github.com/jenkinsci/kubernetes-operator/blob/3a143a08316f4935414b3f935f2c2b44def311a1/pkg/configuration/base/reconcile.go#L310

Kubernetes version: 1.20.5
Jenkins Operator version: v0.5.0 (Also confirmed with v0.6.0 locally)

Add error logs about the problem here (operator logs and Kubernetes events).
N/A

**Comment by MKajzik** [comment]
Hello, could you post Operator logs and more precise information about the size of volume? That would be very helpful for us to find the cause of the problem.

**Comment by Sig00rd** [comment]
Closing this as the requested info wasn't provided. If you find this issue still relevant, please bump it!
