### ISSUE TITLE
Support to set http proxy

### ISSUE THREAD

**Issue by leonj1** [jenkinsci/kubernetes-operator#67]
Access to the internet to install plugins is behind a proxy. 
But its unclear where to set that in the operator.

**Comment by placydo** [comment]
Hey,
Use configuration as code:
https://github.com/jenkinsci/kubernetes-operator/blob/master/docs/getting-started.md#jenkins-customisation
Here is sample configuration:
https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/proxy

**Comment by leonj1** [comment]
Did more digging. I'm in an environment where I "have to" set an http_proxy to pull from the internet.
Therefore, when the "curl" command at startup is invoked it cannot connect out.
So, I need a way to set the http_proxy at POD startup.
But, the operator handles this, therefore I do not know how to tell the operator to set that env var for Jenkins instances. Any idea?

**Comment by tomaszsek** [comment]
Hi @leonj1,

You can set it like in official docker image https://github.com/jenkinsci/docker/blob/master/install-plugins.sh#L95. Environment variables can be set in `spec.master.containers['jenkins-master'].env` https://github.com/jenkinsci/kubernetes-operator/blob/master/docs/jenkins-v1alpha2-scheme.md.
Could you add section to https://github.com/jenkinsci/kubernetes-operator/blob/master/docs/getting-started.md with instruction step by step?

Thanks in advance
