### ISSUE TITLE
Configuring backup and restore

### ISSUE THREAD

**Issue by khongten1452** [jenkinsci/kubernetes-operator#673]
**Relevant links**
Link(s) to the section(s) of documentation that are outdated or otherwise wrong
https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/installing-the-operator/
https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/configuring-backup-and-restore/

**Description**

There is no "getLatestAction" in io.jenkins.v1alpha2.Jenkins.spec.backup in the Backup section in the operator link, 
but in the configuring link, the yaml has that.   

Description of the changes you would like to see
Removing "getLatestAction", or adding it in crd

**Comment by piteros83** [comment]
yes, I also have this problem. To be honest, it's pretty basic feature to have job history in Jenkins, but it's not working :(

```
$ k explain Jenkins.spec.backup
KIND:     Jenkins
VERSION:  jenkins.io/v1alpha2

RESOURCE: backup <Object>

DESCRIPTION:
     Backup defines configuration of Jenkins backup More info:
     https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/configure-backup-and-restore/

FIELDS:
   action	<Object> -required-
     Action defines action which performs backup in backup container sidecar

   containerName	<string> -required-
     ContainerName is the container name responsible for backup operation

   interval	<integer> -required-
     Interval tells how often make backup in seconds Defaults to 30.

   makeBackupBeforePodDeletion	<boolean> -required-
     MakeBackupBeforePodDeletion tells operator to make backup before Jenkins
     master pod deletion
```
