### ISSUE TITLE
Support seed-job configuration through Jenkins.spec.seedJobs

### ISSUE THREAD

**Issue by mxandeco** [jenkinsci/kubernetes-operator#69]
We would like to configure the Seed Job created by the operator, we are particularly  interested 
in configuring:

- Build Trigger:
  - Build periodically
  - GitHub hook trigger for GITScm polling
  - Poll SCM
- Build
  - Ignore missing files
  - Additional classpath
  - Fail build if a plugin must be installed or updated
  - Mark build as unstable when using deprecated features 

Looks like the only way to have that support is to extend the CRD?

Just to be clear, we do not mean the `jenkins-operator-configure-seed-job`, but the jobs generated from that.

**Comment by tomaszsek** [comment]
Added in https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.2.0
