### ISSUE TITLE
Add support for Jenkins-style 'H' seed job's cron field

### ISSUE THREAD

**Issue by surmabck** [jenkinsci/kubernetes-operator#695]
**Describe the bug**
Currently, it is not possible to configure seed jobs using Jenkins-style 'H' hashed field value, cuz Jenkins Operator's validation is delegating cron expression validation to [robfig/cron](github.com/robfig/cron) which obviously does not support it. 
'H' expressions are really cool feature of Jenkins which Jenkins native operator should support.

**To Reproduce**
Declare seed job with 
```
buildPeriodically: 'H/10 * * * *'
```
and observe operator output

**Additional information**
This is the line which is causing it 
https://github.com/jenkinsci/kubernetes-operator/blob/3a143a08316f4935414b3f935f2c2b44def311a1/pkg/configuration/user/seedjobs/validate.go#L123

Kubernetes version:
1.21.1
Jenkins Operator version:
0.7.0

Add error logs about the problem here (operator logs and Kubernetes events).
N/A

**Comment by prryb** [comment]
That validation is gone for now. Released in v0.7.1.
