### ISSUE TITLE
Do not deploy CRD for cert-manager when webhook.enabled = false

### ISSUE THREAD

**Issue by marcportabellaclotet-mt** [jenkinsci/kubernetes-operator#696]
**Describe the solution you'd like**
Right now, cert-manager is deployed when jenkins operator is installed with the helm chart.
It would be great if this deployment was optional, and configured via values files.
This prevents using the desired version and config of cert-manager. In my scenario, I am using cert-manager for other use cases, and installing jenkins-operator, forces the certmanafer CRD to a specific version.

**Describe alternatives you've considered**

Adding an if statement in the cert-manager CRD jenkins-operator templates, could help to decide to install them or not.

Also in the chart cert-manager dependency a condition could be added to allow to create or not the resources

**Comment by marcportabellaclotet-mt** [comment]
After some more investigation, it seems that the problem could be easily solved by adding a couple of lines in the cert-manager.crds.yaml file:
```
{{- if .Values.webhook.enabled -}}
---
{{- end }}
```
I can open a PR with the proposed changes.

**Comment by dafenko** [comment]
We hit the same problem. I had to install jenkins operator without CRDs (from helm) and install CRD manually as separate step.
It would be good to have it fixed.

**Comment by yagilm** [comment]
Do we have any update in regards to that? Clusters that have a cert-manager already in place get a `SharedResourceWarning`  (cert-manager and jenkins-operator fight for controlling these resources)

**Comment by rarecrumb** [comment]
This issue should not be stale.

**Comment by mortenbirkelund** [comment]
I dont understand. Isnt this allready implemented here?
https://github.com/jenkinsci/kubernetes-operator/blob/c39eaa95b7656d753b76b028827b3a77e0b61638/chart/jenkins-operator/Chart.yaml#L10

From reading the helm documentation it should work, however I am facing the same problem.

**Comment by mortenbirkelund** [comment]
My bad, the CRD is not kept in the subchart but in this chart. 

@marcportabellaclotet-mt You never opened the Pull request. Is there any problem with the approach, or is it simply a matter of adding the checks in the CRD?

**Comment by marcportabellaclotet-mt** [comment]
I think this project is "dead", as there is no much movement, and there are a lot of pending issues, it does not work with current jenkins versions..
I did not open the PR, because there was no official response for the maintainers of this project.

**Comment by mortenbirkelund** [comment]
I agree that was the situation, however recently there have been some commits from new people. Perhaps give it a chance and see.

**Comment by marcportabellaclotet-mt** [comment]
The thing is that in our use case, we already migrated to use standard [helm for jenkins](https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins), which give us most of the features that jenkins operator does, as it is supports jcasc, init scripts, custom plugin selection.... 
Jenkins operator has a lot of issues, and from my point of view, right now does not add xtra value.

**Comment by brokenpip3** [comment]
Unfortunately this is not possible due to how helm treat the crds (check the bold text):

>With the arrival of Helm 3, we removed the old crd-install hooks for a more simple methodology. There is now a special directory called crds that you can create in your chart to hold your CRDs. **These CRDs are not templated**, but will be installed by default when running a helm install for the chart. If the CRD already exists, it will be skipped with a warning. 

from: https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-2-separate-charts

Let me understand why we have that crd there in the first place and if we can safely remove it since we have the conditional certmanager dependency in our chart.yaml
