### ISSUE TITLE
Configurable agent image for seed jobs

### ISSUE THREAD

**Issue by dafenko** [jenkinsci/kubernetes-operator#700]
**Describe the solution you'd like**
Currently agent image is hardcoded in agent deployment:
https://github.com/jenkinsci/kubernetes-operator/blob/0f507409ccf3d5b01d9cdb8cb576c51648972baf/pkg/configuration/user/seedjobs/seedjobs.go#L446

We are forced to build our own agent image (based on standards vanilla agent) and add certain tools to it.
Currently we have no possibility how to configure alternate agent image in agent deployment.

I would propose to add additional property in seedJobs section of the jenkins object called image or agentImage
(somewhere here: https://github.com/jenkinsci/kubernetes-operator/blob/0f507409ccf3d5b01d9cdb8cb576c51648972baf/chart/jenkins-operator/crds/jenkins-crd.yaml#L3122)
that could be use to define custom agent image in jenkins cro.

**Describe alternatives you've considered**
I see no alternative for our case.

**Additional context**

**Comment by thegolabek** [comment]
Hi @dafenko, we're working on bringing this functionality to the operator with introduction of the new API. We're currently in progress of preparing the update. Simultaneously, we're developing the [Operator Service](https://operator-service.com), and a different API that the API fed to the Jenkins operator is going to be based on is introduced there already - you're more than welcome to have a look at it; perhaps there's some more features there you'd find interesting.

**Comment by bhubert** [comment]
i missed that issue and did a pull request doing what you requested  : https://github.com/jenkinsci/kubernetes-operator/pull/718
