### ISSUE TITLE
hope to add agent image replacement feature and Gitlab automatically triggers seed job

### ISSUE THREAD

**Issue by y496237839** [jenkinsci/kubernetes-operator#702]
**Describe the solution you'd like**
add agent image replacement feature. 
I can't access the Internet in my private network environment, so I hope all container images can be modified into private docker registry in the way of configuration

add Gitlab automatically triggers seed job
My project is managed by gitlab, so I hope seed-job-agent-jenkins can be updated automatically after modifying the configuration under cicd/job/* . Now the page configuration of Jenkins cannot be persistent

**Describe alternatives you've considered**
Independent yaml configuration or added control parameters

**Additional context**
  Normal   Pulling    3m23s (x4 over 5m32s)  kubelet            Pulling image "jenkins/inbound-agent:4.9-1"
  Warning  Failed     3m6s (x4 over 5m16s)   kubelet            Failed to pull image "jenkins/inbound-agent:4.9-1": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  Failed     3m6s (x4 over 5m16s)   kubelet            Error: ErrImagePull
  Warning  Failed     2m38s (x6 over 5m15s)  kubelet            Error: ImagePullBackOff
  Normal   BackOff    22s (x14 over 5m15s)   kubelet            Back-off pulling image "jenkins/inbound-agent:4.9-1"

![image](https://user-images.githubusercontent.com/19207354/150899862-e8f2ba5b-9536-47d7-b33b-84dddc5f7f5c.png)

**Comment by brokenpip3** [comment]
>so I hope seed-job-agent-jenkins can be updated automatically after modifying the configuration under cicd/job/*

did you tried the one of these 2?

```
buildPeriodically  string | (Optional) BuildPeriodically is setting for scheduled trigger
-- | --
pollSCM  string | (Optional) PollSCM is setting for polling changes in SCM

```
from: https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/schema/

**Comment by y496237839** [comment]
No, these methods take some time. I hope they will take effect immediately after I update the code, such as webhook.Currently, it is a manually configured webhook after startup.
And, the seed-job-agent-jenkins pod image cannot be replaced，I can only use the default image jenkins/inbound-agent: 4.9-1.This is not convenient in a private environment.

**Comment by brokenpip3** [comment]
>No, these methods take some time. 

If you add  a pollSCM every 5min I think it's a valid workaround right? It will check if any changes on branch and if true it will start the seed job to gather the new jobs conf.

> I hope they will take effect immediately after I update the code, such as webhook.Currently, it is a manually configured webhook after startup.

Ok understood, I think that a generic webhook can be a good thing for the community, unfortunately not a priority at moment, I can add this to the 0.10 milestone.

>And, the seed-job-agent-jenkins pod image cannot be replaced，I can only use the default image jenkins/inbound-agent: 4.9-1.This is not convenient in a private environment.

This is not true, it's possible :) : https://github.com/jenkinsci/kubernetes-operator/commit/a8065cc03898f85742c65b8ded8fcf36c9e6b84f

**Comment by brokenpip3** [comment]
hi @y496237839 any feedback?

**Comment by y496237839** [comment]
> 

You're right. I am not using the helmtool to install, just because I have not found instructions in the documentation and do not know how to configure them.
![image](https://user-images.githubusercontent.com/19207354/226611903-6ec26385-ab03-4f19-ac1f-1b9561bbd1ca.png)

**Comment by brokenpip3** [comment]
Here you can find the instruction to use helm: https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/installing-the-operator/ 
Let me know if you see any issue there :)
