### ISSUE TITLE
Add option of "nodeSelector" in the chart templates/jenkins.yaml

### ISSUE THREAD

**Issue by ccwumao** [jenkinsci/kubernetes-operator#707]
Hi,

I need to specific the node that the jenkins pod will be deployed, but the "nodeSelector" is not optionally in the templates/jenkins.yaml.

ex like this : 
```
  master:
    {{- with .Values.jenkins.nodeSelector }}
    nodeSelector: {{ toYaml . | nindent 6 }}
    {{- end }}
```
![image](https://user-images.githubusercontent.com/11351177/152597346-097f6f06-7f44-4f39-a769-11ea86a1b656.png)

I think it's a necessary options for some use-cases. Please consider to add it please. Thanks a lot :)

**Comment by ccwumao** [comment]
add : I talk about the jenkins-operator helm-chart, in the path : chart/jenkins-operator/templates/jenkins.yaml.

**Comment by brokenpip3** [comment]
Hi @ccwumao since you already created the go template if code what about creating a PR for that? I'm adding the "good first issue" label

**Comment by brokenpip3** [comment]
it's already there: https://github.com/jenkinsci/kubernetes-operator/blob/e36441a4a20b27a89199d05d827bb0d023b8dd75/chart/jenkins-operator/values.yaml#L28
