### ISSUE TITLE
jenkins cli not working on jenkins deployment with jenkins-operator

### ISSUE THREAD

**Issue by pasokan-ddn** [jenkinsci/kubernetes-operator#708]
**Describe the bug**

jenkins cli not working on jenkins deployment with jenkins-operator

![image](https://user-images.githubusercontent.com/92999643/152757750-6d1cab22-a0a2-4c93-a415-965b01959f48.png)

**To Reproduce**
helm install jenkins-operator jenkins/jenkins-operator --values test-jenkins-operator.values -n test-jenkins --set jenkins.namespace=test-jenkins

access Jenkins through load balancer IP or Port forwarding 

**Additional information**

Kubernetes version:
v1.23.1+k3s2

Jenkins Operator version:
Latest (v0.7.x)

Add error logs about the problem here (operator logs and Kubernetes events).

**Comment by DionJones615** [comment]
https://jenkinsci.github.io/kubernetes-operator/docs/security/

> The list below describes all the default security setting configured by the Jenkins Operator:
> - basic settings - use Mode.EXCLUSIVE - Jobs must specify that they want to run on master node
> - enable CSRF - Cross Site Request Forgery Protection is enabled
> - disable usage stats - Jenkins usage stats submitting is disabled
> - enable master access control - Slave to Master Access Control is enabled
> - disable old JNLP protocols - JNLP3-connect, JNLP2-connect and JNLP-connect are disabled
> - **disable CLI - CLI access of /cli URL is disabled**
> - configure kubernetes-plugin - secure configuration for Kubernetes plugin
>
> If you would like to dig a little bit into the code, take a look [here](https://github.com/jenkinsci/kubernetes-operator/blob/master/pkg/configuration/base/resources/base_configuration_configmap.go).

**Comment by pasokan-ddn** [comment]
@DionJones615 Thanks for that information!
