### ISSUE TITLE
Invalid plugin name validation in the Jenkins crd.

### ISSUE THREAD

**Issue by mxandeco** [jenkinsci/kubernetes-operator#72]
Underscore is a valid plugin name in jenkins, e.g. [http_request](http://mirrors.jenkins-ci.org/plugins/http_request/) but it won't be accepted by the operator.

```
base/validate.go:233	invalid plugin name 'http_request:1.8.23', must follow pattern '^[0-9a-z-]+$'
```

What makes impossible to have that plugin installed using the `Jenkins` crd.

Can the `_` be added as a valid character to the plugin list?

**Comment by tomaszsek** [comment]
Fixed in https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.2.0
