### ISSUE TITLE
Can you provide examples of deploying a jenkins instance with custom helm chart

### ISSUE THREAD

**Issue by mambon2** [jenkinsci/kubernetes-operator#721]
We currently deploy Jenkins instance with a customized helm chart.  Is there any way Jenkins Operator can manage this instance as it does not use the custom CRD schema for the operator?

**Comment by thecooldrop** [comment]
I think I know what you want but I am not sure. Could you please provide more details to your question?

**Comment by thecooldrop** [comment]
I am assuming you are asking us how to write a chart which deploys the Jenkins Operator and Jenkins instance. The official chart is an example of how to do that, but if you do need something changed you will have to write your own chart. This seems to be more of a "How to write Helm chart" type of question, and does not seem to have anything to do with the operator. Is that correct @mambon2 ?

**Comment by mambon2** [comment]
@thecooldrop actually we already have a helm chart for our Jenkins instance and would rather not have to migrate it to a custom CRD schema.  That's that clarify the question?

**Comment by thecooldrop** [comment]
So if I understand correctly you would like to have the existing Pod managed by the Jenkins operator? Basically you would like to transfer the ownership of existing Pod to the operator, so that you do not have to "replace" your instance, but rather just delegate the management to the operator? 

Please forgive me for asking, but I am trying to flesh out what the request exactly is as to best help you.

**Comment by mambon2** [comment]
Yes I suppose that's true.  I assumed you'd have to change Jenkins operator to understand helm chart CRD schema.

**Comment by thecooldrop** [comment]
As far as I am aware currently such behavior is not possible out-of-the box. It may be possible to force such behavior by changing the Pod so that it "thinks" that it is being managed by Jenkins CRD. This would most likely require chaning the ownership metadata and list of managed fields.

**Comment by brokenpip3** [comment]
>@thecooldrop actually we already have a helm chart for our Jenkins instance and would rather not have to migrate it to a custom CRD schema. That's that clarify the question?

the tldr is that you can't do that. You need to proper migrate your running jenkins instance to a crd that will represent the same so the operator will be able to handle it.
Will close the issue, add more comments if you need more clarification.
