### ISSUE TITLE
Verifying resources created by the Operator

### ISSUE THREAD

**Issue by devdattakulkarni** [jenkinsci/kubernetes-operator#725]
I wanted to check regarding the K8s resources that are created by the Jenkins Operator as part of handling a Jenkins CR instance. Through our [``kubectl connections`` plugin](https://github.com/cloud-ark/kubeplus#kubectl-plugins-for-discovery-monitoring-and-troubleshooting) we were able to discover following resource relationship graph corresponding to a Jenkins CR instance. Is this accurate? If not, which other resources are missing and how are they related to the Jenkins CR instance (through spec properties or owner references or labels or annotations)?

![jenkins-connections-output](https://user-images.githubusercontent.com/732525/157160393-79197a1a-331c-4215-b5f5-f9fe1805e498.png)

**Comment by thecooldrop** [comment]
Please use ArgoCD or something similar to find relationships out. I do not see how this is an issue to be worked on. I vote to close.

**Comment by devdattakulkarni** [comment]
@thecooldrop Thanks for the reply. You are correct - this is not an issue to be worked on. I just wanted to check with the Operator development team whether the resources that are seen in the above topology are accurate.

**Comment by thecooldrop** [comment]
While I understand, I do not think anyone is ready to invest their effort to take over your task. Due to this reason I would like to ask @Sig00rd to close this issue.
