### ISSUE TITLE
Release v0.7.0 contains app v0.6.0

### ISSUE THREAD

**Issue by tomvopat** [jenkinsci/kubernetes-operator#731]
**Describe the bug**
The latest release [v0.7.0](https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.7.0) contains old chars (the newest chart is of version 0.6.0).

**To Reproduce**
Go to the release v0.7.0 and open the [archive](https://github.com/jenkinsci/kubernetes-operator/archive/refs/tags/v0.7.0.tar.gz).

**Additional information**
No additional information.

**Comment by brokenpip3** [comment]
Closing as obsolete, the latest version of the helm chart contains the right [chart version](https://github.com/jenkinsci/kubernetes-operator/blob/v0.8.0-beta/chart/jenkins-operator/Chart.yaml) :)
