### ISSUE TITLE
0.7.0 Liveness & Readiness probes are getting failed for the Jenkins instance.

### ISSUE THREAD

**Issue by PrasadTelasula** [jenkinsci/kubernetes-operator#737]
I Had installed the Jenkins 0.7.0 operator and it was successfully. While creating the Jenkins instance the pod is not running.

```
Liveness probe failed: HTTP probe failed with statuscode: 503
  Warning  Unhealthy  50s                kubelet            Readiness probe failed: HTTP probe failed with statuscode: 503
  Normal   Killing    32s                kubelet            Stopping container jenkins-master
  Normal   Killing    32s                kubelet            Stopping container backup
  Warning  Unhealthy  10s (x3 over 30s)  kubelet            Liveness probe failed: Get "http://10.42.0.235:8080/login": dial tcp 10.42.0.235:8080: connect: connection refused
  Warning  Unhealthy  10s (x3 over 30s)  kubelet            Readiness probe failed: Get "http://10.42.0.235:8080/login": dial tcp 10.42.0.235:8080: connect: connection refused

**Comment by my10c** [comment]
For me it started when we upgraded to EKS 1.21, an older cluster running 1.19 (soon no longer supported) does not have the issue, changing the value of combination of the Liveness and/or Readiness did not help 
step i took
- delete the CRD
- remove the probe in my values files
- tries 0.6.0 / 0.6.2 / 0.6.3
no dice, same error
Liveness probe failed: Get "http://x.x.x.x:8080/login": dial tcp x.x.x.x:8080: connect: connection refused
A quick curl work just fine, the operator comes just fine... is the master that is issue ...

**Comment by my10c** [comment]
update 
- made sure to use the jenkins:tls image instead an old version
-  removed the blue ocean plugin
-  made sure the plugins version are updated
then redeploy and is not working ...

the log never showed that there was any plugin error, but at least is up and we have 180+ job

**Comment by VinayakKukreja** [comment]
+1, I am seeing the same when trying to follow the example [here](https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/deploying-jenkins/).

**Comment by brokenpip3** [comment]
Could you please try the latest master branch helm charts and let me know if this issue persist? 
If yes only the k8s pod events are not enough to troubleshot the issue, please also add the operator and jenkins logs.
thanks

**Comment by WesselAtWork** [comment]
Ran into this as well.
Tried from inside the pod and from a network pod outside.
Works
Checked EKS Flow logs which I can see is allowing the probes.
No idea what is causing it

**Comment by brokenpip3** [comment]
can you share some logs? like operators logs, jenkins logs, describe the pod output

Also are you running the latest version? 0.8.0beta? 
thanks

**Comment by WesselAtWork** [comment]
Also set the Failure threshold to something ludicrous like 50 but the pod gets terminated after 3 attempts

**Comment by WesselAtWork** [comment]
With the beta I am in a restart loop.
The moment the pod starts it is immediately terminated.
The operator logs don't mention why, doesn't look like it coming from k8s

**Comment by WesselAtWork** [comment]
Looks like it is plug-ins related.
Getting versioning errors on the base-plugins.
Resetting the `base-plugins` field in the jenkins resource fixed it

**Comment by WesselAtWork** [comment]
Jenkins is up and running and seems to be stable!

**Comment by WesselAtWork** [comment]
Running LTS too so the plugin-cli works fine!

**Comment by WesselAtWork** [comment]
Unrelated to this issue but it looks like the operator has a memory leak.
The memory usage before was un-remarkable (like most operators) but now it seems to be growing out of controll

**Comment by brokenpip3** [comment]
Thanks for report the status back! :) 
I'm glad it worked, you can safe use the version 0.8.0-beta, it's stable despite the name :)
closing the issue
