### ISSUE TITLE
WARN: install-plugins.sh is deprecated

### ISSUE THREAD

**Issue by samuelbernardolip** [jenkinsci/kubernetes-operator#739]
**Describe the bug**
WARN: install-plugins.sh is deprecated, please switch to jenkins-plugin-cli

**To Reproduce**
Deploy a jenkins instance with operator snapshot virtuslab/jenkins-operator:29c5b1e and current master CRD resource.

**Additional information**

Kubernetes version:
Jenkins Operator version: 29c5b1e

Add error logs about the problem here (operator logs and Kubernetes events).
Debug message in container logs:
WARN: install-plugins.sh is deprecated, please switch to jenkins-plugin-cli

**Comment by brokenpip3** [comment]
Hi @samuelbernardolip this has been solved with this commit: https://github.com/jenkinsci/kubernetes-operator/commit/60b8ee56debf840f0f6bee45081f23eacd7d2068 please try this version and let me know :)
