### ISSUE TITLE
plugin regex release

### ISSUE THREAD

**Issue by rosscdh** [jenkinsci/kubernetes-operator#745]
**Describe the solution you'd like**
Hi there, I was wondering when the release for https://github.com/jenkinsci/kubernetes-operator/pull/729 was planned?

We are currently affected by a dependency in 0.7.0 and are hoping for a release cycle as it currently blocks.

**Comment by Sig00rd** [comment]
Hi @rosscdh, sorry for the delay, it's been released.

**Comment by rosscdh** [comment]
@Sig00rd thanks a tonne! :)
