### ISSUE TITLE
security vulnerabilities detected in the following base plugins: git:4.10.3"

### ISSUE THREAD

**Issue by pniederlag** [jenkinsci/kubernetes-operator#747]
**Describe the bug**
Build (CIr on master is broken due to security vulnerabilities detected in the following base plugins: \ngit:4.10.3",

**To Reproduce**
check latest build/actions/workflow log on master
https://github.com/jenkinsci/kubernetes-operator/actions/workflows/auto-tests.yaml?query=branch%3Amaster

**Comment by Sig00rd** [comment]
Hello, thanks for reporting this, git plugin vesion was bumped in 0.7.1
