### ISSUE TITLE
jenkins operator  can't seems to run with kubernetesv1.24+

### ISSUE THREAD

**Issue by cyxinda** [jenkinsci/kubernetes-operator#749]
**Describe the bug**
when I install crd whith kubernetes v1.24.0 ,it happend to error as follow:
`[root@node1 crds]# kubectl apply -f jenkins.io_jenkins_crd.yaml
error: resource mapping not found for name: "jenkins.jenkins.io" namespace: "" from "jenkins.io_jenkins_crd.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
ensure CRDs are installed first
`

Kubernetes version:  v1.24.0
Jenkins Operator version: v0.7.0

it seems that  new beta apis will be disabled by default from Kubernetes 1.24+. I am not sure.
How can  I  use jenkins operator?

**Comment by prryb** [comment]
You are using an old CRD. Here's the up-to-date one: https://github.com/jenkinsci/kubernetes-operator/blob/master/config/crd/bases/jenkins.io_jenkins.yaml

As you can see it uses the `apiVersion` of `apiextensions.k8s.io/v1`. 

Not sure where did you get the old one – CRDs were updated to the current API version a bit before v0.7.0.

**Comment by cyxinda** [comment]
I have already installed the jenkins operator by helm.It works.
Thanks all the same.
I have found the old version CRDs at the address [https://github.com/jenkinsci/kubernetes-operator/blob/v0.7.1/deploy/crds/jenkins.io_jenkins_crd.yaml](https://github.com/jenkinsci/kubernetes-operator/blob/v0.7.1/deploy/crds/jenkins.io_jenkins_crd.yaml).
![image](https://user-images.githubusercontent.com/7237898/174927920-cedf05cb-6600-43fe-bcc8-1cf120bf6a06.png)
I still can't find the directory named blob  in github of "https://github.com/jenkinsci/kubernetes-operator".
I want to know where I am wrong.
