### ISSUE TITLE
Operator not able to install plugins cause install-plugin.sh has been removed

### ISSUE THREAD

**Issue by surmabck** [jenkinsci/kubernetes-operator#755]
**Describe the bug**
Operator is not able to install plugins and therefore run jenkins at all because install-plugins.sh has been removed finally. It was in deprecation phase since September 2020. 
Change that causes the bug -> https://github.com/jenkinsci/docker/pull/1408

Unfortunately, due to Jenkins OSS policy to override existing docker images, this bug affects all maintained images. Therefore, it is a major problem that should be addressed asap

**To Reproduce**
Run new, or restart, jenkins instance so Operator will try to download plugins.

**Additional information**

Kubernetes version: doesn't matter
Jenkins Operator version: newest

Add error logs about the problem here (operator logs and Kubernetes events):
```
Installing plugins required by Operator - begin
+ [[ -z '' ]]
+ install-plugins.sh
WARN: install-plugins.sh has been removed, please switch to jenkins-plugin-cli
```

How can be fixed:
Operator should either move to `install-plugin-cli.sh` or download `install-plugin.sh` from here: https://github.com/jenkinsci/docker/blob/a9de6b9fb3a0601e51321bc0ea8c7638db2bf88f/install-plugins.sh on it's own.

**Comment by toabi** [comment]
Maybe it helps somebody: Until the operator is fixed, this jenkins image still works: `2.332.3-lts`
