### ISSUE TITLE
Using custom image based on java11 doesn't work

### ISSUE THREAD

**Issue by rdpa** [jenkinsci/kubernetes-operator#76]
It appears that the operator sets some JAVA_OPTS to tune based on the java8 image, specifically `-XX:+UseCGroupMemoryLimitForHeap`. This option is not present in java 11, and so the JVM fails to start. I can't find a place to override these variables, or tell the operator not to set them.

Edit: [Here](https://github.com/jenkinsci/kubernetes-operator/blob/master/pkg/controller/jenkins/configuration/base/resources/pod.go#L72) is the offending line. Also note that setting `-XX:MaxRAMFraction=1` is not advisable because it carries a high risk of getting the container OOMKilled.

Edit 2: The operator explicitly forbids `JAVA_OPTS` from being overridden

**Comment by tomaszsek** [comment]
Hi @rdpa,

`JAVA_OPTS` is hardcoded now. It will be fixed in the next release. Could you provide your jenkins docker image because we support only `jenkins:lts` for now?

Cheers

**Comment by rdpa** [comment]
Hi, sure. I was attempting to use the `jenkins:lts-jdk11` image. Thanks for the response!

**Comment by tomaszsek** [comment]
Fixed in https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.2.0
