### ISSUE TITLE
Unable to use targetPort under slaveService: sections in Values.yaml

### ISSUE THREAD

**Issue by devops-team-92** [jenkinsci/kubernetes-operator#760]
**Describe the bug**

We are using Jenkins operator using helm chart to create 100 plus  production jenkins master instance . But we are unable to use **targetPort** under **slaveService** sections in **values.yaml**.  If we specifically added targetPort , while applying helm chart giving below error 

**error validating "": error validating data: ValidationError(Jenkins.spec.slaveService): unknown field "targetPort" in io.jenkins.v1alpha2.Jenkins.spec.slaveService**

**To Reproduce**
While install or upgrade Jenkins master using operator if we pass **targetPort** under **slaveService**  in values.yaml we are getting this error.

**Additional information**

After deployment if we update targetPort of jenkins-operator-slave-jenkins service from 50000 to some other port (i.e ex 50001) it is resetting automatically after some time to 50000.

Kubernetes version: **v1.22.8-gke.202**
Jenkins Operator version:  **[v0.7.1]**

Add error logs about the problem here (operator logs and Kubernetes events).

**Comment by devops-team-92** [comment]
![image](https://user-images.githubusercontent.com/44020182/181003321-9fc04a8f-3b02-4af0-8d27-0f78b2ecb920.png)

Adding above screenshot to understand the issue in more clear

So in the above screenshot we need the requirement to update **jenkins-operator-slave-jenkins** service from default 50000 **targetPort** to some other custom port.

**Comment by devops-team-92** [comment]
@all , Please assist on the above issue .

**Comment by venkatprasad33** [comment]
It works! by defining tunnel option while creating slaves.

**Comment by venkatprasad33** [comment]
This issue can be cancelled!
