### ISSUE TITLE
"Real life" groovy scripts

### ISSUE THREAD

**Issue by hsaito** [jenkinsci/kubernetes-operator#763]
**Relevant links**
https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/configuring-seed-jobs-and-pipelines/

**Description**
While this document explains some simple examples, but most real life example would involve configuration a lot more complex, particularly for mounting projects file, etc.
Some example or links to such project that contains pipeline would be very helpful as overall examples of usage scenario using jenkins-operator seem to be very scarce at best...

**Comment by brokenpip3** [comment]
hi @hsaito are these scripts https://github.com/jenkinsci/jenkins-scripts good enough as documentation for you?

**Comment by brokenpip3** [comment]
Hi @hsaito any feedback?

**Comment by brokenpip3** [comment]
Closing of lack of feedback, plus is not 100% related to this project but more a generic Jenkins question.
