### ISSUE TITLE
Nobody is responding to the dedicated forum

### ISSUE THREAD

**Issue by halkeye** [jenkinsci/kubernetes-operator#775]
Hi

I help out on the jenkins discourse, and see you recommend people people using the dedicated section of the jenkins forum for help.
looks like a user did https://community.jenkins.io/t/jenkins-operator-slack-notification/4176, but its been silence ever since.

I would like to see if you are directing people there for help, you contribute to help in general, but specifically any new posts in the dedicated category should be handled by people involved in this project, as the documentation is directing people there.

I believe we can setup slack notifications for that category. If you would like to do so, I would recommend opening a ticket on https://github.com/jenkins-infra/helpdesk/. At the very least you should enable notifications (click the bell button on the top right of https://community.jenkins.io/c/contributing/jenkins-operator/20)

**Comment by srikanthmalyala** [comment]
Yes, @halkeye 
 is this project going to be maintained or will be abandoned? The SLack community is always for any questions.

**Comment by brokenpip3** [comment]
hi @halkeye I recently become maintainer of this project, give me some time to take a look on the dedicated forum :)

**Comment by brokenpip3** [comment]
I replied to all the not answered questions on the jenkins discourse and also subscribed to any new topics there.
I'm going to close this issue, please @halkeye feel free to open a new one or comment if the resolution is not enough for you

**Comment by NotMyFault** [comment]
Thanks for stepping up!

**Comment by brokenpip3** [comment]
yw @NotMyFault :)
