### ISSUE TITLE
Set Content Security Policy  groovy.lang.MissingPropertyException

### ISSUE THREAD

**Issue by giovinazzorocco** [jenkinsci/kubernetes-operator#777]
**Describe the bug**
Due to an issue related to [HTML Publisher Plugin](https://issues.jenkins.io/browse/JENKINS-48764) I need to set the CSP to relax the `sandbox` to `sandbox allow-same-origin`.

I tried to use the customize jenkins as it is explained [here](https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/customizing-jenkins/) creating this groovy script

```
2-set-content-security-policy.groovy: |
    System.setProperty("hudson.model.DirectoryBrowserSupport.CSP", "sandbox allow-same-origin; default-src 'none'; img-src 'self'; style-src 'self';")
```

This is the error I get:
```
'jenkins-configuration' Name '2-set-content-security-policy.groovy' groovy script execution failed, logs :
groovy.lang.MissingPropertyException: No such property: System for class: java.lang.String
````

Is there a way to set the Content Security Policy through the jenkins-operator?

In the jenkins documentation this seems to be the only way to [configuring the content security policy](https://www.jenkins.io/doc/book/security/configuring-content-security-policy/) but that System Property seems to be not available in the groovy script I used.

**Comment by bennythejudge** [comment]
It looks like the issue with this is a missing import:

```
  2-set-content-security-policy.groovy: |
    import hudson.model.*
    System.setProperty("hudson.model.DirectoryBrowserSupport.CSP", "sandbox allow-same-origin; default-src 'none'; img-src 'self'; style-src 'self';")
```
