### ISSUE TITLE
Use PV instead of EmptyDir for jenkins_home volumen

### ISSUE THREAD

**Issue by abhinavgautam07** [jenkinsci/kubernetes-operator#779]
**Current scenario**
As I observed an EmptyDir type of volume is created at JENKINS_HOME location,

**Desired feature**
I should be able to use PV at this location so as to persist jobs and configurations.

**Comment by brokenpip3** [comment]
Hi @abhinavgautam07 the whole flow of this operator is to create everything as code and only backup the history of the jobs.
Adding a persistent volume will goes against this philosophy and currently I don't think we have issue that will need a persistent volume to be fixed.
Feel free to add more questions but I will close this as wont-do.
