### ISSUE TITLE
Q: How to use configuration as a code plugin?

### ISSUE THREAD

**Issue by adaniline-traderev** [jenkinsci/kubernetes-operator#8]
Configuration as a code plugin loads configuration from env variable CASC_JENKINS_CONFIG, or from /home/jenkins/jenkins.yaml file

Could you explain how to use this with Jenkins operator?

Thank you

**Comment by tomaszsek** [comment]
Configuration as a code plugin is installed by default. For now we don't have good solution how to use it with Operator. This feature have high priority for us as well, stay tuned.

**Comment by tomaszsek** [comment]
Added in https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.0.6
