### ISSUE TITLE
vanilla manifest still points to outdated image on docker.com

### ISSUE THREAD

**Issue by pniederlag** [jenkinsci/kubernetes-operator#827]
**Describe the bug**
vanilla manifests (
https://github.com/jenkinsci/kubernetes-operator/blob/master/deploy/all-in-one-v1alpha2.yaml) still point to docker.com for the images while the chart (https://github.com/jenkinsci/kubernetes-operator/blob/master/chart/jenkins-operator/values.yaml) has been migrated to images pulled from quay.io

**To Reproduce**
check above links and see different repositiories being used for the operator image

**Additional information**

Kubernetes version:
Jenkins Operator version: github master branch

**Comment by brokenpip3** [comment]
do you think we need to continue to support the all in one files? Will be complicated to maintain due to the helm chart as official method

**Comment by brokenpip3** [comment]
@dropte you got me at kustomize/gitops :D 

I will add a CI step that will "helm template" and commit those files here

(btw do you know that flux has a native helm support? I install the jenkins operator, among all the others things, with that)

**Comment by dropte** [comment]
Yes, we use flux elsewhere, but manage our whole stack with ArgoCD and kustomize. Argo can use helm as well, it's just sort of annoying jumping back and forth from kustomize to helm. 

We use two different Argo apps - one for the operator and one for the configuration  and it's nice to do something like this: 

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/config/crd/bases/jenkins.io_jenkins.yaml
  - https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/deploy/all-in-one-v1alpha2.yaml
  - ingress.yaml
```
and then point argo at that.

**Comment by brokenpip3** [comment]
it's an easy CI implementation, will do it shortly

**Comment by brokenpip3** [comment]
I will work on this after this PR: https://github.com/jenkinsci/kubernetes-operator/pull/833

**Comment by brokenpip3** [comment]
hei @pniederlag @dropte I create a workflow that will update automatically the operator image, deploy and rbac, can you check if this PR #864  will satisfy your flow? 

I may need to make it better and clean something there, will do it this week and release a new operator version

**Comment by brokenpip3** [comment]
Should be fixed in this release: https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.8.0-beta2, let me know if you still have problem.
