### ISSUE TITLE
jenkins-operator fails with SAML integration

### ISSUE THREAD

**Issue by dashashutosh24** [jenkinsci/kubernetes-operator#834]
I have added saml plugin and integration with okta via jcasc. The saml is working properly but the operator's reconciliation loop fails probably due to not being able to authenticate to the jenkins API. I have tried by updating credentials secret created by the operator `(jenkins-operator-credentials-CR)` with username and password from one of the Okta users with admin privileges, still operator isn't functioning properly.
<img width="1471" alt="Screenshot 2023-05-07 at 4 09 43 PM" src="https://user-images.githubusercontent.com/108323845/236672650-f4895597-d826-4e93-aedd-de5e2f2ce707.png">

PS: I have tried by setting authorizationStrategy to serviceAccount in jenkins CR spec as well, but it gives similar error.

<img width="1512" alt="Screenshot 2023-05-07 at 5 40 45 PM" src="https://user-images.githubusercontent.com/108323845/236676650-d4444a20-1a18-4163-b646-dfe54c986e16.png">

**Comment by dashashutosh24** [comment]
Can someone help on this? Or is there any workaround for this? This is the only part that’s blocking our migration of Jenkins to Jenkins Operator.

**Comment by brokenpip3** [comment]
There is a lot of closed issues about this (like this one https://github.com/jenkinsci/kubernetes-operator/issues/47), could you try to login in with the robot account, spawn an api token and add that token to the jenkins operator credential secret?
I know for sure that it works because I have the same configuration (saml, robot account etc) in my cluster.

**Comment by dashashutosh24** [comment]
Thanks a lot @brokenpip3 . This worked. Just to clarify over here, any other user besides `jenkins-operator` with admin privileges didn’t work. I created an user with username jenkins-operator in okta and configured the creds in a secret with name `jenkins-operator-credentials-CR` and also assigned admin privileges to this user via CASC before starting jenkins master. It worked afterwards. Since Okta takes email as the default username, so I had to change the format to fit username jenkins-operator.

**Comment by dashashutosh24** [comment]
@brokenpip3 Since there isn’t a lot of documentation of configuring saml with Jenkins, if it’s not being worked upon, I can contribute towards creating one with all the steps followed to configure SAML integration with Jenkins.

**Comment by brokenpip3** [comment]
> I can contribute towards creating one with all the steps followed to configure SAML integration with Jenkins.

Yep that could be great! the PR will be always appreciated. :) You can modify the current ldap one: https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/ldap/ to embrace the saml config as well by adding the appropriate changes.

> Since Okta takes email as the default username, so I had to change the format to fit username jenkins-operator.

This should not be necessary, you can keep the operator user and pw and just change the api token there.
Also if you are using some gitops tool like flux or argo you may want to add the annotation to avoid the reconciliation on that secret :)

**Comment by dashashutosh24** [comment]
@brokenpip3 Assuming you are talking about something like Okta OAuth token, it gets refreshed at fixed period of time. That would mean that token in the secret object also needs to be changed accordingly time to time. If you talking about any other kind of token, could you please elaborate on what kind is that exactly from Okta POV? And what annotation from ArgoCD would need to be used in that case.

**Comment by brokenpip3** [comment]
> If you talking about any other kind of token, could you please elaborate on what kind is that exactly from Okta POV?

I'm talking about the jenkins token here, no okta changes are involved. You don't need any specific name change of the robot account, just log one time with that account in jenkins, create a token from the user panel and replace that token in the secret without changing the default operator user and password.
If I remember correctly this is what I did, but I could be wrong so if you have the time to test it and report it back will be great for everyone :)

**Comment by msharran** [comment]
I am not able to create a separate gmail account for jenkins okta user due to compliance. Is there a work around in Okta or Jenkins where I can create a service account user without creating a new gmail id.

**Comment by dashashutosh24** [comment]
@msharran You don’t have to create a gmail account for jenkins user. I created user for jenkins operator using a random non-existing email id and chose the password myself.

**Comment by msharran** [comment]
@dashashutosh24  Did you create this user in Okta as a service account user ?

**Comment by dashashutosh24** [comment]
No, just as a regular user. Okta->Directory->People->Add User

**Comment by msharran** [comment]
Ok Let me try this. But I guess there is a compliance issue that all users should be human users in Okta. So I guess this will cause trouble.

**Comment by dashashutosh24** [comment]
@msharran Recently I tried by using static username and creds for the operator to authenticate itself, but after removing the user I had created for operator via Okta. It still worked! It seems the operator doesn't need to go via Okta to authenticate itself, you can set any username and creds for it in `jenkins-operator-credentials-<CR>` but make sure to have something like `USER:Overall/Administer:<operator_username>`  in your JCasC so operator can recognise itself as Admin user. CC: @brokenpip3

**Comment by Harguer** [comment]
FYI. I have been using Jenkins operator with SAML for about 2 years, the Jenkins-operator user is local. No need to add to the remote directory server or anything like that. 
Jenkins operator will use Jenkins-operator user token to talk with Jenkins api.

**Comment by msharran** [comment]
But Jenkins only allows one user identity provider right? Either SAML or Jenkins user database. When I freshly install operator and jenkins, operator's creds are from Jenkins user database. But if I setup SAML, won't the operator's user in jenkins user database be deleted?

**Comment by dashashutosh24** [comment]
@msharran When operator starts up it looks for `jenkins-operator-credentials-<CR>` secret resource. If it exists it'll use the creds mentioned in this secret to connect to Jenkins API. If this secret doesn't exist, it'll create one with username set as `jenkins-operator` and use the creds to generate a token to authenticate to Jenkins API. Either way it doesn't go via SAML configured for Jenkins. My assumption is that the token is stored in-memory so it doesn't need Jenkins user database as well. That's why if you don't have `jenkins-operator-credentials-<CR>` secret pre-defined, everytime the operator creates one of its own, the password changes and the resulting token is used to authenticate itself. However if we have matrix auth or role auth enabled, we just to need to make sure to give this operator user ADMIN permissions over Jenkins.
