### ISSUE TITLE
backup/pvc/bin/run.sh fails if backup dir is empty, causing crashloop

### ISSUE THREAD

**Issue by felipejfc** [jenkinsci/kubernetes-operator#85]
When creating a brand new jenkins, if you set a backup sidecar container, it will crash the pod repeatedly...
maybe related to 
```ls ${BACKUP_DIR} | sort -gr | grep 'tar.gz' | tail -n +$((BACKUP_COUNT +1)) | xargs -I '{}' rm ${BACKUP_DIR}/'{}'```
returning non 0? (haven't actually checked it, it's just a guess)

**Comment by tomaszsek** [comment]
Hi @felipejfc,

It was fixed by PR #82. Please use `virtuslab/jenkins-operator-backup-pvc:v0.0.6` Docker image.

Cheers
