### ISSUE TITLE
KinD Cluster: network namespace for sandbox "" is closed - both on wsl and macos

### ISSUE THREAD

**Issue by JCzz** [jenkinsci/kubernetes-operator#853]
I have installed [Jenkins-Operotor](https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/installing-the-operator/) on Kubernetes running in a KinD Cluster on both Windows wsl and Mac M1 chip - same error on both.

I have [deployed](https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/deploying-jenkins/) but are unable to login to localhost:8080 after kubectl port-forward.
`kubectl port-forward jenkins-example 8080:8080`

I get the following error in the terminal, when trying to login with "jenkins-operator" and password "JGUzvhi5CYnj8aXULcCY":

```
E0614 14:47:31.951295   34186 portforward.go:407] an error occurred forwarding 8080 -> 8080: error forwarding port 8080 to pod c7ddde145594e31c9e6385affcabf50dcc60d4eea8f7bf9e847f9ed36262e069, uid : network namespace for sandbox "c7ddde145594e31c9e6385affcabf50dcc60d4eea8f7bf9e847f9ed36262e069" is closed
E0614 14:47:31.954316   34186 portforward.go:233] lost connection to pod
```

**Comment by brokenpip3** [comment]
let's move the discussion here: https://github.com/jenkinsci/kubernetes-operator/issues/856
