### ISSUE TITLE
update configuration-as-code

### ISSUE THREAD

**Issue by pniederlag** [jenkinsci/kubernetes-operator#87]
currently kubernetes-operator "ships" version 1.19 which has some known security-flaws: https://jenkins.io/security/advisory/2019-07-31/#SECURITY-1458

Please update the plugin (and it's companion  configuration-as-code-support) to version 1.29

**Comment by pniederlag** [comment]
well, seems to have been tackled already by 
https://github.com/jenkinsci/kubernetes-operator/commit/33524f88f1a634bdaae04b790b5e84db58e8ca6f#diff-8f513d08c37e5a503ac55f1fb38cc0a2 so it's probably rather a problem of missing a release or using an outdate image ...

**Comment by tomaszsek** [comment]
Hi @pniederlag

You can change version of base plugins in `spec.master.basePlugins`. New release will set up to date plugins if `spec.master.basePlugins` is empty.

Cheers

**Comment by pniederlag** [comment]
Thx for your support! It seems the non semver version properties are somehow tricky, I had to quote them. Seems to work.

If anyone needs to go that route, here is the patch on my operator.yaml

[0001-bugfix-add-all-basePlugins.txt](https://github.com/jenkinsci/kubernetes-operator/files/3569472/0001-bugfix-add-all-basePlugins.txt)

**Comment by pawelprazak** [comment]
Yes, e.g. 1.0 is interpreted as a float and 1.0.0 is interpreted as a
string, it's a YAML thing.

For the record, as suggested above, use quotes for non-semver versions,
e.g.: "1.0"

**Comment by tomaszsek** [comment]
Fixed in https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.2.0
