### ISSUE TITLE
Support S2I

### ISSUE THREAD

**Issue by flickerfly** [jenkinsci/kubernetes-operator#89]
Are there any plans to support Source-to-Image builds? We're working with that now and it is very handy to have a development team simply provide a "Jenkins" folder in their repo that configures the instance of Jenkins used for their project. This way we can easily manage an ephemeral version of Jenkins and keep the configuration under revision control alongside the appropriate project.

The docker image we've been looking at that does support this is here; although I believe others exist. https://quay.io/repository/openshift/origin-jenkins

**Comment by pawelprazak** [comment]
It sounds very interesting, I'm not familiar with this image. Have you tried reconfigure the operator's CR to use this image? Do you see any challenges/gaps?
I'm trying to understand what kind of changes to the operator are we talking about :)

**Comment by tomaszsek** [comment]
Support for S2I won't be added.
