### ISSUE TITLE
Feature request: configure additional environment variables for master pod from secrets

### ISSUE THREAD

**Issue by adaniline-traderev** [jenkinsci/kubernetes-operator#9]
I'd like to pass a secret value to script / SACS config - for example, OATH2 client secret, etc - see example at https://github.com/jenkinsci/configuration-as-code-plugin/blob/5479188627778acca60b56e318bd899bf18ae131/demos/kubernetes-secrets/README.md

Would be nice if in Jenkins.master I could configure additional environment variables ([]core.v1. EnvVar) for the master container

**Comment by tomaszsek** [comment]
I think we should introduce secret which will be automatically mounted in Jenkins for configuration purpose as a default. Then configuration as a code plugin or groovy scripts can use it.

Of course we can give possibility to configure pod envs as well, but every change will cause Jenkins master pod to restart which we try to avoid.

**Comment by adaniline-traderev** [comment]
Still, I think it would be nice to be able to set env variables or mount user's config maps or secrets as volumes for the master pod - along the lines of podTemplate

**Comment by tomaszsek** [comment]
@adaniline-traderev Now you can use secrets in CasC - https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.0.6

**Comment by tomaszsek** [comment]
@adaniline-traderev Added in https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.0.10
