### ISSUE TITLE
Addition of Persistent volume claims in jenkins deployment file

### ISSUE THREAD

**Issue by richamishra006** [jenkinsci/kubernetes-operator#905]
Hi All,
i am using jenkins operator. i want to mount a dir at some path using persistent volume. I tried adding the volume mount and volume section in the yaml file, but the operator failed with the error that CR definition is not valid.
The goal is to use shared volume, and use that volume (with the data on the mounted path) across the jenkins agents on k8s as well
Can someone help me

**Comment by brokenpip3** [comment]
if you can share jenkins CR, the changes you did and the operator logs we can try to understand, like this it's impossible.

**Comment by brokenpip3** [comment]
any news?
