### ISSUE TITLE
LDAP example yaml not formatted

### ISSUE THREAD

**Issue by lhupfeldt** [jenkinsci/kubernetes-operator#937]
**Relevant links**
https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/ldap/

**Description**
![image](https://github.com/jenkinsci/kubernetes-operator/assets/1584329/e9badf36-5322-4986-9140-484733a5425d)

**Comment by AniketNS** [comment]
hey @lhupfeldt, I'd like to work on this issue. Assign this issue to me.

**Comment by lhupfeldt** [comment]
@AniketNS I cannot assign this to you, I am not a member of the project. You can probebly just create a PR and reference this issue.

**Comment by AniketNS** [comment]
Sure

**Comment by AniketNS** [comment]
Hey @lhupfeldt I've opened the [PR](https://github.com/jenkinsci/kubernetes-operator/pull/951) for this issue. Can you please check and tell me what else changes should I make in this repository?
