### ISSUE TITLE
CRDs 

### ISSUE THREAD

**Issue by sbandaru08** [jenkinsci/kubernetes-operator#975]
**Describe the bug**
I know that Kubernetes CRDs are only supported at cluster scope, so i need to be a cluster admin to install them. As am not an admin of the cluster because of permissions issue

Is there any other way i can deploy

**To Reproduce**
Steps to reproduce the behavior.

**Additional information**

Kubernetes version:
Jenkins Operator version: 0.8.0

Add error logs about the problem here (operator logs and Kubernetes events).

**Comment by brokenpip3** [comment]
>Is there any other way i can deploy

no you can't, you need at least the grants in your user rbac to create and modify the crds at cluster level.
You can try install jenkins with the official helm chart: https://github.com/jenkinsci/helm-charts
