### ISSUE TITLE
bash: line 1: /usr/bin/tini: No such file or directory

### ISSUE THREAD

**Issue by gubinjie** [jenkinsci/kubernetes-operator#976]
1、The k8s Jenkins operator installation steps follow the following path: https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/v0.6.x/installing-the-operator/
2、jenkins_instance.yaml file format
`apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: example
  namespace: default
spec:
  configurationAsCode:
    configurations: []
    secret:
      name: ""
  groovyScripts:
    configurations: []
    secret:
      name: ""
  jenkinsAPISettings:
    authorizationStrategy: createUser
  master:
    basePlugins:
    - name: kubernetes
      version: "4029.v5712230ccb_f8"
    - name: workflow-job
      version: "1385.vb_58b_86ea_fff1"
    - name: workflow-aggregator
      version: "596.v8c21c963d92d"
    - name: git
      version: "5.2.0"
    - name: job-dsl
      version: "1.85"
    - name: configuration-as-code
      version: "1700.v6f448841296e"
    - name: kubernetes-credentials-provider
      version: "1.234.vf3013b_35f5b_a"
    disableCSRFProtection: false
    containers:
      - name: jenkins-master
        image: jenkins/jenkins:2.426.2-alpine
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 12
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 100
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 80
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 1500m
            memory: 3Gi
          requests:
            cpu: "1"
            memory: 500Mi
  seedJobs:
    - id: jenkins-operator
      targets: "cicd/jobs/*.jenkins"
      description: "Jenkins Operator repository"
      repositoryBranch: master
      repositoryUrl: https://github.com/jenkinsci/kubernetes-operator.git
`
How to solve this problem?
![image](https://github.com/jenkinsci/kubernetes-operator/assets/37869445/dd8cadd2-3932-4b94-b459-46564eba0750)

**Comment by brokenpip3** [comment]
hello!

there are several different issues here, the one in bold is the real important one:
- the latest getting started is here https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/installing-the-operator/, you were looking on the old 0.6 version
-  the latest operator version is 0.8.0
- **we do not support the alpine version** of the jenkins image: 
~~jenkins/jenkins:2.426.2-alpine~~ use jenkins/jenkins:2.426.2-lts instead

**Comment by gubinjie** [comment]
@brokenpip3 
I used kubernetes-operator v0.7 version and jenkins/jenkins:2.426.2-lts version, but there are still compatibility issues.

![image](https://github.com/jenkinsci/kubernetes-operator/assets/37869445/3cee9dd5-edbe-4655-b31d-7f2ecaf8dd1c)

**Comment by Harguer** [comment]
Hey @gubinjie , as @brokenpip3 posted in his last comment, it only works with the Jenkins operator `latest version` `0.8.0` , it won't work with version `0.7.x`.
